### ISSUE TITLE
Onedrive

### ISSUE THREAD

**Issue by mdhruv1** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#1]
[Enter feedback ]
For file conversion can we get all the to and from formats

The documentation is incomplete 
We do not from and to what is allowed 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a93c9d5d-a9ba-bc6e-e978-c835c3415da6
* Version Independent ID: 9e792056-8840-b6fa-b3ae-cc4516c48134
* Content: [OneDrive - Connectors](https://docs.microsoft.com/en-us/connectors/onedrive/#convert-file-using-path)
* Content Source: [docs/onedrive/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/onedrive/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment]
Hi @mdhruv1 - I'm not sure what you mean by "to and from formats".

The actions and triggers you find listed in our documentation should be the functionality of the connector, not the end API. 

Is there connector functionality that is not listed in the documentation, or are you making a feature request for the connector to be updated with more functionality?

**Comment by mdhruv1** [comment]
Hi,
Yes the connector functionality documentation is missing, converting from one file type
To another all are not listed. I wanted to know if we can convert a csv file to excel or
Json file to excel or excel sheet to csv

Thanks

Dhruv

**Comment by dougelliott** [comment]
Thanks for the feedback on this, @mdhruv1. I have engaged the OneDrive team that owns the connector and will provide an update once I have more information.

**Comment by dougelliott** [comment]
The owning team has acknowledged the feedback and said this is something that they may look in to. We will go ahead and consider this as closed. Thanks again!
