### ISSUE TITLE
Can you provide the sample value for each filed such schema?

### ISSUE THREAD

**Issue by chris-han** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#10]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f51644a6-79dc-d6c3-8fe3-620ea99872be
* Version Independent ID: 5f05de0f-d02c-08e6-38b4-35c61cafa095
* Content: [Event Hubs - Connectors](https://docs.microsoft.com/en-us/connectors/eventhubs/#feedback)
* Content Source: [docs/EventHubs/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/EventHubs/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment]
Hello - thank you for your feedback - could you please clarify what you mean by "sample value for each filed such schema"? I will then pass your feedback to the team which owns this connector.

**Comment by bezhan-msft** [comment]
Hello - this issue has been closed due to lack of information. If you have more information to provide, please reopen this issue.
