### ISSUE TITLE
Outlook tasks connector: GetTaskFolders does not return

### ISSUE THREAD

**Issue by alpapan** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#102]
When using OutlookTasks.GetTaskFolders(TaskGroup.Id) it fails to return any valid Folders.

This could be due to changes implemented recently with Microsoft To Do vs Microsoft Outlook Tasks?

Note that when I use exactly the same TaskGroup.Id with a Flow and "List Task folders in group" it works absolutely fine so the error lies with the API somewhere?

**Comment by DougKlopfenstein** [comment]
@alpapan Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) or to the connector-specific support contact (if applicable).
