### ISSUE TITLE
Assignee and Reporter ID not saving

### ISSUE THREAD

**Issue by lmvdz** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#104]
Whenever I try to save the assignee id or reporter id and save, close and edit the values are gone.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76d2c23e-c66c-3e66-f61d-681c4327e461
* Version Independent ID: 0c4a4d9e-d055-d56e-6b48-c70cb753aa60
* Content: [JIRA - Connectors](https://docs.microsoft.com/en-us/connectors/jira/)
* Content Source: [docs/JIRA/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/JIRA/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by lmvdz** [comment]
I do remember once seeing that there was an extra field added to the JIRA connector, which actually had the assignee and reporter in a json object.

**Comment by DougKlopfenstein** [comment]
@lmvdz Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) or to the connector-specific support contact (if applicable).
