### ISSUE TITLE
Started getting errors when using this connector, but only on certain flows

### ISSUE THREAD

**Issue by hendrimp1** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#105]
'The template language expression 'json(decodeBase64(triggerOutputs().headers['X-MS-APIM-Tokens']))['$connections']['shared_sendgrid']['connectionId']' cannot be evaluated because property 'shared_sendgrid' doesn't exist, available properties are 'shared_sharepointonline, shared_approvals, shared_office365'. Please see https://aka.ms/logicexpressions for usage details.'.

**Comment by DougKlopfenstein** [comment]
@hendrimp1 Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) or to the connector-specific support contact (if applicable).
