### ISSUE TITLE
Missing key actions and triggers

### ISSUE THREAD

**Issue by roscocheeta** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#106]
Triggers such as "When a Task is Updated" and Actions like "List all Tasks in a project", or "Update Task" seem to be key missing options missing.

How do we get this feedback to the right person in MS whom developed this connector? The Product Ideas section will simply have these requests fade into the background as the user base of this particular connector I would argue is quite low. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 721b75a0-c7d7-b9da-9c36-a402e5d1f6a5
* Version Independent ID: 579c5b41-d01b-5616-c812-d6058e274f30
* Content: [Asana - Connectors](https://docs.microsoft.com/en-us/connectors/asana/#feedback)
* Content Source: [docs/Asana/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Asana/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by DougKlopfenstein** [comment]
@roscocheeta Thank you for your feedback. 

This connector was developed by Asana, not Microsoft. You'll have to direct your query to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) or to the connector-specific support contact (if applicable).
