### ISSUE TITLE
Create or Update template deployment - API Version

### ISSUE THREAD

**Issue by DanteNahuel** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#107]
When trying to use Create or Update template deployment using a nested deployment, I get the following error:

 Deployment template validation failed: 'The template resource '[concat(parameters('virtualMachineName'), '-' , 'BackupIntent')]' at line '1' and column '5690' is invalid. The api-version '2016-06-01' used to deploy the template does not support 'ResourceGroup' property. Please use api-version '2017-05-10' or later to deploy the template. Please see https://aka.ms/arm-template/#resources for usage details.'.

This is the nested Deployment:
`{
      "apiVersion": "2019-10-01",
      "condition":"[equals(parameters('sub'),'5175eb3e-e794-4846-8eeb-b155e4caf34f')]",
      "name": "[concat(parameters('virtualMachineName'), '-' , 'BackupIntent')]",
      "type": "Microsoft.Resources/deployments",
      "resourceGroup": "[parameters('backupVaultRGName')]",
      "properties": {
          "mode": "Incremental",
          "template": {
              "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
              "contentVersion": "1.0.0.0",
              "resources": [
                  {
                      "name": "[concat(parameters('backupVaultName'), '/', parameters('backupFabricName'), '/', parameters('backupItemName'))]",
                      "apiVersion": "2017-07-01",
                      "type": "Microsoft.RecoveryServices/vaults/backupFabrics/backupProtectionIntent",
                      "properties": {
                          "friendlyName": "[concat(parameters('virtualMachineName'), 'BackupIntent')]",
                          "protectionIntentItemType": "AzureResourceItem",
                          "policyId": "[resourceId(parameters('backupVaultRGName'), 'Microsoft.RecoveryServices/vaults/backupPolicies', parameters('backupVaultName'), parameters('backupPolicyName'))]",
                          "sourceResourceId": "[resourceId(parameters('virtualMachineRG'), 'Microsoft.Compute/virtualMachines', parameters('virtualMachineName'))]"
                      }
                  }
              ]
          }
      },
      "dependsOn": [
          "[resourceId(parameters('virtualMachineRG'), 'Microsoft.Compute/virtualMachines', parameters('virtualMachineName'))]"
      ]
    }`

I suspect this is because Create or Update template deployment uses a very old API version but I can't find how to specify it in the main template

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d42574e1-1616-a834-454c-0775cfce46fb
* Version Independent ID: 35fd5c8f-fb21-6056-c100-80d418392ddc
* Content: [Azure Resource Manager - Connectors](https://docs.microsoft.com/en-us/connectors/arm/#create-or-update-a-template-deployment)
* Content Source: [docs/ARM/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/ARM/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by DougKlopfenstein** [comment]
@DanteNahuel Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) or to the connector-specific support contact (if applicable).
