### ISSUE TITLE
Service principal configuration using client certificate

### ISSUE THREAD

**Issue by malaker** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#11]
Hi

Currently connector does not support client certificates for authentication SPN . Will it be supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78bf3518-bce4-ecc5-8bf6-1fb627b9105e
* Version Independent ID: d46568f2-e080-cbbe-2f7e-a655bce20b64
* Content: [Common Data Service (current environment) - Connectors](https://docs.microsoft.com/en-us/connectors/commondataserviceforapps/#feedback)
* Content Source: [docs/commondataserviceforapps/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/commondataserviceforapps/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment]
Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback)
