### ISSUE TITLE
Custom Connectors

### ISSUE THREAD

**Issue by vinoz1990** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#110]
Insightly allows connections only with API key , but Flow doesnt support basic authentication , It shows bearer key , Can you let me know how you connected to insightly with this problems
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a6df7b0-04ac-5f64-d641-db13bfd34a00
* Version Independent ID: afccffbb-7b4c-d351-3a0f-ada16c5ce282
* Content: [Instructions on providing feedback for connectors](https://docs.microsoft.com/en-gb/connectors/custom-connectors/provide-feedback)
* Content Source: [docs/custom-connectors/provide-feedback.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/provide-feedback.md)
* Service: **connectors**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by DougKlopfenstein** [comment]
@vinoz1990 Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) or to the connector-specific support contact (if applicable).
