### ISSUE TITLE
FreshDesk connector open source

### ISSUE THREAD

**Issue by bartbilliet** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#111]
Is the FreshDesk connector open source? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcd11e8a-b7be-7f8a-6c11-5c9d05ce170c
* Version Independent ID: a308753c-40a6-c43c-4045-eb8cbe0e6727
* Content: [Freshdesk - Connectors](https://docs.microsoft.com/en-us/connectors/freshdesk/)
* Content Source: [docs/Freshdesk/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Freshdesk/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by DougKlopfenstein** [comment]
@bartbilliet Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) or to the connector-specific support contact (if applicable).
