### ISSUE TITLE
Twilio connector

### ISSUE THREAD

**Issue by LycheeYum** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#116]
I'm looking for information on the Twilio connector.  Specifically, is there a roadmap to update it?

Twilio says it is not something they developed.

Thank you

**Comment by bezhan-msft** [comment]
Thank you for your feedback. Currently there is no roadmap to update it. 

Please direct any feature requests to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) or to the connector-specific support contact (if applicable).
