### ISSUE TITLE
Connection string data persistence at-rest

### ISSUE THREAD

**Issue by jkernMINITAB** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#118]
The documentation states that connection strings belong to the **securestring** data-type; where is this data persisted between executions of the Logic app, and how is it secured when the data is at-rest?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2658ff5e-3ad5-4c91-4442-3ab99b8b5bf0
* Version Independent ID: e1daa665-94cc-bdf8-ce4c-674d4ee564fc
* Content: [Service Bus - Connectors](https://docs.microsoft.com/en-us/connectors/servicebus/)
* Content Source: [docs/ServiceBus/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/ServiceBus/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by DougKlopfenstein** [comment]
@jkernMINITAB Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) or to the connector-specific support contact (if applicable).
