### ISSUE TITLE
Redirect URL

### ISSUE THREAD

**Issue by devkeydet** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#12]
When I was trying to create a customer connector, I received an error about the redirect url.  When I looked at the query string, it was sending https://global.consent.azure-apim.net/redirect.  I added that in the Azure portal and everything worked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e584c228-236a-27fd-52b6-0910a7e67a13
* Version Independent ID: ec7aceaf-0855-b0c0-3468-9030e339a607
* Content: [Authenticate your API and connector with Azure Active Directory - Azure AD](https://docs.microsoft.com/en-us/connectors/custom-connectors/azure-active-directory-authentication#feedback)
* Content Source: [docs/custom-connectors/azure-active-directory-authentication.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/azure-active-directory-authentication.md)
* Service: **connectors**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by dougelliott** [comment]
Hey @devkeydet - thanks for surfacing! Just to make sure I'm following along correctly, is there an underlying issue in the documentation where the redirect URL requirement isn't clear/accurate? I see that it is discussed [here](https://docs.microsoft.com/en-us/connectors/custom-connectors/azure-active-directory-authentication#set-the-reply-url-in-azure), and a different redirect URL is included, but that's there to simply serve as an example.

**Comment by bezhan-msft** [comment]
Hello - this issue has been closed due to lack of information. If you have more information to provide, please reopen this issue.
