### ISSUE TITLE
This is unreadable

### ISSUE THREAD

**Issue by gormster** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#120]
[Enter feedback here]
Alright, so all of these connector policies have pretty terrible documnetation, but I challenge anyone who's no already familiar with this policy to actually parse any of these sentences.

> Name of the property within each object that should contain the array item value.

Within *what* object? These descriptions are all so incredibly vague, even though I can tell whoever wrote them was trying very hard to convey this quite complex action using simple language.

I think it's probably too complicated for such simple language. This needs, at a minimum, an example, if not an actual diagram. It should also avoid using words like "the object" and "the property" because they have multiple meanings and the ambiguity makes it incredibly confusing.

I still don't know what this does, by the way. I'm going to try to figure it out by experimentation, which is also very difficult to do with connectors, but you've left me little choice.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d937cbaf-bb06-f14e-d382-d79c72219fa6
* Version Independent ID: 20e61b2f-df2b-6552-c450-9e21d60b6a85
* Content: [Convert Delimited String Into Array Of Objects(Preview)](https://docs.microsoft.com/en-au/connectors/custom-connectors/policy-templates/stringtoarray/stringtoarray)
* Content Source: [docs/custom-connectors/policy-templates/stringtoarray/stringtoarray.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/policy-templates/stringtoarray/stringtoarray.md)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@gormster - Thanks for your feedback. The topic in question, Convert Delimited String Into Array Of Objects(Preview), has been revised. Closing the issue.
