### ISSUE TITLE
Dead link in connector documentation

### ISSUE THREAD

**Issue by schabungbam** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#121]
From support:

My Cx noticed that there is a link that goes nowhere on the Adobe Sign documentation. Specifically it is the “file” response link under “Returns”. See here:
https://docs.microsoft.com/en-us/connectors/adobesign/#get-form-field-data-of-agreement

Could someone have a look at this please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d758ac3b-a9f4-0500-c5bd-2d030fa28f01
* Version Independent ID: a47a20a0-037e-a589-a6ed-33ae7f16b7b9
* Content: [Adobe Sign - Connectors](https://docs.microsoft.com/en-us/connectors/adobesign/#get-form-field-data-of-agreement)
* Content Source: [docs/adobesign/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/adobesign/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by DougKlopfenstein** [comment]
@schabungbam Thanks for your feedback.

The link you identified seems to be working correctly. If you have more information to provide, please reopen this issue.
