### ISSUE TITLE
BatchResponseAccount return values (AadTenantId and AadUserId) are mising

### ISSUE THREAD

**Issue by zlDev** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#124]
When I run a playbook with **Alert - Get account** and provide input as **Entities** I'm not getting back values outlined in the **BatchResponseAccount**

This is what I'm getting back when I check inputs and outputs in Logic app run
  {
    "$id": "2",
    "Name": "**test_user**",
    "UPNSuffix": "**testDomain**.onmicrosoft.com",
    "IsDomainJoined": true,
    "Type": "account"
  }

Actual values replaced with the **test_user** and **testDomain**

**BatchResponseAccount** is supposed to return **seven** parameters/values, but I'm only getting **five** above. **AadTenantId** and **AadUserId** are missing from the output.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 685e689b-8d6c-d138-955e-9d230889c542
* Version Independent ID: d026d398-9998-fef5-823c-2b3a9a9af251
* Content: [Azure Sentinel - Connectors](https://docs.microsoft.com/en-us/connectors/azuresentinel/#alert---get-accounts)
* Content Source: [docs/azuresentinel/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/azuresentinel/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by DougKlopfenstein** [comment]
@zlDev Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) or to the connector-specific support contact (if applicable).
