### ISSUE TITLE
Trigger when a Pull request is completed. 

### ISSUE THREAD

**Issue by agrabhi** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#125]
Do we have a trigger when a pull request is completed. The trigger for code push to Git looks like its a trigger for any code push and not necessarily for PR completion

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1992475b-648a-9ebc-f165-abef6b5180a4
* Version Independent ID: da0b9096-309c-5d3f-11c2-0dba2c029c39
* Content: [Azure DevOps - Connectors](https://docs.microsoft.com/en-us/connectors/visualstudioteamservices/?source=docs#known-issues-and-limitations)
* Content Source: [docs/VisualStudioTeamServices/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/VisualStudioTeamServices/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by DougKlopfenstein** [comment]
@agrabhi Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) or to the connector-specific support contact (if applicable).
