### ISSUE TITLE
Broken link at top of page

### ISSUE THREAD

**Issue by nonodename** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#127]
Hyperlink under the bullet "Create a custom connector from a Postman collection" goes to "https://docs.microsoft.com/en-us/connectors/custom-connectors/define-blank" should go to "https://docs.microsoft.com/en-us/connectors/custom-connectors/define-postman-collection"
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c443c1c-e4af-1f21-10b3-9c8d81abc1f1
* Version Independent ID: 9aa14809-3da3-23b3-3210-7a2e84608f04
* Content: [Create a custom connector from scratch](https://docs.microsoft.com/en-us/connectors/custom-connectors/define-blank)
* Content Source: [docs/custom-connectors/define-blank.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/define-blank.md)
* Service: **connectors**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by v-aangie** [comment]
@nonodename - Thanks for your feedback. We have updated the docs to fix the link, and the updated content is live. Closing this issue.
