### ISSUE TITLE
Incorrect command line example for updating with settings file

### ISSUE THREAD

**Issue by maventis** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#129]
In the "Update an Existing Custom Connector", the last command-line example should be "update" instead of create. For example

Incorrect: 
`paconn create -s [Path to settings.json] --secret [The OAuth2 client secret for the connector]`

Correct:
`paconn update -s [Path to settings.json] --secret [The OAuth2 client secret for the connector]`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ae4e2ec-bb1d-8e70-bdb4-c2ecb57e6d73
* Version Independent ID: ba1cfb3e-51b1-02ce-7654-969ee500b0f5
* Content: [Microsoft Power Platform Connectors CLI](https://docs.microsoft.com/en-us/connectors/custom-connectors/paconn-cli)
* Content Source: [docs/custom-connectors/paconn-cli.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/paconn-cli.md)
* Service: **connectors**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by v-aangie** [comment]
@maventis - Thanks for your feedback. We have updated the docs to fix information about the update error in https://docs.microsoft.com/en-us/connectors/custom-connectors/paconn-cli, and the updated content is live. Closing this issue.
