### ISSUE TITLE
Content Conversion - Timeout

### ISSUE THREAD

**Issue by Gregghis** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#134]
Hi,

Starting from this morning (19/06/2020 9AM BST) Content Conversion is throwing Timeout error in each power automate flow.
I'm using the HTML to TEXT action.

**Comment by DougKlopfenstein** [comment]
@Gregghis Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) or to the connector-specific support contact (if applicable).
