### ISSUE TITLE
Needs to get User Type as well

### ISSUE THREAD

**Issue by bkwaz4** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#136]
Need to be able to use Get User to return the User Type (Member or Guest) so I don't have to make an http call to the graph api to get it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd854166-65d2-2bc3-5fc6-bb89b93f7b2a
* Version Independent ID: 3be5703b-0f16-18e9-8f15-5b6ca32cb6c1
* Content: [Azure AD - Connectors](https://docs.microsoft.com/en-us/connectors/azuread/#get-user)
* Content Source: [docs/AzureAD/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/AzureAD/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by DougKlopfenstein** [comment]
@bkwaz4 Hello - thank you for your feedback.

The documentation should describe the functionality of the connector, not the end API. If the connector itself does not contain certain actions and triggers that you are requesting, please instead make a [feature request](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback).
