### ISSUE TITLE
Can't deploy Gmail Connector in arm template

### ISSUE THREAD

**Issue by duzvik** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#137]
Did something change from May'20?
`{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"error\": {\r\n \"code\": \"**GmailConnectorPolicyViolation**\",\r\n \"message\": \"The workflow 'XXXX' cannot be saved because it contains connections to 'gmail' connector which are not valid. Please create new API connection and try again.\"\r\n }\r\n}"}]}`

**Comment by DougKlopfenstein** [comment]
@duzvik  Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) or to the connector-specific support contact (if applicable).
