### ISSUE TITLE
How to register an Azure Devops connection with another account that the current one ?

### ISSUE THREAD

**Issue by ToineSeiter** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#140]
In Logic App designer in Azure, SSO is performed each time I want to create a new API connection to Azure DevOps. 
It would be nice to add somewhere a "Sign in with another account" button.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1992475b-648a-9ebc-f165-abef6b5180a4
* Version Independent ID: da0b9096-309c-5d3f-11c2-0dba2c029c39
* Content: [Azure DevOps - Connectors](https://docs.microsoft.com/en-us/connectors/visualstudioteamservices/)
* Content Source: [docs/VisualStudioTeamServices/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/VisualStudioTeamServices/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by DougKlopfenstein** [comment]
@ToineSeiter Hello - thank you for your feedback.

The documentation should describe the functionality of the connector, not the end API. If the connector itself does not contain certain actions and triggers that you are requesting, please instead make a [feature request](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback).
