### ISSUE TITLE
Handling lookups of large Azure Storage Tables

### ISSUE THREAD

**Issue by JS-Jake** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#142]
When using the Azure Storage Tables connector to get azure storage entities, the response does not return all rows and returns a nextLink object.    
How can I use this object to retrieve the rest of the entities in my table?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe88d2b3-07cd-2c33-c835-4aec5f4b3473
* Version Independent ID: 2958cf7f-3c44-4f6f-0656-4aab4c8a8203
* Content: [Azure Table Storage - Connectors](https://docs.microsoft.com/en-us/connectors/azuretables/#get-entities)
* Content Source: [docs/azuretables/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/azuretables/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by DougKlopfenstein** [comment]
@JS-Jake Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) or to the connector-specific support contact (if applicable).
