### ISSUE TITLE
Expected GCC timeframe work JotForm?

### ISSUE THREAD

**Issue by danlopez** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#144]
Hi, is there a timeframe for GCC support for the Jotform connector? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7daa91e-cf89-2897-1b14-97555471a168
* Version Independent ID: af20c599-ed98-a872-f020-6b8c3c85780f
* Content: [JotForm - Connectors](https://docs.microsoft.com/en-us/connectors/jotform/)
* Content Source: [docs/JotForm/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/JotForm/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by DougKlopfenstein** [comment]
@danlopez Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) or to the connector-specific support contact (if applicable).
