### ISSUE TITLE
LogicApp - Calling ACI container

### ISSUE THREAD

**Issue by sharma-dilip** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#148]
Hi,

I am working on a scenario where i am trying to access the existing container(ACI) from logicApp. I hope we could access 'FQDN' of the container group and access it and get the desired response.

I set the FQDN as a variables in my logic app but am not able to invoke the same. Can somebody please suggest how to proceed further and invoke the application image.

**Comment by DougKlopfenstein** [comment]
@sharma-dilip Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) or to the connector-specific support contact (if applicable).
