### ISSUE TITLE
HTTP connector not documented in list

### ISSUE THREAD

**Issue by mirlenbrink** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#149]
The HTTP connector is not listed in the full list of all connectors.  'HTTP with Azure AD' is documented/listed but not the regular HTTP connector.

**Comment by DougKlopfenstein** [comment]
@mirlenbrink Thanks for your feedback.

Closing because this is a duplicate of [#101](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors-public/issues/101).
