### ISSUE TITLE
Intagram's get my recent media is returning "This endpoint has been retired".

### ISSUE THREAD

**Issue by rathanveerddy** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#150]
Intagram's get my recent media is returning the following response:
{
  "meta": {
    "code": 400,
    "error_type": "APINotAllowedError",
    "error_message": "This endpoint has been retired"
  }
}
This error started appearing since 6/29/2020 10: 30 AM (MST)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52b605b1-b441-873f-6bab-e9f6feea25da
* Version Independent ID: 70a8f3dd-f4a1-ab49-4385-f9623e61f027
* Content: [Instagram - Connectors](https://docs.microsoft.com/en-us/connectors/instagram/)
* Content Source: [docs/Instagram/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Instagram/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by DougKlopfenstein** [comment]
@rathanveerddy Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) or to the connector-specific support contact (if applicable).
