### ISSUE TITLE
redmine

### ISSUE THREAD

**Issue by toreno77** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#152]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c5f7220-7fa2-24db-25e3-40dbce235018
* Version Independent ID: 42347246-acc2-c6d0-01f4-11074469aafb
* Content: [Easy Redmine - Connectors](https://docs.microsoft.com/en-us/connectors/easyredmine/#create-a-project)
* Content Source: [docs/EasyRedmine/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/EasyRedmine/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by DougKlopfenstein** [comment]
@toreno77 Hello - this issue has been closed due to lack of information. If you have more information to provide, please reopen this issue.
