### ISSUE TITLE
Missing comma in JSON examples

### ISSUE THREAD

**Issue by Blackbaud-BenLambert** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#156]
On this page, the following sections have JSON examples are malformed (missing a comma):
https://docs.microsoft.com/en-us/connectors/custom-connectors/operational-versioning#operation-initiation
https://docs.microsoft.com/en-us/connectors/custom-connectors/operational-versioning#operation-deprecation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 035b5615-823c-3088-263d-50dd542f095c
* Version Independent ID: 26a142e7-c655-2266-dc2a-7ef081eea5a9
* Content: [Evolving your API with version control](https://docs.microsoft.com/en-us/connectors/custom-connectors/operational-versioning#api-annotation)
* Content Source: [docs/custom-connectors/operational-versioning.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/operational-versioning.md)
* Service: **connectors**
* GitHub Login: @CamyDee
* Microsoft Alias: **camerost**

**Comment by v-aangie** [comment]
@Blackbaud-BenLambert - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
