### ISSUE TITLE
Why are filesize limits not mentioned

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#16]
for creating new file or new item in sharepoint we are seeing 94 MB limit.. if we exceed 100MB we are seeing a error related to chunking not available, if we do anything greater than 94 MB, then the connector is throwing error saying cannot exceed 94MB, this is only accepting file upto 90MB... why are these limits not mentioned in the documentation(am i missing something?), is the documentation no longer proactive, has it become reactive to the comments customers like me are giving?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69a01872-3062-4100-f807-7d43e8111e9f
* Version Independent ID: 48560378-76ed-cb42-e816-894179e1f16d
* Content: [SharePoint - Connectors](https://docs.microsoft.com/en-us/connectors/sharepointonline/#create-item)
* Content Source: [docs/sharepointonline/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/sharepointonline/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment]
I am told that chunking support is now available (except for on-prem). Closing issue.
