### ISSUE TITLE
Webex Teams: use a bot token instead of oAuth?

### ISSUE THREAD

**Issue by DJF3** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#160]
**Integration**: Webex Teams integration.
**Request**: the ability to use a **_BOT TOKEN_** instead of a _user granting rights via oAuth_. There's many scenarios where you only need to send messages and a bot works great for that. Plus, many organisations block unapproved (oAuth) integrations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44dbfcfd-646c-e800-d60e-73dfcd0a4a71
* Version Independent ID: bc171b69-7a2b-5af8-6fa3-cca17e225215
* Content: [Webex Teams - Connectors](https://docs.microsoft.com/en-us/connectors/webex/)
* Content Source: [docs/webex/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/webex/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by DougKlopfenstein** [comment]
@DJF3 Hello - thank you for your feedback.

The documentation should describe the functionality of the connector, not the end API. If the connector itself does not contain certain actions and triggers that you are requesting, please instead make a [feature request](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback).
