### ISSUE TITLE
Does DB2 Connector GetRows $filter support DATE type columns?

### ISSUE THREAD

**Issue by ericthomas1** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#166]
I can't seem to get the following query to work using the DB2 connector: 

**Scenario**: 
1. Database: DB2
2. Connector DB2
3. Action `Get Rows`
4. Column name `TEST_COLUMN`
5. Column data type `DATE` (verified in the DB2 table itself)

**Issue**:
1. In the `Filter` area of the connector, I type:
`TEST_COLUMN gt '2020-06-01`

**Results in an error**:

```
We cannot apply operator < to types Text and Date.
     inner exception: We cannot apply operator < to types Text and Date.
clientRequestId: 51595fbd-354f-4c2c-a1bd-dba04f264b6b
```

**Also tried**:
`TEST_COLUMN lt '2020-06-01`
- Also fails

`TEST_COLUMN lt formatDateTime('2020-06-01', 'yyyy-MM-dd')
- Also fails

`TEST_COLUMN eq '2020-06-01`
- Strangely enough, THIS SUCCEEDS, but ALWAYS returns a blank record even though i've verified there are records in the DB with 2020-06-01 in the database!

Please advise. This is blocking me at the moment. 

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be2e8667-7502-4b40-afe7-3de992679318
* Version Independent ID: 873d28d2-0fe3-d348-d3bb-532f7ff4c8c0
* Content: [DB2 - Connectors](https://docs.microsoft.com/en-us/connectors/db2/)
* Content Source: [docs/DB2/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/DB2/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by ericthomas1** [comment]
Anyone?

**Comment by DougKlopfenstein** [comment]
@ericthomas1 Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) or to the connector-specific support contact (if applicable).
