### ISSUE TITLE
Comms should be aligned with insensitive language

### ISSUE THREAD

**Issue by GossiTheDog** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#167]
Hey - Microsoft has guidelines on race-insensitive language, we should update blacklist to deny list, and whitelist to allow list.

Many thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65b8b971-9ad3-d2b9-e774-43a6571f02d2
* Version Independent ID: ca25c323-31df-a9ee-6582-f018342d7bee
* Content: [SerwerSMS - Connectors](https://docs.microsoft.com/en-us/connectors/serwersms/)
* Content Source: [docs/serwersms/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/serwersms/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@GossiTheDog - Thanks for your feedback. We are changing blacklist to blocklist, and whitelist to allowlist. Closing the issue.
