### ISSUE TITLE
What is a filelocator

### ISSUE THREAD

**Issue by torakoneko** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#17]
Don't define a word by just using the word again! If I'm looking up what a filelocator is, telling me it's a filelocator is literally the least helpful thing you could do.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69a01872-3062-4100-f807-7d43e8111e9f
* Version Independent ID: 48560378-76ed-cb42-e816-894179e1f16d
* Content: [SharePoint - Connectors](https://docs.microsoft.com/en-us/connectors/sharepointonline/#feedback)
* Content Source: [docs/sharepointonline/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/sharepointonline/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment]
Thank you for your feedback. 

I believe "Filelocator" is a defined external term and out of scope for this documentation. For example, "etag" ...etc is also not defined. The connector description while I agree does not provide information on what Filelocator is, does not have the responsibility of defining terms unless they are specific to the connector.
