### ISSUE TITLE
Power Platform for Admins - Create Environment DLP Policy (Block connectors)

### ISSUE THREAD

**Issue by fs366e2spm** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#173]
Hi,

Creating a new Environment DLP Policy doesn't support choosing "Blocked" as default group, only "hbi" and "lbi".

Additionally when Block Action Type is set to "Blocked" it results in the following error message independent where these connectors are defined (hbi, lbi):
You cannot block the following trusted connectors: 'Cloud App Security, Common Data Service, Common Data Service (current environment), Microsoft Kaizala, Microsoft Forms Pro, Office 365 Groups, Office 365 Groups Mail, Power Apps Notification, Shifts for Microsoft Teams, Skype for Business Online'.

Issue? Not yet fully implemented in the preview? User handling error?

Thanks for any help or suggestions.

**Comment by DougKlopfenstein** [comment]
@fs366e2spm Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) or to the connector-specific support contact (if applicable).
