### ISSUE TITLE
Minor - SharePoint logo dimensions are not correct

### ISSUE THREAD

**Issue by MKuhlani** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#178]
At the top of the page - SharePoint logo does not have the right dimensions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69a01872-3062-4100-f807-7d43e8111e9f
* Version Independent ID: 48560378-76ed-cb42-e816-894179e1f16d
* Content: [SharePoint - Connectors](https://docs.microsoft.com/en-us/connectors/sharepointonline/#feedback)
* Content Source: [docs/sharepointonline/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/sharepointonline/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by natalie-pienkowska** [comment]
Hi @MKuhlani thanks for raising this. It looks like we've updated it to the correct logo since your comment.
