### ISSUE TITLE
Creating a connection

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#180]
Hello,

About "Creating a connection", for section "examples: \MACHINE\myShare"
Does this connector really supports a network share?
Tried to implement it, but it fail... Working with MS support

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e32f470-9966-6207-ed34-db39f7e79395
* Version Independent ID: a0654443-876d-3d36-afb7-189a559d4e9f
* Content: [File System - Connectors](https://docs.microsoft.com/en-us/connectors/filesystem/)
* Content Source: [docs/filesystem/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/filesystem/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by natalie-pienkowska** [comment]
Hi @lightupdifire since you were working with MS support on this, I'll close this issue. If you still have this issue, please reach out to us here: https://powerusers.microsoft.com/t5/Connecting-To-Data/bd-p/ConnectingToData
