### ISSUE TITLE
Custom Headers are stripped off when using 'When a new mail arrives" connector

### ISSUE THREAD

**Issue by ifflanb** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#182]
Hi, I am using custom headers via the office js library here https://docs.microsoft.com/en-us/javascript/api/outlook/office.internetheaders?view=outlook-js-preview to pass meta data in the email headers.
I can see that the header is added but when it is received via the logic app, the custom headers have been removed.
Is this a known issue? Is there a way to prevent the stripping of custom headers?

thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc40a098-af8c-d8a9-4538-71d184efbe91
* Version Independent ID: 0ee8cf79-18e9-d923-607f-ef40cdd23e4d
* Content: [Office 365 Outlook - Connectors](https://docs.microsoft.com/en-us/connectors/office365/)
* Content Source: [docs/office365/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/office365/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@ifflanb - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue,  go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
