### ISSUE TITLE
How to trigger a cloud function after user is added to a certain group?

### ISSUE THREAD

**Issue by Manubi** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#183]
Hi,
I can't find an event listener function who can trigger after a user is added to azure active directory? Use case is, I want to update the database of my webapp as I use azure for authentication. 

Thanks!

**Comment by v-aangie** [comment]
@Manubi - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue,  go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
