### ISSUE TITLE
App Centre -> Power App Integration

### ISSUE THREAD

**Issue by trevalex-smax** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#186]
I would like to use the App Centre Open API with Power Apps to create a simple sign up app, and remove from list feature.
Was trying to connect the API to a Power App using a customer Connector with the Open API Swagger file.
https://docs.microsoft.com/en-gb/connectors/custom-connectors/define-openapi-definition
Seems like this should be possible but the Swagger file is >1MB which is a limitation of Power App Custom Connector.

Any reason for this.. any suggestions on best way to work round?

**Comment by v-aangie** [comment]
@trevalex-smax - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue,  go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
