### ISSUE TITLE
Incorrect description of Create Job action

### ISSUE THREAD

**Issue by simonbrady** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#187]
The Create Job action is described as creating an Automation job on a hybrid runbook worker, but this is misleading: it can also create a job to run on an Azure sandbox.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: daeb05b6-45da-9fb9-936b-35212c587ef5
* Version Independent ID: 39ffc4aa-d490-6346-33b9-df690d781c1a
* Content: [Azure Automation - Connectors](https://docs.microsoft.com/en-us/connectors/azureautomation/#create-job)
* Content Source: [docs/AzureAutomation/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/AzureAutomation/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@simonbrady - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
