### ISSUE TITLE
https://docs.microsoft.com/en-us/connectors/arm/#list-resources-by-subscription - Filter?

### ISSUE THREAD

**Issue by Madrawn** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#188]
Hi, several methods have a "filter" parameter, but nowhere is this parameter described.

I suspected that it's a OData-filter but that doesn't seem to work:
![image](https://user-images.githubusercontent.com/1095756/92553911-73b34000-f264-11ea-9dac-6556d7e22d00.png)
I tried a lot of variants: "type eq "stuff"", "Type eq "stuff"", "type eq 'stuff'", "type -eq 'stuff'", "value/type eq 'stuff'"  etc

So I would be grateful for some example how to filter on an attribute.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d42574e1-1616-a834-454c-0775cfce46fb
* Version Independent ID: 35fd5c8f-fb21-6056-c100-80d418392ddc
* Content: [Azure Resource Manager - Connectors](https://docs.microsoft.com/en-us/connectors/arm/#list-resources-by-subscription)
* Content Source: [docs/ARM/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/ARM/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@Madrawn - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue,  go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
