### ISSUE TITLE
When a library file name is changed, the trigger "When an item is created or modified" does not fire

### ISSUE THREAD

**Issue by oliviadudley** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#19]
When a file name in a library is changed, the trigger "When an item is created or modified" does not fire. It does fire when other columns are updated, but not when the file name is changed. If approval is required for the item after the file name is changed, the modified date field updates, but the modified (user) field does not.

https://docs.microsoft.com/en-us/connectors/sharepointonline/#when-an-item-is-created-or-modified

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69a01872-3062-4100-f807-7d43e8111e9f
* Version Independent ID: 48560378-76ed-cb42-e816-894179e1f16d
* Content: [SharePoint - Connectors](https://docs.microsoft.com/en-us/connectors/sharepointonline/#when-an-item-is-created-or-modified)
* Content Source: [docs/sharepointonline/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/sharepointonline/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment]
Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback)

**Comment by jyrate** [comment]
I believe the issue is that this trigger does not work unless the authenticated user is a site collection admin - and this should be clearly documented!
