### ISSUE TITLE
Need examples for dynamicFileSchema 

### ISSUE THREAD

**Issue by EnterTheQuirk** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#193]
Please include some (even basic) examples of how to use the dynamicFileSchema attribute. 

We're building a doc gen function for a client and wanted to use PowerAutomate Flows. However, as this is an enterprise client, we need migrate between environments properly, which ultimately means we need to dynamically set the Sharepoint Library, file etc. per environment. 

We can handle that OK at the moment (environment variables will make it so much better though), but the problem is if we dynamically reference our template, Flow does not give us the fields/attributes to populate through the Flow UI. Completely understandable since we won't know what that template is until runtime. 

However, we ARE given a "dynamicFileSchema" field, and if we had previously had fields presented due to statically referencing the file, they remain and are given a "dynamicFileSchema/12345" reference. This looks suspiciously like the thing we need, but there is no documentation on how to use it. It sounds like it should be a JSON structure but we cannot determine the schema to follow (we tried a few but we were guessing).

If the dynamicFileSchema attribute can be used to define the template attributes we can populate while leaving the template selection to runtime, please provide examples. Some basic examples of any key features would be very useful. eg. provide an example schema which defines plain text fields in the template; and/or repeatable elements; and/or images (base64 encoding?) etc.

(If this is not what dynamicFileSchema is used for, please clarify in the documentation)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d39ce977-b1fc-d4be-3776-ad31a5b780ec
* Version Independent ID: 21c81572-7742-f033-cdc1-07c1090e9878
* Content: [Word Online (Business) - Connectors](https://docs.microsoft.com/en-us/connectors/wordonlinebusiness/)
* Content Source: [docs/wordonlinebusiness/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/wordonlinebusiness/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@EnterTheQuirk - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
