### ISSUE TITLE
Please provide more details about the existing limits of this connector

### ISSUE THREAD

**Issue by dgrospelier** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#194]
[Tapez vos commentaires ici]
When I try to use this connector to insert or update a record into a DB2 table, I found that this is not supported if the DB2 table does not have a primary key. Unfortunately, this is something that is not provided in the documentation.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: be2e8667-7502-4b40-afe7-3de992679318
* Version Independent ID: 873d28d2-0fe3-d348-d3bb-532f7ff4c8c0
* Content: [DB2 - Connectors](https://docs.microsoft.com/fr-fr/connectors/db2/)
* Content Source: [docs/DB2/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/DB2/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@dgrospelier - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
