### ISSUE TITLE
Is Jira server/Data Center supported?

### ISSUE THREAD

**Issue by jackchenwork** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#195]
[Enter feedback here]

Could you please clarify if Jira Server/Data Center is supported ?

Based on "JIRA Server behind a firewall or with REST API disabled is not supported." , it seems Jira Server who allow REST API is supported.

But based on "For authentication, you need to use an API token. To get a token, go to this link.", it seems the connector only support Jira Cloud, since Jira server/Data Center doesn't provide user API token.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76d2c23e-c66c-3e66-f61d-681c4327e461
* Version Independent ID: 0c4a4d9e-d055-d56e-6b48-c70cb753aa60
* Content: [JIRA - Connectors](https://docs.microsoft.com/en-us/connectors/jira/)
* Content Source: [docs/JIRA/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/JIRA/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@jackchenwork - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
