### ISSUE TITLE
SharePoint "When an item is deleted" trigger 

### ISSUE THREAD

**Issue by jyrate** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#196]
After a lot of googling, it seems that the SharePoint "When an item is deleted" trigger ONLY works when connecting using a user account with site collection admin privileges. If this is the case it should be CLEARLY documented as a prerequisite.

Other commentary suggests "MS discovered some security vulnerabilities around that trigger, so earlier this year [2019]  the removed most of the metadata from that trigger.  They said they were going to put the metadata back, but would restrict its use in the future to only users with site collection admin permissions."... Again, if this is the case, the documentation should be updated to reflect this.

**Comment by natalie-pienkowska** [comment]
Thanks @jyrate for raising this issue. We have updated the documentation to reflect this: https://docs.microsoft.com/en-us/connectors/sharepointonline/#triggers
