### ISSUE TITLE
Value to add documentation limited

### ISSUE THREAD

**Issue by philhagger** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#197]
I am unable to work out what to put in Value to add to target the path to the property. 

It seems that no matter what I do a constant is always provided.

I am trying to update a value with a different value on the object that is nested

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95493cfc-bc47-9ee3-5015-da6af9edc5b5
* Version Independent ID: c4a2d116-5383-affb-1cbc-2461721ac729
* Content: [Set Property(Preview)](https://docs.microsoft.com/en-us/connectors/custom-connectors/policy-templates/setproperty/setproperty?source=docs)
* Content Source: [docs/custom-connectors/policy-templates/setproperty/setproperty.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/policy-templates/setproperty/setproperty.md)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@philhagger - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
