### ISSUE TITLE
Need documentation of the "ObjectWithoutType" object

### ISSUE THREAD

**Issue by fmigacz** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#198]
The action, [Send an HTTP Request to Azure DevOps](https://docs.microsoft.com/en-us/connectors/visualstudioteamservices/#send-an-http-request-to-azure-devops), returns an [ObjectWithoutType](https://docs.microsoft.com/en-us/connectors/visualstudioteamservices/#objectwithouttype), but there is no information of what that is, its use, or its expected values.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1992475b-648a-9ebc-f165-abef6b5180a4
* Version Independent ID: da0b9096-309c-5d3f-11c2-0dba2c029c39
* Content: [Azure DevOps - Connectors](https://docs.microsoft.com/en-us/connectors/visualstudioteamservices/)
* Content Source: [docs/VisualStudioTeamServices/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/VisualStudioTeamServices/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@fmigacz - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.

**Comment by masaru-iritani** [comment]
@v-aangie This is an issue on a Microsoft Docs page for a connector, not a connector itself. Which is the best community to report the issue?
