### ISSUE TITLE
'Get file/folder/item metadata using path', but URI? | SharePoint Online / OneDrive for Business

### ISSUE THREAD

**Issue by haneef95** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#199]
Hi,

The existing action is fairly useful, however, what's much needed is the ability to convert URIs/URLs to JSON metadata objects.

# Use case 1
Ask users to enter the URL of a file/folder and carry out an action on that file/folder.

# Use case 2
The result from '[for a selected file](https://docs.microsoft.com/en-gb/connectors/onedriveforbusiness/#for-a-selected-file)' returns the the relative path within the site and the full URL. However, the actions require the Site Address, Library and File Path as separate inputs, examples:
[Move folder](https://docs.microsoft.com/en-gb/connectors/sharepointonline/#move-folder)
[Get file content](https://docs.microsoft.com/en-gb/connectors/sharepointonline/#get-file-content)

Is there anyway to achieve this? Has this been documented somewhere?

Thanks,

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69a01872-3062-4100-f807-7d43e8111e9f
* Version Independent ID: 48560378-76ed-cb42-e816-894179e1f16d
* Content: [SharePoint - Connectors](https://docs.microsoft.com/en-gb/connectors/sharepointonline/#get-folder-metadata-using-path)
* Content Source: [docs/sharepointonline/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/sharepointonline/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@haneef95 - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
