### ISSUE TITLE
Missing Actions

### ISSUE THREAD

**Issue by HrlecMatej** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#2]
There's a big issue with some Actions missing, namely ListTaskLists, without which one cannot get their taskListId. And those are needed to get individual Tasks Lists. This page seems to document a lot more Actions, but many of them are not available in the Logic Apps Designer on Azure: https://www.carlosag.net/PowerApps/Connectors/Teamwork-Projects

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa2f08e-238c-92d5-5c2e-bd3d4c1659f9
* Version Independent ID: bc62fa9a-10c5-c290-d318-781110cd40cf
* Content: [Teamwork Projects - Connectors](https://docs.microsoft.com/en-us/connectors/teamwork/#feedback)
* Content Source: [docs/Teamwork/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Teamwork/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment]
Hello - thank you for your feedback.

I have taken a look at the connector in Power Automate; it seems the Teamwork Projects connector doesn't have the "ListTaskLists" action. Is there somewhere you are seeing this action available in the connector?

Our documentation should describe the functionality of the connector, not the end API. If the connector itself does not contain certain actions and triggers that you are requesting, please instead make a [feature request](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback).

**Comment by bezhan-msft** [comment]
Hello - this issue has been closed due to lack of information. If you have more information to provide, please reopen this issue.
