### ISSUE TITLE
"Start the custom connector wizard" section is invalid

### ISSUE THREAD

**Issue by christinaeir** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#20]
"In the upper right corner, choose the gear icon, then choose Custom connectors."
There is no Custom connectors in the panel that opens after clicking the gear icon. Please update the documentation with correct navigation on how to create a custom connector.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c443c1c-e4af-1f21-10b3-9c8d81abc1f1
* Version Independent ID: 9aa14809-3da3-23b3-3210-7a2e84608f04
* Content: [Create a custom connector from scratch](https://docs.microsoft.com/en-us/connectors/custom-connectors/define-blank)
* Content Source: [docs/custom-connectors/define-blank.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/define-blank.md)
* Service: **connectors**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by bezhan-msft** [comment]
Hi @DougKlopfenstein , could you please take a look at this?

**Comment by bezhan-msft** [comment]
This fix is now live. Thank you for reporting the issue.
