### ISSUE TITLE
Requesting Logic App Word Online Connector Upgrade 

### ISSUE THREAD

**Issue by ajay2java2dev** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#200]
[There are lot of frameworks like iText, Apache POI, FOP etc to get documents generated and integrated with a coding platform but users of logic app if can a get similiar features in connectors that would be just awesome. Our team needs  solutions which are easy to develop and faster to ship to market. The project really doesn't care which platform we are on, as long as the Cost is kept lower and things are delivered ASAP. 

I poked around Word Online and even though I see documentation here and there to create dynamic forms, I dont find enough details on one place. Word Online Connector for example would help to covert my doc template and also replace the template elements in logic app but I dont find easy solution to create Dynamically generated form elements. Can someone share links how to do that. For example: Form may contain a table and number of rows in that table needs to be increased as per the list size]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d39ce977-b1fc-d4be-3776-ad31a5b780ec
* Version Independent ID: 21c81572-7742-f033-cdc1-07c1090e9878
* Content: [Word Online (Business) - Connectors](https://docs.microsoft.com/en-us/connectors/wordonlinebusiness/#convert-word-document-to-pdf)
* Content Source: [docs/wordonlinebusiness/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/wordonlinebusiness/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@ajay2java2dev - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
