### ISSUE TITLE
Export Connector Catalog to Table (feature request, not an issue)

### ISSUE THREAD

**Issue by melodietang** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#203]
Would be helpful if I could export the connector catalog and it's filters to spreadsheet format for some data analysis

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7741d635-bb14-0cbb-6ddc-d53108b59423
* Version Independent ID: c52d6e84-dc16-af82-9e1f-923659e25c54
* Content: [Connector reference overview](https://docs.microsoft.com/en-us/connectors/connector-reference/)
* Content Source: [docs/connector-reference/index.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/connector-reference/index.md)
* Service: **connectors**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by rootsmusic** [comment]
#337

**Comment by v-aangie** [comment]
@melodietang - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
