### ISSUE TITLE
List Count not working

### ISSUE THREAD

**Issue by kcnighsurf** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#205]
"Message List Message Count" 0 even though json has all the messages ( over 1000 ).
Outputs('List_Messages')?[body/total]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bce87de8-1bf9-ecb8-1d6e-aa337db9cbdb
* Version Independent ID: 99a52156-b21a-0d5b-0f38-aa14e2ede2fa
* Content: [Twilio - Connectors](https://docs.microsoft.com/en-us/connectors/twilio/#messagelist)
* Content Source: [docs/Twilio/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Twilio/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@kcnighsurf - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
