### ISSUE TITLE
Form Recognizer connector using wrong api

### ISSUE THREAD

**Issue by rens8** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#207]
When using the [Analyze Form](https://docs.microsoft.com/en-us/connectors/formrecognizer/) action from the Form Recognizer  connector in Power Automate/Logic Apps, following error is returned:
```
{
  "error": {
    "code": "Gone",
    "message": "Cognitive Services Form Recognizer 'v1.0-preview' APIs have been deprecated. Please upgrade to v2.0."
  }
}

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e84d6396-2e1e-2c2b-3c15-28c34c3d0557
* Version Independent ID: 4b1b05aa-bcab-57f6-9f6d-6ed2014d6d75
* Content: [Form Recognizer - Connectors](https://docs.microsoft.com/en-us/connectors/formrecognizer/)
* Content Source: [docs/formrecognizer/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/formrecognizer/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@rens8 - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
