### ISSUE TITLE
Invalid characters for "Specify a tag for the webhook" parameter

### ISSUE THREAD

**Issue by mynhardtburger** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#208]
The "Specify a tag for the webhook" parameter cannot contain "(" or ")" characters. If it does contain those characters the connection fails with a HTTP 404 error.

I suggest the list of invalid characters is listed in the doc or the connector is updated to work with those characters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4015d5e7-e436-9b33-287c-68381ed572e3
* Version Independent ID: e5ae13a9-af55-0d74-b68f-e56d550380fc
* Content: [Typeform - Connectors](https://docs.microsoft.com/en-us/connectors/typeform/)
* Content Source: [docs/Typeform/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Typeform/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@mynhardtburger - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
