### ISSUE TITLE
No promised list of connectors

### ISSUE THREAD

**Issue by mauledbyjesus** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#21]
https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/connections-list#all-standard-connectors

...directs me to this page for a "list of all standard connectors".  Not being able to find a list of things you're charging me for is frustrating to say the least.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e8db6aa-e833-aacd-033f-49b9c91e45f3
* Version Independent ID: 75b2bdc4-5af2-f8e9-659e-33d0437cc4e0
* Content: [Connectors Overview](https://docs.microsoft.com/en-us/connectors/#feedback)
* Content Source: [docs/index.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/index.md)
* Service: **connectors**
* GitHub Login: @asavaritayal
* Microsoft Alias: **kvivek**

**Comment by bezhan-msft** [comment]
Thank you for your feedback.

A list of standard connectors is a feature set to be released in the next month. There is an error in the documentation you linked suggesting such a list exists today, and I have notified the feature team of that error.

In the meantime, the best place to view if connectors are standard or premium would be in the product experience itself as it allows you to scroll down a connectors list and view which connectors are tagged as Premium. Unfortunately we do not yet have a filtered list view, though it is on our roadmap for the next month or so.

**Comment by bezhan-msft** [comment]
Hello - I would like to add an update that we have now released the List of all Standard connectors:

https://docs.microsoft.com/en-us/connectors/connector-reference/
