### ISSUE TITLE
OpenApi version locked to 2.0

### ISSUE THREAD

**Issue by NickyTope** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#210]
I have just spent hours converting my api definition submitting from raml to openapi 3.0.3 only to find that you only support swagger: 2.0. please at least update the documentation to reflect the missing functionality.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9659a345-1116-5020-4300-386f3a591c2e
* Version Independent ID: e2a3861f-d3d5-f542-28db-1897d4c7feb0
* Content: [Create a custom connector from an OpenAPI definition](https://docs.microsoft.com/en-us/connectors/custom-connectors/define-openapi-definition)
* Content Source: [docs/custom-connectors/define-openapi-definition.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/define-openapi-definition.md)
* Service: **connectors**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by natalie-pienkowska** [comment]
Thank you for this feedback, @NickyTope. We've updated this documentation page to call out that we currently only support 2.0.
