### ISSUE TITLE
PostNotificationRequest not specified

### ISSUE THREAD

**Issue by mdddev** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#211]
I'm trying to submit the action "post as flow bot to user", however I'm returned 400 bad request errors.
What is the schema of this? I used the Flow UI as a guidance (see below), but this didn't work

            var msg = new {
                Recipient = "my@mail.com",
                Message = "test-message",
                Headline = "test-headline",
                Summary = "test-summary",
                IsAlert = false
            };

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb4ba692-98a2-2ec7-319b-d75b59d3fa50
* Version Independent ID: c24a9495-e4cb-28db-3657-ecf81005757b
* Content: [Microsoft Teams - Connectors](https://docs.microsoft.com/en-us/connectors/teams/)
* Content Source: [docs/Teams/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Teams/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@mdddev - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
