### ISSUE TITLE
Documentation unclear on how to add steps to outlook tasks from power automate

### ISSUE THREAD

**Issue by Tasty213** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#213]
In the documentation for the outlook tasks it is unclear how to add steps from power automate. For instance each week i want a task to be made that has two steps in it as per https://support.microsoft.com/en-us/office/add-steps-importance-notes-tags-and-categories-to-your-tasks-bf9fdff6-f85f-4e03-9534-c587eb32515c .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 732687c8-bfeb-3e52-d81f-e7363b431b39
* Version Independent ID: 7aedd7c5-8820-9dbb-6235-9b08b3d75eaf
* Content: [Outlook Tasks - Connectors](https://docs.microsoft.com/en-us/connectors/outlooktasks/#taskhtml)
* Content Source: [docs/OutlookTasks/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/OutlookTasks/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@Tasty213 - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
