### ISSUE TITLE
SAP ERP page could be improved with some more explicit guidance on using the Diagnostics component

### ISSUE THREAD

**Issue by atho3009** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#218]
[Enter feedback here]

Could be improved with some more explicit guidance on using the Diagnostics component.

For instance, we are getting a GatewayNoSupportDiagnostics message, even though the version of the gateway is Jun 2020.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e40f7068-0e24-651d-ade2-3686114b9815
* Version Independent ID: 3bebcd2b-1d3e-f6c7-13b2-cb67cda843dc
* Content: [SAP ERP - Connectors](https://docs.microsoft.com/en-us/connectors/saperp/)
* Content Source: [docs/saperp/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/saperp/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@atho3009 - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
