### ISSUE TITLE
"Export To File for Power BI Reports" bookmarks and page selection does not seem to work properly

### ISSUE THREAD

**Issue by AlexanderDeCraemer** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#219]
I have been trying to use the "Export To File for Power BI Reports" API.
However, everything related to bookmarks and page selection does not seem to work. I have tried many times and many different combinations. Every time the API returns all pages with the default bookmark...
 - I tried the label of the page and it's technical name
 - I tried the default bookmark and page bookmark
- I tried name and status (which should be better documented as the difference is not clear)
- I tried the GUID and label

**Comment by rootsmusic** [comment]
@AlexanderDeCraemer Please re-submit this issue by clicking on the feedback link at the bottom of https://docs.microsoft.com/en-us/connectors/powerbi/#export-to-file-for-power-bi-reports if that's the connector that you're referring to.

**Comment by v-aangie** [comment]
@AlexanderDeCraemer - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
