### ISSUE TITLE
Throttling criteria are unclear

### ISSUE THREAD

**Issue by TWolverson** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#220]
The section "Throttling Limits" mentions a figure of 100, but doesn't specify units. Per second? Something else? It is also not clear what "renewal period" means. Does this mean 100 calls/second evaluated every ten seconds, or 100 calls per ten seconds?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58c0b60a-fdc5-6ce7-e73f-c5071c0f9356
* Version Independent ID: 5865c7d1-abc2-4a70-56dd-4ebef0b411c4
* Content: [SQL Server - Connectors](https://docs.microsoft.com/en-us/connectors/sql/)
* Content Source: [docs/Sql/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Sql/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@TWolverson - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
