### ISSUE TITLE
Differences between modified and changed?

### ISSUE THREAD

**Issue by AhmadiRamin** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#222]
Hi,

What are the differences between when a record is modified and when a record is changed (business central connector)

and is there a way to subscribe to a custom table?
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fedc2db-772f-c6d2-7769-c132ad5bc457
* Version Independent ID: def5bf08-c74c-5041-cf68-61491df338d4
* Content: [Business Central - Connectors](https://docs.microsoft.com/en-gb/connectors/dynamicssmbsaas/#when-a-record-is-changed)
* Content Source: [docs/dynamicssmbsaas/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/dynamicssmbsaas/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@AhmadiRamin - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
