### ISSUE TITLE
Listed as Standard, also needs more clarification 

### ISSUE THREAD

**Issue by TheChaunz** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#223]
### Inconsistency of Standard vs Premium, and need more information on purpose of connector
Hey Team,

This connector is listed as Premium in the list of connectors at flow.microsoft.com/connectors. I'm pretty sure it's premium, but we should clarify.

Also, "provides access to org-based database" is not a sufficient description as to what purpose this connector serves in conjunction/in contrast to the normal CDS connector. Couple that with the licensing confusion, and this puts our makers in a weird place.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78bf3518-bce4-ecc5-8bf6-1fb627b9105e
* Version Independent ID: d46568f2-e080-cbbe-2f7e-a655bce20b64
* Content: [Common Data Service (current environment) - Connectors](https://docs.microsoft.com/en-us/connectors/commondataserviceforapps/)
* Content Source: [docs/commondataserviceforapps/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/commondataserviceforapps/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@TheChaunz - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
