### ISSUE TITLE
Typo in documentation page

### ISSUE THREAD

**Issue by miguelguadarrama** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#224]
There is a typo in documentation:  "qoutes"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6de37f0-2e5d-f0ee-bbf9-c6f5d7cdd6e6
* Version Independent ID: 4db5c39c-b2fb-9ed5-598c-6901fd17d3e3
* Content: [Azure Cosmos DB - Connectors](https://docs.microsoft.com/en-us/connectors/documentdb/)
* Content Source: [docs/DocumentDB/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/DocumentDB/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@miguelguadarrama - Thanks for your feedback. We have updated the docs to fix the spelling error, and the updated content is live. Closing this issue.
