### ISSUE TITLE
Additional Parameter Detail

### ISSUE THREAD

**Issue by topness-msft** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#226]
This doc is missing parameter detail needed to be useful.

playerType: powerapps | fieldservice
app:  {"appIdentifier": "<GUID>",  "displayName\": "<name>",  "type": "CanvasApp"}
Recipients:  this is optional, what happens if this is omitted?  Also: this appears to be an AD Object ID.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e319372-14e5-4c26-529c-ee49cfd7d011
* Version Independent ID: a3bc5df8-92f9-1f45-12a5-9b3fb4ed4668
* Content: [Power Apps Notification V2 - Connectors](https://docs.microsoft.com/en-us/connectors/powerappsnotificationv2/)
* Content Source: [docs/powerappsnotificationv2/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/powerappsnotificationv2/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by Znyldo** [comment]
Yes! Is missing! and is missinho an example, and I do not know how to put to work.
@topness-msft can you help me with an example?  I don't know how to use it, even the Dymics365.
What show is:

![Screenshot_1](https://user-images.githubusercontent.com/70381182/97046476-d3805480-154d-11eb-9d05-5f3c5258ef7b.jpg)

But I don't know how to fill "playerType","App" and "dynamicParams"
I already tryed the ID app but no success.

**Comment by topness-msft** [comment]
HI @Znyldo  - sorry for taking so long.  Clearly I need to fix my notifications.  :/

playerType is "powerapps" or "fieldservice"
App this object: {"appIdentifier": "FILL IN APP ID", "displayName": "FILL IN DISPLAY NAME", "type": "CanvasApp"}
I'm not sure about the dynamic parameters, but they don't appear requried.

**Comment by pcasti** [comment]
This is a sample:
![image](https://user-images.githubusercontent.com/5353147/147416765-d909cd6d-092c-4322-8bd1-d0c0996306a7.png)

**Comment by v-aangie** [comment]
@topness-msft - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
