### ISSUE TITLE
When will release this trigger in Turkey?

### ISSUE THREAD

**Issue by MusaAlican** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#228]
Hi I need to this trigger so much. When will you release in Europe (in Turkey actually)?

Thanks for your help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6e9cd1a-f737-edf3-b071-0aa47d2d61c6
* Version Independent ID: 0f8d5a0e-e96d-6ae4-e0f0-b435f6e71106
* Content: [Office 365 Groups Mail - Connectors](https://docs.microsoft.com/en-us/connectors/office365groupsmail/)
* Content Source: [docs/office365groupsmail/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/office365groupsmail/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@MusaAlican - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
