### ISSUE TITLE
A single action for Microsoft Forms

### ISSUE THREAD

**Issue by jdearaujo** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#229]
So I noticed that the action list only has one action. Are there plans to add more than one?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a5a57d-aa82-9c07-5502-bd3be89773dc
* Version Independent ID: 5bdbf2ae-5c31-7a59-56f0-09d568602012
* Content: [Microsoft Forms - Connectors](https://docs.microsoft.com/en-us/connectors/microsoftforms/)
* Content Source: [docs/MicrosoftForms/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/MicrosoftForms/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@jdearaujo - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
