### ISSUE TITLE
Unclear info on dynamic inputs and outputs

### ISSUE THREAD

**Issue by remyblok** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#230]
The page described the Approval Connector  but it is very light on the description of the input and output of the (non-depricated) actions. The page just says type dynamic for input and output which is not very useful. 

I'm creating a flow based on this connector, which work fine. But I would like some more documentation on the inputs and outputs that I could expect, especially since it is dynamic. This can help me when creating more complex Expressions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc3be4e8-204a-a1f5-21ea-a289dc8a0583
* Version Independent ID: 167b2834-1025-136b-9c25-4ba80e3c3410
* Content: [Approvals - Connectors](https://docs.microsoft.com/en-us/connectors/approvals/)
* Content Source: [docs/Approvals/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Approvals/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by LinnZawWin** [comment]
I agree with @remyblok 
I would be great to have some more information on the other dynamics parameters like Title, Details, Item link, Item link description, Enable notifications, Enable reassignment, Attachments.
I was not aware that the Attachments Content parameter accepts the value in binary. I was having an issue because I was trying to set the content value with base64.

**Comment by v-aangie** [comment]
@remyblok - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
