### ISSUE TITLE
Include callouts for Actions that don't work in GCC/GCCH/DOD

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#231]
While parts of the Teams connector work with O365 for US Govt clouds, several steps do not (like "Post a message as the Flow bot to a channel"). Please work with the product team to review which steps are expected to work in GCC/GCCH/DOD, and which are not, so that the documentation can reflect this accurately. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb4ba692-98a2-2ec7-319b-d75b59d3fa50
* Version Independent ID: c24a9495-e4cb-28db-3657-ecf81005757b
* Content: [Microsoft Teams - Connectors](https://docs.microsoft.com/en-us/connectors/teams/)
* Content Source: [docs/Teams/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Teams/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by npherson** [comment]
This impacts the ability for us to deliver several key platform plays in Teams with GCC customers. While this was a burden in FY21, it will be even more of an issue in FY22. What's the best way to escalate this request?

**Comment by v-aangie** [comment]
@npherson - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
