### ISSUE TITLE
GetOnNewItems_V2 - A "timestamp" column is required

### ISSUE THREAD

**Issue by zshane15** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#233]
Can you please update the documentation for **GetOnNewItems_V2** to include a footnote that a **timestamp NOT NULL** column is required for this trigger to work on a table? I had to dig quite a bit to figure out why my table was not triggering Flow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58c0b60a-fdc5-6ce7-e73f-c5071c0f9356
* Version Independent ID: 5865c7d1-abc2-4a70-56dd-4ebef0b411c4
* Content: [SQL Server - Connectors](https://docs.microsoft.com/en-us/connectors/sql/#when-an-item-is-modified-(v2))
* Content Source: [docs/Sql/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Sql/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@zshane15 - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
