### ISSUE TITLE
Add User is missing Tags and Groups as Additional Parameters

### ISSUE THREAD

**Issue by DonPetry-EY** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#234]
When adding a user, it is neccesary to specify which Tags and Groups they should be included in for Mailchimp segments to work properly.

Currently, the Connector does not provide this option and it is not clear how to add it.  Please add this ability...

https://mailchimp.com/developer/api/marketing/list-member-tags/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 765ffd53-c328-ee9f-f577-6889c528ef99
* Version Independent ID: d93a62f2-735d-4597-aa1b-ad8c8c5976de
* Content: [MailChimp - Connectors](https://docs.microsoft.com/en-us/connectors/mailchimp/)
* Content Source: [docs/MailChimp/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/MailChimp/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@DonPetry-EY - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
