### ISSUE TITLE
Receipts needs to be clarified

### ISSUE THREAD

**Issue by MattyBearBytes** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#237]
What data format is the input parameter of recipients? What is the delimiter between GUID/username that is used? If a comma, will it trim white space between them?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e319372-14e5-4c26-529c-ee49cfd7d011
* Version Independent ID: a3bc5df8-92f9-1f45-12a5-9b3fb4ed4668
* Content: [Power Apps Notification V2 - Connectors](https://docs.microsoft.com/en-au/connectors/powerappsnotificationv2/)
* Content Source: [docs/powerappsnotificationv2/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/powerappsnotificationv2/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@MattyBearBytes - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
