### ISSUE TITLE
Delete a Task Document

### ISSUE THREAD

**Issue by ThataIC** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#239]
[Enter feedback here]
I can see a delete a task documentation, but in the actual I cannot find the delete a task.

Any reason why I cannot used it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24185ffe-d266-c113-9327-4e305c276697
* Version Independent ID: 98978ace-f736-e07a-bde3-9156cd815100
* Content: [Planner - Connectors](https://docs.microsoft.com/en-us/connectors/planner/#delete-a-task)
* Content Source: [docs/Planner/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Planner/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@ThataIC - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
