### ISSUE TITLE
Planner Update a Task (v2) documentation

### ISSUE THREAD

**Issue by aqyx** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#240]
The Update a Task (v2) documentation for Microsoft Planner specifically mentions bucketId as a usable parameter within the action. When using the action, that parameter is not available.

Is the documentation wrong, and if not, when will this functionality be added?
 
![image](https://user-images.githubusercontent.com/13008664/98958415-279da980-24fa-11eb-90e7-aac3357dfc5c.png)

**Comment by v-aangie** [comment]
@aqyx - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
