### ISSUE TITLE
Office 365 Users > Get user profile (V2) 100 user limit instead of 1000?

### ISSUE THREAD

**Issue by SalviJansen** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#241]
The documentation for the "Get user profile (V2)" says that the default setting for the "Top" attribute is 1000, whereas by default only a 100 users are returned (at least when there is no search term completed, I haven't tested other scenarios). Manually entering "1000" in the Top field gives an error. The workaround to get ALL results is to enter "999" into the Top box which is really weird. I think the documentation should reflect the actual cut-off at 100, the maximum Top value of 999 (it seems) and that this maximum is related to the group members maximum.

I refer to the following forum topic:
https://powerusers.microsoft.com/t5/I-Found-A-Bug/get-group-members-returns-maximum-100-users/m-p/120190#M2297

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8635712-d5a2-e58a-301f-cf849f2cf2e4
* Version Independent ID: 4cfdd73e-f074-0446-2aee-2dd013a8b30f
* Content: [Office 365 Users - Connectors](https://docs.microsoft.com/en-us/connectors/office365users/?source=docs#limits)
* Content Source: [docs/office365users/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/office365users/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@SalviJansen - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
