### ISSUE TITLE
Not all projects visible

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#242]
Good afternoon,

I have an issue with all Connectors going to Azure DevOps.

It seems that not all projects can be selected when choosing List Work Items in Flow, or choosing Get Qery Results. We have multiple projects setup in exactly the same way. 

Please elaborate what we are missing in order to see all projects in our Azure DevOps organization.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1992475b-648a-9ebc-f165-abef6b5180a4
* Version Independent ID: da0b9096-309c-5d3f-11c2-0dba2c029c39
* Content: [Azure DevOps - Connectors](https://docs.microsoft.com/en-us/connectors/visualstudioteamservices/#definitions)
* Content Source: [docs/VisualStudioTeamServices/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/VisualStudioTeamServices/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@ghost - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
