### ISSUE TITLE
Power Automate Management Connector limitations

### ISSUE THREAD

**Issue by christianrudfoss** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#243]
Hi
I am wondering if you can tell me why there are limitations when using the Power Automate Management Connector. It seems that you can't reference to other flows in the same solution (Solution aware flows?). An example of an action is "Get Flow", that specifies an environment and flow name (which has to be flows outside the solution)

**Comment by v-aangie** [comment]
@christianrudfoss - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
