### ISSUE TITLE
Could we add more distinction here about how the connectors get shared for app users vs. app makers? I believe this line in the current docs tries to make the point but isn't clear: "You can share them directly, and they are also shared if you share an app or create a team flow that uses the connector." When you share the connector via "invite another user," is that meant for App Makers to share with other App Makers, or to share with App Users? The docs could add clarity here.

### ISSUE THREAD

**Issue by TashasEv** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#244]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd3d6fa-3833-5800-4b5c-dcdd39b88c37
* Version Independent ID: 8709487d-3012-2b8c-ad40-abebd741ad87
* Content: [Share a custom connector in your organization](https://docs.microsoft.com/en-us/connectors/custom-connectors/share)
* Content Source: [docs/custom-connectors/share.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/share.md)
* Service: **connectors**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by v-aangie** [comment]
@TashasEv - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
