### ISSUE TITLE
No mention of supported Open API standard.

### ISSUE THREAD

**Issue by MandarJKulkarni** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#245]
Currently we cannot create custom connector from an open api specification file with open api standard 3.0.0
Only open API standard 2.0.0 files are supported. I couldn't find this information in the documentation.
https://docs.microsoft.com/en-us/connectors/custom-connectors/define-openapi-definition

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9659a345-1116-5020-4300-386f3a591c2e
* Version Independent ID: e2a3861f-d3d5-f542-28db-1897d4c7feb0
* Content: [Create a custom connector from an OpenAPI definition](https://docs.microsoft.com/en-us/connectors/custom-connectors/define-openapi-definition)
* Content Source: [docs/custom-connectors/define-openapi-definition.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/define-openapi-definition.md)
* Service: **connectors**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by natalie-pienkowska** [comment]
Hi @MandarJKulkarni Thanks for the feedback! We've updated the page to reflect that we only support OpenAPI 2.0
