### ISSUE TITLE
Wrong domain url

### ISSUE THREAD

**Issue by mojomojo52** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#246]
[Enter feedback here]

In "Creating an OAuth Client Application in Google"

"Add azure.apim as one of the authorized domains" is wrong.
It should be:
"Add azure-apim.net as one of the authorized domains" 

Also, the doc should add the you need to register the account as a tester.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94336520-0566-edeb-a3c8-48e7065c19b2
* Version Independent ID: aec0952b-45bb-6d5c-532f-9e3451713e98
* Content: [Gmail - Connectors](https://docs.microsoft.com/en-us/connectors/gmail/#feedback)
* Content Source: [docs/Gmail/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Gmail/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@mojomojo52 - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
