### ISSUE TITLE
Twitter Connector Retired but not shown here

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#247]
https://www.reddit.com/r/Office365/comments/fa4wdc/microsoft_teams_retires_twitter_connector_as_of/

However, Power Automate isn't as easy to use and may be more restricted by different environments (like MSIT). Having a simple connector brought back would be appreciated and have saved me hours of headache.

There seems to be dozens of requests for this back on UserVoice as well:
 - https://microsoftteams.uservoice.com/forums/555103-public/suggestions/40023370-bring-back-the-twitter-connector
 - https://microsoftteams.uservoice.com/forums/555103-public/suggestions/18615961-better-integration-with-twitter
 - https://microsoftteams.uservoice.com/forums/555103-public/suggestions/40285942-twitter-and-facebook-connectors
 - https://microsoftteams.uservoice.com/forums/555103-public/suggestions/18615994-a-better-integration-with-twitter-linkedin-and-fa

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4362ac6-b761-f114-a78d-1c1a7a19b67a
* Version Independent ID: d2d21050-f068-b115-3755-e4752766b8c1
* Content: [Twitter - Connectors](https://docs.microsoft.com/en-us/connectors/twitter/)
* Content Source: [docs/twitter/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/twitter/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@michael-hawker - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
