### ISSUE TITLE
Step 6: No New trigger in PowerApps

### ISSUE THREAD

**Issue by HubSaul** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#248]
In step 6, you show a + New trigger in the PowerApp

This does not show up in our Powerapps environment - please can you provide the OpenApi that needs to be added instead

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49d0e0df-c314-933d-43a9-c735081ddd5a
* Version Independent ID: a4aaf076-c72b-6585-b91c-ad98d5cd045d
* Content: [Use a polling trigger for Microsoft Power Automate](https://docs.microsoft.com/en-us/connectors/custom-connectors/create-polling-trigger#feedback)
* Content Source: [docs/custom-connectors/create-polling-trigger.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/create-polling-trigger.md)
* Service: **connectors**
* GitHub Login: @DougKlopfenstein
* Microsoft Alias: **v-douklo**

**Comment by v-aangie** [comment]
@HubSaul - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
