### ISSUE TITLE
set host policy does not work when custom connector uses on premise data gateway

### ISSUE THREAD

**Issue by malaker** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#249]
Set host policy and none of expressions work correctly with on-premise data gateway. Do you have any information when it will be fixed?

https://community.dynamics.com/365/f/dynamics-365-general-forum/410156/power-automate-custom-connector-s-set-host-policy-not-working

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41458bed-f93a-5a9a-7cc2-24ad4a615fec
* Version Independent ID: 8e286b44-d1ee-409d-5665-af213a1c7789
* Content: [Expressions](https://docs.microsoft.com/en-us/connectors/custom-connectors/policy-templates/expressions/expressions)
* Content Source: [docs/custom-connectors/policy-templates/expressions/expressions.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/policy-templates/expressions/expressions.md)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@malaker - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
