### ISSUE TITLE
Analyze Form - Keys to extract list form

### ISSUE THREAD

**Issue by mostness** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#25]
For Analyze Form, parameter "Keys to extract" is a "list of known keys".  What is the list format to use for this string?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e84d6396-2e1e-2c2b-3c15-28c34c3d0557
* Version Independent ID: 4b1b05aa-bcab-57f6-9f6d-6ed2014d6d75
* Content: [Form Recognizer - Connectors](https://docs.microsoft.com/en-us/connectors/formrecognizer/#feedback)
* Content Source: [docs/formrecognizer/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/formrecognizer/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment]
This seems to be a limitation of the end service API documentation as it does not specify either.

https://westus2.dev.cognitive.microsoft.com/docs/services/form-recognizer-api/operations/AnalyzeWithCustomModel.

Please re-open this issue if you are able to propose a change to update this documentation.
