### ISSUE TITLE
Reflect Upsert ability of 'Update a Record'

### ISSUE THREAD

**Issue by eBentl** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#250]
The 'Update a Record' function documentation be updated to reflect that the command will create a record if it does not already exist.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 603b00f9-8a99-140e-c640-cb2bcc28b5f1
* Version Independent ID: 0e07aace-2e6d-132c-c8b5-113b3c15085e
* Content: [Common Data Service - Connectors](https://docs.microsoft.com/en-gb/connectors/commondataservice/#update-a-record)
* Content Source: [docs/commondataservice/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/commondataservice/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@eBentl - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
