### ISSUE TITLE
Http with Azure AD documentation should reflect Power Apps limitations

### ISSUE THREAD

**Issue by pjsummersjr** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#252]
The [documentation page for the Http with Azure AD connector](https://docs.microsoft.com/en-us/connectors/webcontents/) does not indicate that when the connector is used in Power Apps, it will only return a boolean, rather than a string.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ce7ba1f-e39a-b6d7-dcd3-0bba96f28e92
* Version Independent ID: f254a24f-6004-849f-d566-10d7d3e87779
* Content: [HTTP with Azure AD - Connectors](https://docs.microsoft.com/en-us/connectors/webcontents/)
* Content Source: [docs/webcontents/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/webcontents/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@pjsummersjr - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
