### ISSUE TITLE
Please include Expected Return Values of "Actions"

### ISSUE THREAD

**Issue by ikessler0424** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#254]
Please include the expected return values when requests are made using the actions provided (if they are not freeform). A good example of this is:

Action Type | actionType | string | Type of action which changed the event in change trigger.
Values included would be:
- "added"
- "deleted"
- "updated" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 352d2e69-2be4-03c9-9fa8-f3b9795cab42
* Version Independent ID: 8889e801-9db2-aab1-ebf3-1340ae15f0f1
* Content: [Google Calendar - Connectors](https://docs.microsoft.com/en-us/connectors/googlecalendar/#when-an-event-is-added%2c-updated-or-deleted-from-a-calendar)
* Content Source: [docs/GoogleCalendar/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/GoogleCalendar/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@ikessler0424 - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
