### ISSUE TITLE
Export Email (V2) should mention that export format is .eml

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#255]
The Export Email (V2) action does not mention the target export format which is ".eml".
Using the ".msg" extension can't open the exported message with outlook or other mail client.
Using the ".eml" extension instead of ".msg" opens correctly the exported file with mail clients.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc40a098-af8c-d8a9-4538-71d184efbe91
* Version Independent ID: 0ee8cf79-18e9-d923-607f-ef40cdd23e4d
* Content: [Office 365 Outlook - Connectors](https://docs.microsoft.com/en-us/connectors/office365/#export-email-(v2))
* Content Source: [docs/office365/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/office365/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@ghost - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
