### ISSUE TITLE
Example of how to use Convert An Object To An Array(Preview) policy template

### ISSUE THREAD

**Issue by goda** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#257]
Trying to understand the policy templates and how to use them has been very difficult as the docs are short and not very descriptive on how to configure the parameters properly.

Is it possible to provide a sample example of how to apply both the Convert An Object To An Array(Preview) and Convert An Array To An Object(Preview) policy templates? Showing the input JSON, what the policy parameters need to be, as well as what the final output would be.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2bc3c7c-7f73-0635-a1a8-30e026b4ebf9
* Version Independent ID: 748c4021-4ef1-1e33-5cce-030d1289bf68
* Content: [Convert An Object To An Array(Preview)](https://docs.microsoft.com/en-us/connectors/custom-connectors/policy-templates/convertobjecttoarray/convertobjecttoarray)
* Content Source: [docs/custom-connectors/policy-templates/convertobjecttoarray/convertobjecttoarray.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/policy-templates/convertobjecttoarray/convertobjecttoarray.md)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@goda - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
