### ISSUE TITLE
DB2 Connector does not seem to support gt, ge, lt, le filters

### ISSUE THREAD

**Issue by ericthomas1** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#258]
Hello,

I need to know whether the DB2 connector is broken or does not support `gt`, `ge`, `lt`, `le` operators. 

**Example:**
- If I run the following query **directly** on the DB2 database, it returns 17 records
```
SELECT * FROM DB2_TABLE
WHERE LOAD_TS >= '2021-01-05'
```
![image](https://user-images.githubusercontent.com/42788729/103812920-19f53380-5014-11eb-97a3-c7724c82852f.png)

- If I add the Filter Query `'LOAD_TS' ge '2020-01-05'`, the filter is not respected and all records in the DB2 table are returned.
- I've tried `formatDateTime(utcNow(), 'MM/dd/yyyy hh:mm:ss')` etc, but nothing works.
![image](https://user-images.githubusercontent.com/42788729/103813359-d51dcc80-5014-11eb-92cd-90473a31705a.png)

PLEASE ADVISE. 

This has been a longstanding issue, need an answer: 
- https://powerusers.microsoft.com/t5/Building-Flows/DB2-GetRows-Filter-By-Date/td-p/646391

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be2e8667-7502-4b40-afe7-3de992679318
* Version Independent ID: 873d28d2-0fe3-d348-d3bb-532f7ff4c8c0
* Content: [DB2 - Connectors](https://docs.microsoft.com/en-us/connectors/db2/#known-issues-and-limitations)
* Content Source: [docs/DB2/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/DB2/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by ericthomas1** [comment]
bump

**Comment by v-aangie** [comment]
@ericthomas1 - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
