### ISSUE TITLE
do post  and pass Blob body in hTTP with Azure AD

### ISSUE THREAD

**Issue by iovex** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#26]
how can I do post request in powerapps canvas app ,how to pass the body? as I know , the body is a Blob type , how can I convert json to Blob ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ce7ba1f-e39a-b6d7-dcd3-0bba96f28e92
* Version Independent ID: f254a24f-6004-849f-d566-10d7d3e87779
* Content: [HTTP with Azure AD - Connectors](https://docs.microsoft.com/en-us/connectors/webcontents/#feedback)
* Content Source: [docs/webcontents/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/webcontents/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment]
Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback)
