### ISSUE TITLE
cross-company parameter missing in FinOps action 'update a record'

### ISSUE THREAD

**Issue by vseykov** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#264]
Cross company parameter is missing, hence the flow cannot update records in Company specific tables unless the default company of the connection used is the same as the one of the record being updated
![image](https://user-images.githubusercontent.com/21282262/106122991-085e0200-6162-11eb-9fb7-db66167b3735.png)

**Comment by v-aangie** [comment]
@vseykov - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
