### ISSUE TITLE
Not possible to configure a policy using policy templates to perform throttling  

### ISSUE THREAD

**Issue by davidyack** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#266]
[Enter feedback here]

Intro paragraph says "For example, policies are used to **_**_enforce throttling limits on API calls_**_**, to route calls to different endpoints, and so on"

Replace throttling with something  like convert response data that you can do with policy templates

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54a9dbfc-59c8-3b66-af5c-7afe0e312384
* Version Independent ID: a34a4759-a955-870c-5566-d2101f0654cb
* Content: [Policy support in custom connectors](https://docs.microsoft.com/en-us/connectors/custom-connectors/policy-templates)
* Content Source: [docs/custom-connectors/policy-templates.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/policy-templates.md)
* Service: **connectors**
* GitHub Login: @shyamsu
* Microsoft Alias: **shyamsu**

**Comment by v-aangie** [comment]
@davidyack - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.

**Comment by davidyack** [comment]
The problem is that content suggests an action not supported by policy templates and should be updated

**Comment by davidyack** [comment]
@v-aangie  please advise why you closed without fixing the content
