### ISSUE TITLE
Parameters string validation issues

### ISSUE THREAD

**Issue by cwarne** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#269]
The `parameters` value for `Queue a new build` is vague. It is clear it needs to be a JSON dictionary string although I am still getting a 400 code validation error.

I'm trying the format:
```json
"parameters": "{\"param1\": \"false\", \"deployEnvironment\": \"dev\", \"dropDownParam\": \"Monday\"}",
```
Is this format correct? These keys and values are the same as those listed on the ADO pipeline build.
Additionally, are the drop down / radio selection build parameters value's defined differently? And it appears that boolean values are quoted, is that correct?

Thank you for the clarification here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1992475b-648a-9ebc-f165-abef6b5180a4
* Version Independent ID: da0b9096-309c-5d3f-11c2-0dba2c029c39
* Content: [Azure DevOps - Connectors](https://docs.microsoft.com/en-us/connectors/visualstudioteamservices/#queue-a-new-build)
* Content Source: [docs/VisualStudioTeamServices/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/VisualStudioTeamServices/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@cwarne - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
