### ISSUE TITLE
Connectors missing from the list

### ISSUE THREAD

**Issue by zsolt-illes** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#270]
The list is missing the below connectors:
HTTP
HTTP Webhook
Spatial Services
When a HTTP Request

The first two being critical, because with a little knowledge users can go around the DLP Policies in the tenant and leak out any information anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2067cc5-57dd-bbf9-6194-9a63506d301c
* Version Independent ID: 96125d37-c7bb-b0a3-49c3-384a3674abcd
* Content: [List of all Power Apps connectors](https://docs.microsoft.com/en-us/connectors/connector-reference/connector-reference-powerapps-connectors)
* Content Source: [docs/connector-reference/connector-reference-powerapps-connectors.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/connector-reference/connector-reference-powerapps-connectors.md)
* Service: **connectors**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by v-aangie** [comment]
@zsolt-illes - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
