### ISSUE TITLE
Chunked transfer mode limitation

### ISSUE THREAD

**Issue by sandeep-ma** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#271]
[Enter feedback here]
Please update the design limitations section of this article to clearly indicate that the "Create File" action is designed to fail when attempting to create a new version of a file in chunked transfer mode, if the file is greater than 100KB in size. And that chucked transfer can be disabled if it is desired to create a new version of a file greater than 100KB

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a893f4d-b1cf-b32f-6c54-421d72831cc8
* Version Independent ID: db4d1fcf-5125-6d0f-f5eb-31ec98def9f4
* Content: [SharePoint - Connectors](https://docs.microsoft.com/en-us/connectors/sharepoint/)
* Content Source: [docs/SharePoint/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/SharePoint/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@sandeep-ma - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
