### ISSUE TITLE
Fix references to "Visual Studio Team Services"

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#272]
This docs page still has references to the old name "Visual Studio Team Services". Let's get those fixed.

Thanks,
--Neno

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 1992475b-648a-9ebc-f165-abef6b5180a4
* Version Independent ID: da0b9096-309c-5d3f-11c2-0dba2c029c39
* Content: [Azure DevOps - Connectors](https://docs.microsoft.com/de-de/connectors/visualstudioteamservices/)
* Content Source: [docs/VisualStudioTeamServices/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/VisualStudioTeamServices/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@NenoLoje - Thanks for your feedback. We have updated the docs to fix information about Visual Studio Team Services, and the updated content is live. Closing this issue.
