### ISSUE TITLE
Known issue link is browken

### ISSUE THREAD

**Issue by HinaMS** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#274]
Known issue link: https://docs.microsoft.com/en-us/connectors/common/known-issues.md  is not working.
Please get this fixed for Connectors topic

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a6df7b0-04ac-5f64-d641-db13bfd34a00
* Version Independent ID: afccffbb-7b4c-d351-3a0f-ada16c5ce282
* Content: [Instructions on providing feedback for connectors](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback)
* Content Source: [docs/custom-connectors/provide-feedback.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/provide-feedback.md)
* Service: **connectors**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by v-aangie** [comment]
@HinaMS - Thanks for your feedback. We have updated the docs to fix information about the link, and the updated content is live. Closing this issue.
