### ISSUE TITLE
Connection Parameters

### ISSUE THREAD

**Issue by swettstein** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#275]
Is there any way to authenticate a connection via a Service Principal in AAD? The access key grants too much access to users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4a1ef15-eee8-e31f-e05d-34ae84216545
* Version Independent ID: 01cf0d74-3e50-c6c9-fe0d-7d639886318c
* Content: [Azure Blob Storage - Connectors](https://docs.microsoft.com/en-us/connectors/azureblob/)
* Content Source: [docs/azureblob/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/azureblob/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@swettstein - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
