### ISSUE TITLE
How to get ID of email

### ISSUE THREAD

**Issue by afratila** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#277]
I have a particular use case where I'd like to have my Logic App reply to an email without the trigger being "when an email is received", and instead use the http trigger. Ideally the http trigger would include the email ID in payload and Logic App could use that in the "reply to email" step.

My question is: when I open Outlook and select an email, how can I see its ID?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc40a098-af8c-d8a9-4538-71d184efbe91
* Version Independent ID: 0ee8cf79-18e9-d923-607f-ef40cdd23e4d
* Content: [Office 365 Outlook - Connectors](https://docs.microsoft.com/en-us/connectors/office365/#reply-to-email-(v3))
* Content Source: [docs/office365/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/office365/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@afratila - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
