### ISSUE TITLE
Incorrect documentation on the Create SAS URI by path Start Time

### ISSUE THREAD

**Issue by Floriszz** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#278]
[Enter feedback here]
According the tooltip the default value for Start Time is now().  But as you can see in the error message below it will not allow now() in the Start Time value. 
What I entered in the Start Time field was: subtractFromTime(now(), 15, 'Minute') to make sure the link is working regardless of little time differences between system and receiver. 
instead of now() utcNow() does work, but can have a whole different outcome ofcourse!

Error:
InvalidTemplate. Unable to process template language expressions in action 'Create_SAS_URI_by_path_for_blob' inputs at line '1' and column '3519': 'The template function 'Now' is not defined or not valid.'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4a1ef15-eee8-e31f-e05d-34ae84216545
* Version Independent ID: 01cf0d74-3e50-c6c9-fe0d-7d639886318c
* Content: [Azure Blob Storage - Connectors](https://docs.microsoft.com/en-us/connectors/azureblob/)
* Content Source: [docs/azureblob/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/azureblob/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@Floriszz - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
