### ISSUE TITLE
Weather connector take the wrong datetime to get the weather when using the waiting step before

### ISSUE THREAD

**Issue by ahmedmahdi** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#279]
Hi,
When I have a waiting step for 1 day or more before the weather, the MSN Weather connector take the dateTime of the flow start and not the current day and this make the flow wrong

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 4bbeba7f-5c07-3fa6-2d19-d973fb3be68c
* Version Independent ID: 30c3272f-550b-66da-4554-baffe0185e61
* Content: [MSN Weather - Connectors](https://docs.microsoft.com/fr-fr/connectors/msnweather/#get-the-forecast-for-tomorrow)
* Content Source: [docs/MsnWeather/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/MsnWeather/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@ahmedmahdi - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
