### ISSUE TITLE
Can you add the get list trigger ?

### ISSUE THREAD

**Issue by sdavos** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#28]
Can you add the get list trigger ?
And other entity trigger ?
That could be very great !! :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3048fd61-c645-0bfa-fcf3-c9c9a77ebabb
* Version Independent ID: eabc60e8-1278-61ff-a90c-64afa4ddd443
* Content: [Pipedrive - Connectors](https://docs.microsoft.com/en-us/connectors/pipedrive/)
* Content Source: [docs/Pipedrive/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Pipedrive/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment]
Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback)
