### ISSUE TITLE
Can you provide examples on how to construct the event Content?

### ISSUE THREAD

**Issue by DrEsteban** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#280]
The current documentation is pretty bare-bones, and doesn't provide any pointers on how to construct a `byte` payload in Power Apps. We're trying to take a JSON string and send that as the event payload to an Event Hub, but I can't seem to find any way to construct a binary format of a string (sometimes referred to as type "Blob"), within the PowerApps ecosystem.  I couldn't find any base64 encoders or anything in the Canvas app experience.  Attempting to send the "unconverted" JSON string as the event payload results in an error:

```json
{
    "error": {
        "code": "TriggerInputSchemaMismatch",
        "message": "The input body for trigger 'manual' of type 'Request' did not match its schema definition. Error details: 'Invalid type. Expected String but got Null.'."
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f51644a6-79dc-d6c3-8fe3-620ea99872be
* Version Independent ID: 5f05de0f-d02c-08e6-38b4-35c61cafa095
* Content: [Event Hubs - Connectors](https://docs.microsoft.com/en-us/connectors/eventhubs/#send-event)
* Content Source: [docs/EventHubs/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/EventHubs/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@DrEsteban - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
