### ISSUE TITLE
How to set body of the requested URL when the httpMethod is POST?

### ISSUE THREAD

**Issue by smig23** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#282]
There doesn't appear to be any documentation or examples of setting the body of a POST request if the httpMethod is set to POST rather than GET.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c49bd67f-ec44-0eac-9aa0-b7ada190b557
* Version Independent ID: a2f4c83d-9c12-1ce3-c9c7-bfed20ec4f44
* Content: [Set Header/Query Parameter Value From URL(Preview)](https://docs.microsoft.com/en-us/connectors/custom-connectors/policy-templates/setvaluefromurl/setvaluefromurl)
* Content Source: [docs/custom-connectors/policy-templates/setvaluefromurl/setvaluefromurl.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/policy-templates/setvaluefromurl/setvaluefromurl.md)
* Service: **connectors**
* GitHub Login: @natalie-pienkowska
* Microsoft Alias: **napienko**

**Comment by v-aangie** [comment]
@smig23 - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
