### ISSUE TITLE
not possible to export collection as v1 in postman v8

### ISSUE THREAD

**Issue by DmitryKleshchov** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#283]
In postman v8+ it's not possible to export collections as v1 anymore, at least with the screenshots provided in the article. Either they deprecated v1 exports completely, or instructions to do that changed. Anyhow unfortunately I wasn't able to export a collection as a v1 in new postman

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a54d3a6-8cc5-37c2-a37e-b46054d22a73
* Version Independent ID: ae119da7-b9cc-e6eb-3dac-8ba8ac704ccd
* Content: [Create a Postman collection for a custom connector](https://docs.microsoft.com/en-us/connectors/custom-connectors/create-postman-collection)
* Content Source: [docs/custom-connectors/create-postman-collection.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/create-postman-collection.md)
* Service: **connectors**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by natalie-pienkowska** [comment]
Thank you for your feedback! We are happy to announce that we will be supporting Postman V2 in the next few weeks :)
