### ISSUE TITLE
List Rows: FetchXml with Aggregation broken

### ISSUE THREAD

**Issue by DanielBruckhaus** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#285]
The List Rows action cannot properly handle FetchXml aggregation.
This is not listed in the _Known issues and limitations_ section

Details:
If the fetchxml query does not contain the primary id attribute of the table being queried, the List Rows action fails with  message:

> Key property '[PrimaryIdAttribute]' of type 'Microsoft.Dynamics.CRM.[LogicalName]' is null. Key properties cannot have null values.

For example, with an aggregate query on the Activity table:

> Key property 'activityid' of type 'Microsoft.Dynamics.CRM.activitypointer' is null. Key properties cannot have null values.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78bf3518-bce4-ecc5-8bf6-1fb627b9105e
* Version Independent ID: d46568f2-e080-cbbe-2f7e-a655bce20b64
* Content: [Common Data Service (current environment) - Connectors](https://docs.microsoft.com/en-us/connectors/commondataserviceforapps/#list-rows)
* Content Source: [docs/commondataserviceforapps/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/commondataserviceforapps/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@DanielBruckhaus - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
