### ISSUE TITLE
If this connector is deprecated... which connector should be used?

### ISSUE THREAD

**Issue by sorcia25** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#287]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2294a2b5-f7af-95bf-5a38-4391dd90cdd6
* Version Independent ID: 4221f8bb-e548-5e5f-ce3a-b477d221a468
* Content: [Dynamics 365 (deprecated) - Connectors](https://docs.microsoft.com/en-us/connectors/dynamicscrmonline/#power-apps-delegable-functions-and-operations-for-dynamics-365)
* Content Source: [docs/dynamicscrmonline/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/dynamicscrmonline/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@sorcia25 - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
