### ISSUE TITLE
Power Query Dataflows ARE NOT available in Logic Apps despite documentation saying otherwise

### ISSUE THREAD

**Issue by aimskl** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#288]
This page says that Power Query Dataflows are available in Logic Apps. But this appears to be wrong.
![image](https://user-images.githubusercontent.com/71928381/110811405-a1d01600-82c1-11eb-911e-50e4dda772f5.png)

I have spun up logic apps in various regions like West US and Asia Pacific. Both regions showed no options for power query dataflows. Neither as trigger nor as action.
![image](https://user-images.githubusercontent.com/71928381/110811351-954bbd80-82c1-11eb-9d93-25c01011c667.png)

![image](https://user-images.githubusercontent.com/71928381/110811509-bc09f400-82c1-11eb-8a52-56d4ed4dbfec.png)

They are available in Power Automate (and Power Apps). But I want to use them in Logic Apps, as is documented...

Separately, Power BI actions _are_ available in Logic Apps, but I need to first refresh a Power Query Dataflow before refreshing the related Dataset...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b2f4932-6823-0a6a-fd8a-36130bfb7d95
* Version Independent ID: d11509ca-ed77-6bd0-d2e3-bbb75675050e
* Content: [Power Query Dataflows - Connectors](https://docs.microsoft.com/en-us/connectors/dataflows/)
* Content Source: [docs/dataflows/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/dataflows/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@aimskl - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
