### ISSUE TITLE
"Calculate" column type's delegable status is unclear

### ISSUE THREAD

**Issue by FerretyWorld** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#289]
The page lists that Text type from Sharepoint includes "Calculated", and based on the table's definition of "Text" types, it implies that this column type (calculated) is delegable. However, "Calculated" columns are not delegable no matter what we've tried. We've confirmed that the type selected within the column settings is "single line of text". It might be worth calling out a footer like some of the other types have that show there's a caveat about the "Calculated" column types.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69a01872-3062-4100-f807-7d43e8111e9f
* Version Independent ID: 48560378-76ed-cb42-e816-894179e1f16d
* Content: [SharePoint - Connectors](https://docs.microsoft.com/en-us/connectors/sharepointonline/)
* Content Source: [docs/sharepointonline/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/sharepointonline/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@FerretyWorld - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
