### ISSUE TITLE
Name is now Logic Apps Custom Connector

### ISSUE THREAD

**Issue by jcmacgregor** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#29]
In the instructions it says, " In the search box, enter logic apps connector as your filter" but this returns no results, as the new name is Logic Apps Custom Connector.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9640dfd-4bf8-3aa7-f431-d052ebaeae19
* Version Independent ID: 0c5d6db1-34f6-f613-8cf9-c13300d2d5f4
* Content: [Create a custom connector in Azure Logic Apps](https://docs.microsoft.com/en-us/connectors/custom-connectors/create-logic-apps-connector#feedback)
* Content Source: [docs/custom-connectors/create-logic-apps-connector.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/create-logic-apps-connector.md)
* Service: **connectors**
* GitHub Login: @divyaswarnkar
* Microsoft Alias: **divswa**

**Comment by bezhan-msft** [comment]
Thank you for your feedback. This is now under review and no further action is required at this time.

**Comment by DougKlopfenstein** [comment]
@jcmacgregor This issue has now been fixed.
