### ISSUE TITLE
Add GCC as Unsupported for Shifts Connector

### ISSUE THREAD

**Issue by rocamp** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#291]
Please list GCC Moderate as another unsupported region for this connector in Power Automate and Power Apps. This is confirmed by Devin Carr (decar)

https://portal.microsofticm.com/imp/v3/incidents/details/230105105/home 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76fc4f9f-bea0-fb07-2f1d-d7c322cd9c80
* Version Independent ID: bf1dec05-5e3c-ab9c-729a-82def10038fc
* Content: [Shifts for Microsoft Teams - Connectors](https://docs.microsoft.com/en-us/connectors/shifts/)
* Content Source: [docs/shifts/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/shifts/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@rocamp - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
