### ISSUE TITLE
Replacing host but also base URL

### ISSUE THREAD

**Issue by Quartermaster-007** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#294]
Set Host URL policy overwrites any set Host URL of the custom connector itself.
However, the documentation does not mention that it also replaces any set string in the Base URL, so the policy will need to include that as well.

Example: (in apiDefinition.swagger.json or Custom Connector wizard step 1)
```
"host": "changemepls.topdesk.net",
"basePath": "/tas/api",
```

Change expected: (using policy templates in apiProperties.json)
```
"templateId": "dynamichosturl",
        "title": "Set TOPdesk environment",
        "parameters": {
          "x-ms-apimTemplateParameter.urlTemplate": "https://@connectionParameters('TOPdeskTenant').topdesk.net",
```

Expected behaviour that all operations continue to use the provided basePath. **But this will fail any operations that need the Base URL**, because Base URL is no longer used from apiDefinition.swagger.json.

And in reality you need:
```
"templateId": "dynamichosturl",
        "title": "Set TOPdesk environment",
        "parameters": {
          "x-ms-apimTemplateParameter.urlTemplate": "https://@connectionParameters('TOPdeskTenant').topdesk.net/tas/api",
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3817394-e2f3-da6b-797c-552ae6f3e71f
* Version Independent ID: b0e24b14-8f7c-57e4-e7e7-4e0447dcf354
* Content: [Set Host URL](https://docs.microsoft.com/en-us/connectors/custom-connectors/policy-templates/dynamichosturl/dynamichosturl)
* Content Source: [docs/custom-connectors/policy-templates/dynamichosturl/dynamichosturl.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/policy-templates/dynamichosturl/dynamichosturl.md)
* Service: **connectors**
* GitHub Login: @natalie-pienkowska
* Microsoft Alias: **napienko**

**Comment by v-aangie** [comment]
@Quartermaster-007 - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
