### ISSUE TITLE
PostMessageToConversation issue?

### ISSUE THREAD

**Issue by dbaars** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#295]
Hi,
the PostMessageToConversation details above suggest there are 3 required fields, post as, post in, and message, however when I try and use it in PowerApps 
![image](https://user-images.githubusercontent.com/14931710/111932839-296c1f00-8b23-11eb-8146-735c1251823f.png)

1. It is not clear what the location (post in) field should be (especially if we're trying to target a user)
2. When putting some dummy data in, the command doesn't seem to want to accept 3 variables, even though this page says they are all required
![image](https://user-images.githubusercontent.com/14931710/111933910-4bff3780-8b25-11eb-8c54-08fa4cda8dfd.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb4ba692-98a2-2ec7-319b-d75b59d3fa50
* Version Independent ID: c24a9495-e4cb-28db-3657-ecf81005757b
* Content: [Microsoft Teams - Connectors](https://docs.microsoft.com/en-us/connectors/teams/#post-message-in-a-chat-or-channel)
* Content Source: [docs/Teams/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Teams/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@dbaars - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
