### ISSUE TITLE
Github connector - When a pull request is created or modified - does not work for organization

### ISSUE THREAD

**Issue by komoreka** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#296]
Hi All, 

I did test on private account and works. 
As Soon as I changed Repository Owner to organization name and picked repo from there it is not working.
Is this already should work or was not yet developed ?
If not yet than - Is it in backlog ?

**Comment by v-aangie** [comment]
@komoreka - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
