### ISSUE TITLE
Onenote connector - Create page in a section

### ISSUE THREAD

**Issue by komoreka** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#297]
Hi All.

Is there a way to create subpage instead of page via connector ?

**Comment by v-aangie** [comment]
@komoreka - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
