### ISSUE TITLE
Not clear what detail is required for Logic Apps MySQL on-premise connector

### ISSUE THREAD

**Issue by jamesmcroft** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#298]
The documentation outlines what fields are available but not examples of what the values of those fields should look like. 

We have installed the necessary Connector/Net version on the server where our MySQL instance exists and have attempted to connect to it on a custom port (3307) but we are receiving the following error:

```
Test connection failed. Error 'MySQL: We were unable to find a database provider with invariant name 'MySql.Data.MySqlClient'.
This error could've been the result of provider-specific client software being required, but missing on this computer.  To download client software for this provider, visit the following site and choose the 64-bit (x64) version of, at minimum, 'MySQL Connector/Net': https://go.microsoft.com/fwlink/?LinkId=278885'
```

We can connect to it locally from Jetbrains DataGrip however so we know the details we have are correct. 

It would be helpful for there to be more detail or examples on how to use the connector.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0427dc6f-a63d-2bcb-b141-290335f47671
* Version Independent ID: 129d5c5a-2018-d8a6-e0ff-488f48aa22f8
* Content: [MySQL - Connectors](https://docs.microsoft.com/en-us/connectors/mysql/)
* Content Source: [docs/MySql/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/MySql/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by jamesmcroft** [comment]
Asking this question on the community Q&A, it looks like the issue is that the docs don't explain the Connector/Net for MySQL needs to be installed where the on-premise data gateway is.

This just needs clarifying in the documentation.

https://docs.microsoft.com/en-us/answers/questions/327312/test-connection-failed-to-on-premise-mysql-instanc.html

**Comment by v-aangie** [comment]
@jamesmcroft - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
