### ISSUE TITLE
Content-type what values?

### ISSUE THREAD

**Issue by wfplrc** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#299]
Content-Type is defined as the type of file but is not clear how to specify it. What value is expected?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94336520-0566-edeb-a3c8-48e7065c19b2
* Version Independent ID: aec0952b-45bb-6d5c-532f-9e3451713e98
* Content: [Gmail - Connectors](https://docs.microsoft.com/en-us/connectors/gmail/#send-email-(v2))
* Content Source: [docs/Gmail/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Gmail/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@wfplrc - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
