### ISSUE TITLE
"Settings->Pagination..." Detail required

### ISSUE THREAD

**Issue by keohan** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#300]
Re. Page: https://docs.microsoft.com/en-us/connectors/office365groups/

Please provide a link to details regarding the instructions for "List group members" which indicates :
"In case you need to retrieve more than 1000 values please turn on Settings->Pagination feature and provide Threshold limit."

I cannot find a reference to Settings->Pagination or where this is applied.

**Comment by v-aangie** [comment]
@keohan - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
