### ISSUE TITLE
Trigger - when blob is added addtional parameters are not in documentation

### ISSUE THREAD

**Issue by Floriszz** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#301]
[Enter feedback here]
There are 2 additional parameters;
- Zone
- Start time
These are not mentioned in the documentation. Especially the Start time is interesting to me.
I noticed the trigger fires on all existing blob the first time the solution is enabled. Not just on a newly added blob. So this Start time might have to do with this behavior?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4a1ef15-eee8-e31f-e05d-34ae84216545
* Version Independent ID: 01cf0d74-3e50-c6c9-fe0d-7d639886318c
* Content: [Azure Blob Storage - Connectors](https://docs.microsoft.com/en-us/connectors/azureblob/#when-a-blob-is-added-or-modified-(properties-only))
* Content Source: [docs/azureblob/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/azureblob/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@Floriszz - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
