### ISSUE TITLE
OpenAPI 2.0 support not complete. 

### ISSUE THREAD

**Issue by Hjaf** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#302]
It seems that some parts of the OpenAPI 2.0 specification is not supported as documented.
"allOf" operator (and possibly others) produce errors. 

[The issue has been discussed some time ago (issue is reproduced and acknowledged by Microsoft)](https://powerusers.microsoft.com/t5/Building-Power-Apps/Missing-Properties-in-Collection-when-calling-custom-REST-API/m-p/613574/highlight/true#M193578)

[Version 2.0 specification](https://swagger.io/specification/v2/)
> Swagger allows combining and extending model definitions using the allOf property of JSON Schema, in effect offering model composition. allOf takes in an array of object definitions that are validated independently but together compose a single object.

Please mention the lack of support in the documentation until full OpenAPI 2.0 support is present.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9659a345-1116-5020-4300-386f3a591c2e
* Version Independent ID: e2a3861f-d3d5-f542-28db-1897d4c7feb0
* Content: [Create a custom connector from an OpenAPI definition](https://docs.microsoft.com/en-us/connectors/custom-connectors/define-openapi-definition)
* Content Source: [docs/custom-connectors/define-openapi-definition.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/define-openapi-definition.md)
* Service: **connectors**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by Hjaf** [comment]
Any update on this matter? It would be useful to have a list of the known limitations in the documentation and/or possible workarounds

**Comment by v-aangie** [comment]
@Hjaf - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
