### ISSUE TITLE
Please add PowerApps to the Firewall rules issues as well - not listed

### ISSUE THREAD

**Issue by gmndrg** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#304]
The documentation states: Logic apps can't directly access storage accounts that are behind firewalls if they're both in the same region. As a workaround, you can have your logic apps and storage account in different regions. For more information about enabling access from Azure Logic Apps to storage accounts behind firewalls, see the Access storage accounts behind firewalls.

Please add PowerApps to the firewall enabled (that won't work with storage account in the same region) since routed through internal IPs in Azure.

The same applies for PowerApps because they use a connector and this causes confusion since that is not clear enough from the PowerApps blogs to connect to Azure Storage: https://powerapps.microsoft.com/en-us/blog/upload-files-from-powerapps-using-the-azure-blob-storage-connector/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4a1ef15-eee8-e31f-e05d-34ae84216545
* Version Independent ID: 01cf0d74-3e50-c6c9-fe0d-7d639886318c
* Content: [Azure Blob Storage - Connectors](https://docs.microsoft.com/en-us/connectors/azureblob/)
* Content Source: [docs/azureblob/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/azureblob/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@gmndrg - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
