### ISSUE TITLE
All good but how to get Flow's description

### ISSUE THREAD

**Issue by kabiraaj** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#305]
Hello,
There should be an easy way to get my flow's description. Why isn't a direct property? But everything else is. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0624dd98-0950-674d-ae2e-aef1f0de9188
* Version Independent ID: 7f2dd0dd-fdf3-7e7c-cd79-bd45a606b6a1
* Content: [Power Automate Management - Connectors](https://docs.microsoft.com/en-us/connectors/flowmanagement/#list-my-flows)
* Content Source: [docs/flowmanagement/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/flowmanagement/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@kabiraaj  - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
