### ISSUE TITLE
Power Apps for Admins connector is not for "SharepointFormApp"

### ISSUE THREAD

**Issue by DavidPaf** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#307]
When running this connector's actions in PowerShell or Power Automate flow, you will get the error:

![image](https://user-images.githubusercontent.com/61499598/113809590-ac7fad00-9792-11eb-924f-bc03b43d8ba4.png)

{
  "error": {
    "code": "NoPermissionsForEmbeddedApplications",
    "message": "No permission to the 'SharepointFormApp' application that has ID = 'c398e6f3-209e-49bd-a6a1-3de38bb62c38'."
  }
}

This is expected behavior since the connector is not supported for SharepointFormApp (Customization Form)

The documents should have note about the applicable PowerApps Name is not SharePoint Form App

Document: https://docs.microsoft.com/en-us/connectors/powerappsforadmins/#actions

**Comment by v-aangie** [comment]
@DavidPaf - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
