### ISSUE TITLE
Where would the weather alerts be?

### ISSUE THREAD

**Issue by programmin1** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#309]
Where is the weather alert object? Eg "Freeze - Warning from 4/9/2021 2:00:00 AM to 4/9/2021 9:00:00 AM" ??

If it could give url examples, like a sandbox environment that would be great.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bbeba7f-5c07-3fa6-2d19-d973fb3be68c
* Version Independent ID: 30c3272f-550b-66da-4554-baffe0185e61
* Content: [MSN Weather - Connectors](https://docs.microsoft.com/en-us/connectors/msnweather/#get-current-weather)
* Content Source: [docs/MsnWeather/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/MsnWeather/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@programmin1 - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
