### ISSUE TITLE
Guide on how to configure the BC on-prem connector for Power Apps

### ISSUE THREAD

**Issue by businessuser123** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#31]
I thought the documentation above was too comprehensive. Therefore, I wrote a guide on how to configure the on-prem connector for Power Apps: https://ruudvg.com/2020/03/22/connecting-power-apps-to-business-central-on-premises-data/. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f4d9705-254f-c3ee-88c1-a483aa280a51
* Version Independent ID: 33d3527e-bc1b-ea89-79e5-c40efcdd9f5b
* Content: [Business Central (on-premises) - Connectors](https://docs.microsoft.com/en-us/connectors/dynamicssmbonprem/?source=docs#feedback)
* Content Source: [docs/dynamicssmbonprem/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/dynamicssmbonprem/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment]
Thank you for your feedback - I will close the issue as there is no error in the current documentation, however this issue will remain public for anyone running into issues.
