### ISSUE TITLE
GetOnChangeItems also triggered when creating new item with attachment from ModernUI

### ISSUE THREAD

**Issue by VinceRun** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#311]
[Enter feedback here]
The text for GetOnChangeItems is misleading. The text states "not when it is created". Yet we have some scenarios where the event is triggered when the user creates a new items with an attachment. (In ModernUI, create a new item with an attachement.) SPO considers "linking" the attachement property as an item modification. So we should clarify this scenario. My suggestion is something like:
"Note: the item creation UI can also update the item, for example when adding an attachment. In this specific scenario, this event will rightfully be triggered when setting the attachment property on the newly created item".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69a01872-3062-4100-f807-7d43e8111e9f
* Version Independent ID: 48560378-76ed-cb42-e816-894179e1f16d
* Content: [SharePoint - Connectors](https://docs.microsoft.com/en-us/connectors/sharepointonline/#when-an-item-or-a-file-is-modified)
* Content Source: [docs/sharepointonline/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/sharepointonline/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@VinceRun - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
