### ISSUE TITLE
FLOW: Stripe Connectors use a deprecated API

### ISSUE THREAD

**Issue by GuillaumeLeNost** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#312]
[Tapez vos commentaires ici]

Stripe Orders API is deprecated.
cf. https://stripe.com/docs/orders
Time to update these connectors !

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: e2881750-f169-d512-3d0f-830421995165
* Version Independent ID: d9be1f6a-8cbc-6cae-a894-df8e368027cf
* Content: [Stripe - Connectors](https://docs.microsoft.com/fr-fr/connectors/stripe/#when-a-charge-is-added)
* Content Source: [docs/Stripe/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Stripe/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@GuillaumeLeNost - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
