### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by saeidjoker** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#313]
Search for "Cloumdersive" in the page and you'll see the typo in the first table in front of Name column

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 575a0ff8-59a7-b48f-08f0-94251ef77af9
* Version Independent ID: 1d58d3d0-7d63-c587-f266-2f434ee723a5
* Content: [Cloudmersive NLP - Connectors](https://docs.microsoft.com/en-us/connectors/cloudmersivenlp/)
* Content Source: [docs/cloudmersivenlp/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/cloudmersivenlp/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@saeidjoker — Thank you for your feedback. The type is fixed and will be live by end-of-day. Closing this issue.

**Comment by v-aangie** [comment]
miriver does not exist so I self-assigned.

**Comment by rootsmusic** [comment]
Yes @v-aangie, @miriver seems to have abandoned this repo.  Can his open tickets be reassigned?
