### ISSUE TITLE
Power Automate and Power Apps logos are outdated

### ISSUE THREAD

**Issue by cimaja** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#314]
Both icons for Power Apps and Power Automate are outdated and should be updated to match the new product logos.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05311999-5cc3-eb54-779a-5340392b6437
* Version Independent ID: f6958b1c-6fc9-fd34-1535-eef6e36ef793
* Content: [Connectors Overview](https://docs.microsoft.com/en-us/connectors/connectors)
* Content Source: [docs/connectors.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/connectors.md)
* Service: **connectors**
* GitHub Login: @asavaritayal
* Microsoft Alias: **kvivek**

**Comment by KumarVivek** [comment]
Resolved
