### ISSUE TITLE
Power Apps and Power Automate logos are outdated

### ISSUE THREAD

**Issue by cimaja** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#315]
Power Apps and Power Automate logos inside the first image are outdated. We should update it to show the latest product brand logos.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f873de3b-82f2-8cbc-0de3-6dbdc968b9fa
* Version Independent ID: ca3ccf84-5de8-ef66-9bda-b804404b5085
* Content: [Custom connectors overview](https://docs.microsoft.com/en-us/connectors/custom-connectors/)
* Content Source: [docs/custom-connectors/index.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/index.md)
* Service: **connectors**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by v-aangie** [comment]
Logos will be updated soon.

**Comment by v-aangie** [comment]
@cimaja - Thanks for your feedback. We have updated the docs to change the logos in https://docs.microsoft.com/en-us/connectors/custom-connectors/, and the updated content is live. Closing this issue.
