### ISSUE TITLE
Prerequisites for Customer Voice connector?

### ISSUE THREAD

**Issue by Craig-Humphrey** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#316]
Could you please document the prerequisites for this connector?
In particular, it appears to need some form of admin access (it doesn't say what admin role) to actually install the connector for the first time.

Error message:
Need admin approval
CustomerVoiceFlowApp
CustomerVoiceFlowApp needs permission to access resources in your organization that only an admin can grant. Please ask an admin to grant permission to this app before you can use it.

Thanks
Craig

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a5226d0-b7e1-1691-6a3d-34881de58503
* Version Independent ID: e254de35-95a2-00c7-6d09-5e76e270722b
* Content: [Dynamics 365 Customer Voice - Connectors](https://docs.microsoft.com/en-us/connectors/microsoftformspro/)
* Content Source: [docs/microsoftformspro/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/microsoftformspro/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@Craig-Humphrey - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
