### ISSUE TITLE
Define Link type options

### ISSUE THREAD

**Issue by codepounder** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#317]
Documenting the "Link type" as "The type of link" doesn't really help anyone. List the options (View, Edit, and Direct) and tell me what each of those means. I think I understand View and Edit, but what is Direct? How are the others not direct? Does any user with the link have access to the file? 

This applies to "Create share link" and "Create share link by path" actions.

The same comment applies to the "Link scope" parameter as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 218578e7-a37c-9793-da70-8b9b4918402e
* Version Independent ID: ffcda025-b67a-6a02-50a5-e111f2c138d7
* Content: [OneDrive for Business - Connectors](https://docs.microsoft.com/en-us/connectors/onedriveforbusiness/#create-share-link)
* Content Source: [docs/onedriveforbusiness/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/onedriveforbusiness/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@codepounder - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
