### ISSUE TITLE
Should mention Outlook.com is intended for personal MSA only in the introduction + Add date of modified

### ISSUE THREAD

**Issue by anhdtv102** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#318]
[Enter feedback here]
I think this will reduce the confusion for the customers when they accidentally used Outlook.com for their business account in the past because they weren't informed that this is intended for personal MSA. Also they need to know when the documentation was last modified for transparency and clear awareness.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af6585d4-6a1a-df85-e3c8-b496e8c877ad
* Version Independent ID: f335e263-aaf9-914b-06a8-3cebd9593caa
* Content: [Outlook.com - Connectors](https://docs.microsoft.com/en-us/connectors/outlook/)
* Content Source: [docs/Outlook/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Outlook/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@anhdtv102 - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
