### ISSUE TITLE
Additional Trigger for DevOps connector

### ISSUE THREAD

**Issue by paulhasell** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#319]
Hi, it seems the obvious trigger that is missing is State Changed as Updated is too broad...you can't tell what has been changed.

Also, you need a work item type filter (multi-select) as you may only track (say) Bug & Story.

This would allow for extended sign-off scenarios as the work item moves through process as well as push notifications into Teams of significant events. To that end, it would also be useful if the URL returned was actually for the UI rather than the API (or both) so that you could click on it in Teams.

Many Regards

Paul Hasell

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1992475b-648a-9ebc-f165-abef6b5180a4
* Version Independent ID: da0b9096-309c-5d3f-11c2-0dba2c029c39
* Content: [Azure DevOps - Connectors](https://docs.microsoft.com/en-gb/connectors/visualstudioteamservices/#when-a-work-item-is-updated)
* Content Source: [docs/VisualStudioTeamServices/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/VisualStudioTeamServices/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@paulhasell - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
