### ISSUE TITLE
No documentation on the 'time zone' or 'start date' parameters for 'When a file is added or modified' trigger

### ISSUE THREAD

**Issue by riptusk331** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#320]
As the title says, there's not really much documentation on this. How exactly are these parameters used? If I want to run my trigger once a day at a specific time in my time zone that checks for new files, I don't really know how...it's not entirely clear and I didn't see anything on this reference for it. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1114b8b-0c42-b092-70dc-7a2b7c200376
* Version Independent ID: f0d4c89b-10fb-04f3-7aa9-042d27d59416
* Content: [SFTP - SSH - Connectors](https://docs.microsoft.com/en-us/connectors/sftpwithssh/)
* Content Source: [docs/sftpwithssh/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/sftpwithssh/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@riptusk331 - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
