### ISSUE TITLE
Connector is marked as Legacy - what should be used for LogicApps?

### ISSUE THREAD

**Issue by tims205** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#323]
The only connector to D365/Common Data Service/Dataverse from Logic Apps is now marked as 'Legacy' and does not have feature parity with the 'Microsoft Dataverse' connector available for PowerAutomate.

Which connector should be used for LogicApps, will there be updates to the Microsoft Dataverse (Legacy) connector that we have to use from LogicApps?

**Comment by v-aangie** [comment]
@tims205 - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
