### ISSUE TITLE
Type in documentation

### ISSUE THREAD

**Issue by biterbit** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#324]
There is a typo in the section referring the reader to in-depth information about the SharePoint connector: it says 'in-dept' instead of 'in-depth'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69a01872-3062-4100-f807-7d43e8111e9f
* Version Independent ID: 48560378-76ed-cb42-e816-894179e1f16d
* Content: [SharePoint - Connectors](https://docs.microsoft.com/en-us/connectors/sharepointonline/)
* Content Source: [docs/sharepointonline/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/sharepointonline/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@biterbit — Thank you for your feedback. The typo has been corrected, and will be live by end-of-day. Closing this issue.
