### ISSUE TITLE
Workaround for Known Issues and Limitations is not complete and hard to understand

### ISSUE THREAD

**Issue by chvollm** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#325]
I work with a customer who tries to use the connector. The issue listed, although a bit hidden, around the attached emails is really hard to understand. 

1. "An item attachments has a lot of properties." There is a typo. Also, is that the reason the attachment type is not supported?
2. Then it lists that you can workaround that these attachments are not supported by using the HTTP with Azure AD. Well, you first need to call the API to get ALL attachments, because you don't get the email attachments in the first place because the Outlook connector does not support it.
3. Then you need to call the API to get the complete attachment. 
4. And then of course you need to do the usual Parse JSON etc. stuff. Which can be expected from a developer, but then again we are targeting a citizen developer here, so might be worth mentioning or even giving a really good example. 
5. Then, after I started using the provided workaround, I get an email saying, that the HTTPD with Azure AD is not secure and I should stop using it! What good is a workaround, if I get told to not use it?

The customer just plainly gave up after reading the "workaround". So I sat down and figured it out myself, but even I (as a developer) needed some time. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc40a098-af8c-d8a9-4538-71d184efbe91
* Version Independent ID: 0ee8cf79-18e9-d923-607f-ef40cdd23e4d
* Content: [Office 365 Outlook - Connectors](https://docs.microsoft.com/en-us/connectors/office365/#known-issues-and-limitations)
* Content Source: [docs/office365/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/office365/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@chvollm - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
