### ISSUE TITLE
Salesforce Connector for Logic App

### ISSUE THREAD

**Issue by nssidhu** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#326]
https://docs.microsoft.com/en-us/connectors/salesforce/

I am using this connecter to get CDC changes from Salesforce using streaming API.

What puzzled me is why is it doing polling(Like i have to specify check every 1 minute) ?

Should it not subscribe to CDC Events an be called automatically whenever change happens in Salesforce instead of we polling Salesforce to check every few seconds.

How does it cover changes which i somehow missed, does it keep track of last time it retrieved the changes ?

**Comment by v-aangie** [comment]
@nssidhu - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
