### ISSUE TITLE
Image content inside "repeating action" in word template

### ISSUE THREAD

**Issue by joje1234** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#328]
Hi!

I have a .docx template i use in Power Automate, but when I try to put an 'image content' inside a 'repeating action' in the template, the image content does not appear in my Power Automate flow "Populate a microsoft word template"-node.
If I add a 'image content' outside of the repeating action, it appears in the flow.
In the documentation, I can't find anything about this being a limitation, so therefor I'm wondering if this is a bug.

Sincerely
Jørgen Jørgensen

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d39ce977-b1fc-d4be-3776-ad31a5b780ec
* Version Independent ID: 21c81572-7742-f033-cdc1-07c1090e9878
* Content: [Word Online (Business) - Connectors](https://docs.microsoft.com/en-us/connectors/wordonlinebusiness/#populate-a-microsoft-word-template)
* Content Source: [docs/wordonlinebusiness/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/wordonlinebusiness/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@joje1234 - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
