### ISSUE TITLE
Teams connector does not trigger with reply messages

### ISSUE THREAD

**Issue by textminer** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#33]
Hi,

I created a Logic Apps designed to connect with Teams for getting posts from a certain channel that then will be added into a spreadsheet:

![image](https://user-images.githubusercontent.com/38899601/77781364-32233580-7034-11ea-8e66-8a17f2765453.png)

My app only triggers when a new message is posted, but never when a message is replied.

my understanding reading:
https://docs.microsoft.com/en-us/connectors/teams/#when-a-new-channel-message-is-added
is that reply messages should appear since there is a replyToId (ID of the parent message of the thread).

Could you please review it?

Thanks.

**Comment by bezhan-msft** [comment]
From the documentation, I see this:

"This operation triggers when a new message is posted to a channel in a Team. Note that this trigger only fires when a root messages is added in the channel. Replies to an existing channel message will not result in the trigger event firing."

As such I believe this is expected functionality. Please reopen this issue if something has been missed.
