### ISSUE TITLE
OneNote document is get incorrect contents

### ISSUE THREAD

**Issue by Himeno-app** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#330]
[Enter feedback here]
OneDrive for business connector get incorrect content  from OneNote section on my OneDrive folder.
every contents is named "無題のセクション.one".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 218578e7-a37c-9793-da70-8b9b4918402e
* Version Independent ID: ffcda025-b67a-6a02-50a5-e111f2c138d7
* Content: [OneDrive for Business - Connectors](https://docs.microsoft.com/en-us/connectors/onedriveforbusiness/#triggers)
* Content Source: [docs/onedriveforbusiness/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/onedriveforbusiness/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@Himeno-app - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
