### ISSUE TITLE
Please get trigger on Shared file 

### ISSUE THREAD

**Issue by Himeno-app** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#331]
OneDrive for business connector's trigger can not get on Shared file modified.
Please it be able to specify shared url in it.
Thanks,

**Comment by v-aangie** [comment]
@Himeno-app - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
