### ISSUE TITLE
The Spatial Services connector is missing from the documentation

### ISSUE THREAD

**Issue by Erica0214** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#332]
Why the Spatial Services connector is not listed in the documentation?

https://docs.microsoft.com/en-us/connectors/connector-reference/

And, the link below from PPAC even navigates to a 404 Content not found page?

![image](https://user-images.githubusercontent.com/63276075/118094473-5b9e4c80-b401-11eb-9d94-31065ac21d4a.png)

![image](https://user-images.githubusercontent.com/63276075/118094538-71ac0d00-b401-11eb-9e45-8d2bc18d0649.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7741d635-bb14-0cbb-6ddc-d53108b59423
* Version Independent ID: c52d6e84-dc16-af82-9e1f-923659e25c54
* Content: [Connector reference overview](https://docs.microsoft.com/en-us/connectors/connector-reference/)
* Content Source: [docs/connector-reference/index.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/connector-reference/index.md)
* Service: **connectors**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by v-aangie** [comment]
@Erica0214 - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
