### ISSUE TITLE
Graph Security API deprecated

### ISSUE THREAD

**Issue by rootsmusic** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#333]
Power Query has deprecated its [connector to MS Graph Security](https://docs.microsoft.com/en-us/power-query/connectors/microsoftgraphsecurity#deprecation) due to the API ending support.  In the chart for [connectors in Power Query](https://docs.microsoft.com/en-us/power-query/connectors/#letter-m), Power Apps has also deprecated its connector to MS Graph Security.  Should this content be edited as "deprecated"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cca6694-d045-e34e-f17d-0cc7cf6fc333
* Version Independent ID: 136fce77-3988-0500-4aa5-a2e7197cb99e
* Content: [Microsoft Graph Security - Connectors](https://docs.microsoft.com/en-us/connectors/microsoftgraphsecurity/)
* Content Source: [docs/microsoftgraphsecurity/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/microsoftgraphsecurity/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@rootsmusic - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
