### ISSUE TITLE
Add all available options to optional keys in GetRoute function

### ISSUE THREAD

**Issue by anotherRedbeard** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#336]
[Enter feedback here]
Hi there!

It would be really helpful to know all the available options to pass into the GetRoute function.  For example, the docs list the defaults for all the optional keys, but it doesn't list all the possibilities.  Is that something you could add?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ceeb123-8398-c312-617e-0c40cc85cd05
* Version Independent ID: 4f59f3b8-b4df-bb22-d0cc-6c5bac66abf2
* Content: [Bing Maps - Connectors](https://docs.microsoft.com/en-us/connectors/bingmaps/)
* Content Source: [docs/BingMaps/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/BingMaps/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@anotherRedbeard - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
