### ISSUE TITLE
Listening to Salesforce CDC

### ISSUE THREAD

**Issue by nssidhu** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#339]
Is there a way to listen for Salesforce CDC changes like INSERT/UPDATE/DELETE/UNDELETE and get all columns for an object?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1edb85cd-28f3-bc48-8ba9-bebc6382ae56
* Version Independent ID: d634090e-3bc4-631e-9493-9be296ca0194
* Content: [Salesforce - Connectors](https://docs.microsoft.com/en-us/connectors/salesforce/)
* Content Source: [docs/Salesforce/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Salesforce/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@nssidhu - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
