### ISSUE TITLE
Azure Table Storage: Get Entity does not return the required column

### ISSUE THREAD

**Issue by rsganta** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#34]
Hi,
I tried to use Azure table storage connector in Power automate to retrieve a single column in the give table. I used syntax as Column, columnname  e.g. Column, Firstname.  It always returns some unique id rather than column.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe88d2b3-07cd-2c33-c835-4aec5f4b3473
* Version Independent ID: 2958cf7f-3c44-4f6f-0656-4aab4c8a8203
* Content: [Azure Table Storage - Connectors](https://docs.microsoft.com/en-us/connectors/azuretables/)
* Content Source: [docs/azuretables/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/azuretables/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment]
Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) or to the connector-specific support contact (if applicable).
