### ISSUE TITLE
Postman v1 export

### ISSUE THREAD

**Issue by biterbit** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#341]
The current version of the Postman app does not provide an option for export in v1 format so it is not possible to follow these instructions.

![Screenshot 2021-05-27 153127](https://user-images.githubusercontent.com/50102389/119844789-a4293000-bf00-11eb-8bf7-b89ec1e95d6b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a54d3a6-8cc5-37c2-a37e-b46054d22a73
* Version Independent ID: ae119da7-b9cc-e6eb-3dac-8ba8ac704ccd
* Content: [Create a Postman collection for a custom connector](https://docs.microsoft.com/en-us/connectors/custom-connectors/create-postman-collection)
* Content Source: [docs/custom-connectors/create-postman-collection.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/create-postman-collection.md)
* Service: **connectors**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by natalie-pienkowska** [comment]
Thank you for your feedback! We are happy to announce that we will begin supporting Postman V2 in the next few weeks :)
