### ISSUE TITLE
Connector reference pages show icon as wide rectangle instead of square

### ISSUE THREAD

**Issue by dtinikko** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#342]
![Screen Shot 2021-05-27 at 12 35 19 PM](https://user-images.githubusercontent.com/60011711/119863849-03c71180-bee8-11eb-899d-e9ff58dd4d9f.png)
![Screen Shot 2021-05-27 at 12 37 26 PM](https://user-images.githubusercontent.com/60011711/119864110-4e488e00-bee8-11eb-86f5-0d22a3c1bff9.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc40a098-af8c-d8a9-4538-71d184efbe91
* Version Independent ID: 0ee8cf79-18e9-d923-607f-ef40cdd23e4d
* Content: [Office 365 Outlook - Connectors](https://docs.microsoft.com/en-us/connectors/office365/)
* Content Source: [docs/office365/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/office365/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@dtinikko - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
