### ISSUE TITLE
Postman only gives the option to export as v2 or v2.1, how can openapi3 be imported?

### ISSUE THREAD

**Issue by dhardie** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#343]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a54d3a6-8cc5-37c2-a37e-b46054d22a73
* Version Independent ID: ae119da7-b9cc-e6eb-3dac-8ba8ac704ccd
* Content: [Create a Postman collection for a custom connector](https://docs.microsoft.com/en-us/connectors/custom-connectors/create-postman-collection)
* Content Source: [docs/custom-connectors/create-postman-collection.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/create-postman-collection.md)
* Service: **connectors**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by v-aangie** [comment]
@dhardie - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
