### ISSUE TITLE
Add a video duration snippet to the Youtube Connector

### ISSUE THREAD

**Issue by smelfra** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#346]
I use the Youtube connector to be notified by mail when a new video is posted on a subscribed channel and it would be nice to know the length of the video without having to visit its youtube page.
Regards,

**Comment by v-aangie** [comment]
@smelfra - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
