### ISSUE TITLE
Reference to V3 trigger should be V2

### ISSUE THREAD

**Issue by luxaflow** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#348]
<img width="809" alt="Screenshot 2021-06-04 at 08 37 12" src="https://user-images.githubusercontent.com/34321224/120757094-63d53d80-c510-11eb-9190-e0eb197b2ca0.png">

As shown in  the screenshot, there seems to be a reference to a V3 Connector in the docuemtation, where it seems it should be reference to the V2 Connector.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca6193ac-2539-73fb-27a8-134722eac6ac
* Version Independent ID: c9a83b37-0105-cf97-d5b9-ad20a4420986
* Content: [Office 365 Outlook - Connectors](https://docs.microsoft.com/en-us/connectors/office365connector/)
* Content Source: [docs/Office365Connector/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Office365Connector/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@luxaflow - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
