### ISSUE TITLE
No mention to need to re-submitting security details of custom connector upon solution import

### ISSUE THREAD

**Issue by manuelpsnunesmsft** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#351]
Upon the export / import of a custom connector in a solution, there is no reference to the need of re-submitting the security details of the custom connector. No mention also to whether this feature will be implemented or not.
This information is important because it sets expectations for the customer. Also because needing to input security details every time a custom connector is exported within a solution is time consuming.
For more information ping me, alias manuelnunes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3101e9c4-47d6-b564-ce7e-e52e868acd57
* Version Independent ID: 15ffa6d4-d303-c3fe-2d5d-9164afc40e59
* Content: [Create custom connectors in solutions (Preview)](https://docs.microsoft.com/en-us/connectors/custom-connectors/customconnectorssolutions)
* Content Source: [docs/custom-connectors/CustomConnectorsSolutions.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/CustomConnectorsSolutions.md)
* Service: **connectors**
* GitHub Login: @caburk
* Microsoft Alias: **caburk**

**Comment by v-aangie** [comment]
@manuelpsnunesmsft - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
