### ISSUE TITLE
Include the limitation that Excel files needs to be closed while creating/ playing Power Apps apps

### ISSUE THREAD

**Issue by xuyen1** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#352]
Hello team, 

Could you please include the limitation that Excel files needs to be closed while creating/ playing Power Apps app, otherwise it will return the error "Cannot write file to filesource. File is being locked." or Power Apps app will be blank. 

I know the document currently mentions some limits with locked Excel files but appreciate if the document can clearly states the Excel limit above for customers to be aware right away while building apps. 

Thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bbdfc54-809f-5f87-b707-0137aff397ea
* Version Independent ID: b035def8-7d52-5518-df0b-504c03236212
* Content: [Excel Online (OneDrive) - Connectors](https://docs.microsoft.com/en-us/connectors/excelonline/#known-issues-and-limitations)
* Content Source: [docs/excelonline/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/excelonline/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@xuyen1 - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
