### ISSUE TITLE
Custom connectors FAQ still mentions the old licensing plans

### ISSUE THREAD

**Issue by anmateusMSFT** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#353]
Instead of plan 1 and plan 2

![image](https://user-images.githubusercontent.com/79160351/121162007-6bb11c80-c845-11eb-9772-fac8cd3c2ac3.png)

should be..

Power Apps per user, Power Apps per app, Power Automate per user, Power Automate per flow (at least)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7a6439e-a119-688b-bb8a-b6fd0b8a37fb
* Version Independent ID: 8250980c-0bd3-6d89-fb0e-24f8ea6eafd8
* Content: [Custom connector FAQ for Azure Logic Apps, Power Automate, and Power Apps](https://docs.microsoft.com/en-us/connectors/custom-connectors/faq?source=docs#limits)
* Content Source: [docs/custom-connectors/faq.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/faq.md)
* Service: **connectors**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by v-aangie** [comment]
Thanks for your feedback. We have updated the docs to fix information about [Custom connector FAQ for Azure Logic Apps, Power Automate, and Power Apps](https://docs.microsoft.com/en-us/connectors/custom-connectors/faq?source=docs#limits), and the updated content is live. Closing this issue.
