### ISSUE TITLE
Power Automate: Outlook.com connector missing IsReminderOn attribute

### ISSUE THREAD

**Issue by apwood** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#354]
The Outlook 365 connector for Power Automate ("Get calendar view of items (v3)") includes the boolean attribute IsReminderOn. This allows a flow to read this attribute, for example in a condition to only process calendar events that have a reminder set.

However, this cannot be used for people with a personal Office 365 account. They have to use the Outlook.com connector instead  ("Get calendar view of items (v2)"). This v2 connector has a "bug" in that it is missing the attribute IsReminderOn.  Any expression addressing the value of this boolean attribute always evaluates to false, whether or not a reminder is set.

Please can this be fixed?

**Comment by v-aangie** [comment]
@apwood - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
