### ISSUE TITLE
Page on office 365 Users Connector Does Not Say If Connectors Supports SPN's

### ISSUE THREAD

**Issue by NPrice99** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#355]
The Page on Office 365 Users does not say if the Connector supports SPN's or not.
Service Accounts are considered by many to be insecure so SPNs are much the preferred way of connecting Logic App steps / PowerAutomate Flow steps to connections.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8635712-d5a2-e58a-301f-cf849f2cf2e4
* Version Independent ID: 4cfdd73e-f074-0446-2aee-2dd013a8b30f
* Content: [Office 365 Users - Connectors](https://docs.microsoft.com/en-us/connectors/office365users/)
* Content Source: [docs/office365users/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/office365users/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@NPrice99 - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
