### ISSUE TITLE
Azure Blade screenshots are out of date.

### ISSUE THREAD

**Issue by cchannon** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#357]
Azure screenshots for app registration management are out of date, across the board. This is mostly just an aesthetic difference, but in some places it matters. 

For example: When setting up the redirectURLs on the app registration, there is no left nav item for redirect URLs any more. YOu must go to Authentication --> Add a Platform --> Web (or other) then add a redirect URL there.

Updating these instructions will help users of custom connectors more readily follow your instructions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e584c228-236a-27fd-52b6-0910a7e67a13
* Version Independent ID: ec7aceaf-0855-b0c0-3468-9030e339a607
* Content: [Authenticate your API and connector with Azure Active Directory - Azure AD](https://docs.microsoft.com/en-us/connectors/custom-connectors/azure-active-directory-authentication)
* Content Source: [docs/custom-connectors/azure-active-directory-authentication.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/azure-active-directory-authentication.md)
* Service: **connectors**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by v-aangie** [comment]
@cchannon - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
