### ISSUE TITLE
Operations on this page do not match current powershell commands

### ISSUE THREAD

**Issue by binarytoshokan** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#358]
Operations on this page do not match current PowerShell commands.  For example, https://docs.microsoft.com/en-us/connectors/microsoftflowforadmins/#edit-flow-owner-role-as-admin incorrectly states the operation is edit-AdminFlowOwnerRole.  Only Set-AdminFlowOwnerRole is currently available under PowerShell.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f99a610e-3726-b491-2da9-f6a73e6cb4e4
* Version Independent ID: c98a93ec-d598-a085-5d59-8fc47ad12dc0
* Content: [Power Automate for Admins - Connectors](https://docs.microsoft.com/en-us/connectors/microsoftflowforadmins/#edit-flow-owner-role-as-admin)
* Content Source: [docs/microsoftflowforadmins/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/microsoftflowforadmins/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@binarytoshokan - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
