### ISSUE TITLE
Bcc is being deprecated

### ISSUE THREAD

**Issue by Tovli** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#36]
Hi, 
Sendgrid are deprecating the Bcc option (https://sendgrid.com/docs/ui/account-and-settings/retired-mail-settings/)

Is there a plan to update this connector?
Can you reflect this deprecation in this doc? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 318526ef-736e-a42e-87df-2ae3f5b5a8a7
* Version Independent ID: 8333dcc0-24a0-ee5f-1be7-875ec575d806
* Content: [SendGrid - Connectors](https://docs.microsoft.com/en-us/connectors/sendgrid/)
* Content Source: [docs/SendGrid/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/SendGrid/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment]
Thank you for your feedback. This is now under review and no further action is required at this time.

**Comment by Tovli** [comment]
Hi,
I've talked with Sendgrid and it seems that the confusion was on my end. Their deprecating the Bcc feature at the account level but still respect the Bcc option in the Api call
sorry for the hassle
