### ISSUE TITLE
when "content conversion Html to Text" will be generally available? can we use this for production release?

### ISSUE THREAD

**Issue by RaviNuthakki** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#360]
when "content conversion Html to Text" will be generally available? can we use this for production release?
will this be a premium action post general availability?
or please provide me the right place to search for the same.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 413f88f9-2b3c-172b-a74a-a533fcd167de
* Version Independent ID: b9ee8f92-b5b8-f2a3-51e6-f93a7c913567
* Content: [Content Conversion - Connectors](https://docs.microsoft.com/en-us/connectors/conversionservice/)
* Content Source: [docs/conversionservice/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/conversionservice/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@RaviNuthakki - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
