### ISSUE TITLE
Provide option to hide deprecated actions

### ISSUE THREAD

**Issue by biterbit** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#361]
This page is very long and hard to navigate. The majority of the information contained in it refers to deprecated actions. Could the deprecated sections be hidden by default and an option be provided to show them; or could the page be split to show deprecated content separately to make the page easier to read and navigate for most users?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc40a098-af8c-d8a9-4538-71d184efbe91
* Version Independent ID: 0ee8cf79-18e9-d923-607f-ef40cdd23e4d
* Content: [Office 365 Outlook - Connectors](https://docs.microsoft.com/en-us/connectors/office365/#find-meeting-times-(v2))
* Content Source: [docs/office365/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/office365/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@biterbit - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
