### ISSUE TITLE
Planner shows as available in tenants and is listed as available on DoD

### ISSUE THREAD

**Issue by TurnerMarshall** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#363]
[Enter feedback here]
Per other documentation Planner is listed as available and has recently shown up in the tenants. Requesting documentation be updated to reflect that.
Says it isn't available:
https://docs.microsoft.com/en-us/connectors/planner/
Says it is available:
https://docs.microsoft.com/en-us/connectors/connector-reference/connector-reference-powerautomate-connectors#list-of-connectors

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24185ffe-d266-c113-9327-4e305c276697
* Version Independent ID: 98978ace-f736-e07a-bde3-9156cd815100
* Content: [Planner - Connectors](https://docs.microsoft.com/en-us/connectors/planner/)
* Content Source: [docs/Planner/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Planner/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@TurnerMarshall - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
