### ISSUE TITLE
Clarification on DOD supported Connectors

### ISSUE THREAD

**Issue by JoeAlanis** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#364]
Hello!

The table in this article mentions that SharePoint connector is available in DOD tenants, however when drilling down to the actual connector is advises that it's not available.

https://docs.microsoft.com/en-us/connectors/sharepointonline/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 570fb89c-0e1c-b66e-91db-1fb0baa12c41
* Version Independent ID: 26689b04-39d6-c776-2590-9eb24955adfd
* Content: [List of all Power Automate connectors](https://docs.microsoft.com/en-us/connectors/connector-reference/connector-reference-powerautomate-connectors?source=docs)
* Content Source: [docs/connector-reference/connector-reference-powerautomate-connectors.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/connector-reference/connector-reference-powerautomate-connectors.md)
* Service: **connectors**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by v-aangie** [comment]
@JoeAlanis - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
