### ISSUE TITLE
Two sections with different information for the same limit

### ISSUE THREAD

**Issue by anmateusMSFT** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#365]
There are two sections for the topic - throttling limits. This is misleading.

![image](https://user-images.githubusercontent.com/79160351/123065870-75bb4980-d407-11eb-8115-413b24771387.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59e25400-ea5a-a77a-65e3-f5f7bd7b17a9
* Version Independent ID: 15fb9fda-6420-5f6e-1a4e-74997a5d7dfb
* Content: [Mail - Connectors](https://docs.microsoft.com/en-us/connectors/sendmail/?source=docs)
* Content Source: [docs/SendMail/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/SendMail/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@anmateusMSFT - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
