### ISSUE TITLE
Azure Tables Power Apps connector

### ISSUE THREAD

**Issue by cwanja** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#366]
So is it still true that Azure Tables do not have a Power App connector? Because I can see one in my Power App environment today:
![image](https://user-images.githubusercontent.com/54645561/123141314-e0777f80-d41d-11eb-9de1-7676a11c7159.png)

If so, I would suggest updating the top of this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe88d2b3-07cd-2c33-c835-4aec5f4b3473
* Version Independent ID: 2958cf7f-3c44-4f6f-0656-4aab4c8a8203
* Content: [Azure Table Storage - Connectors](https://docs.microsoft.com/en-us/connectors/azuretables/)
* Content Source: [docs/azuretables/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/azuretables/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@cwanja - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
