### ISSUE TITLE
Azure Monitor Logic App connector: specify target via resourceId string

### ISSUE THREAD

**Issue by fgheysels** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#367]
The Azure Monitor Logic App connector which allows you to execute a KQL query on AppInsights or Log Analytics opens a lot of possibilities.
However, it is a bit cumbersome that the only possibility to specify the resource you're targetting to execute the query against, is via multiple properties (subscriptionId, resourceType, etc.... ).

It would be a nice addition if it was also possible to specify the target resource via an resource-id string, like `/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/microsoft.insights/components/{appinsightsname}`

Why ?
Because, when you create a Logic App that is triggered when an Azure Monitor alert is fired, you receive this information and the query 'as is' in the alert-context.

An excerpt from such a alert body:

```json
"data": {
  "essentials": {
    "alertId": "....",
   ....
   "alertTargetIDs": [
        "/subscriptions/{redacted}/resourcegroups/{resourcegroupName}/providers/microsoft.insights/components/{appInsightsName}"
                ],
   ...
   "essentialsVersion": "1.0",
    "alertContextVersion": "1.0"
 },
"alertContext": {
    "properties": null,
    "conditionType": "LogQueryCriteria",
    "condition": {
        "windowSize": "PT10M",
           "allOf": [
           {
               "searchQuery": "customEvents\n| where name == \"VesselTelemetryStopped\"\n| project LastTelemetryReceivedAt = customDimensions[\"LastTelemetryReceivedTimestamp\"], VesselId = customDimensions[\"VesselId\"], timestamp\n",
```

So, that would make it super easy to use that information (`alertTargetId` + `searchQuery`) to execute the query and include the query-results in the message that we're posting on a Teams channel for instance.

We've a Logic App which does this already, but it's only working with alert-rules that have been created using version `2018-04-16` of the scheduledQueryRules API.  (Alerts that are created with that version include the search-results in the request that is sent to the webhook, so we can directly retrieve them, however, with later versions of the API, the search-results are no longer included).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0961c18-27ca-5465-7c78-bf28fc383c83
* Version Independent ID: 6ac323e2-362a-e5f2-421d-c0d35529e0e3
* Content: [Azure Monitor Logs - Connectors](https://docs.microsoft.com/en-us/connectors/azuremonitorlogs/)
* Content Source: [docs/azuremonitorlogs/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/azuremonitorlogs/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@fgheysels - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
