### ISSUE TITLE
Postman version out of date

### ISSUE THREAD

**Issue by Arcalight** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#368]
Postman has deprecated v1 and you can only export collections using v2 and v2.1. This prevents you from importing a Postman collection to a custom connector using this process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd4ed455-8e17-4699-da0f-c7dc01d72c12
* Version Independent ID: a1662685-6c0b-d920-f6d8-929b176fbe6c
* Content: [Create a custom connector from a Postman collection](https://docs.microsoft.com/en-us/connectors/custom-connectors/define-postman-collection)
* Content Source: [docs/custom-connectors/define-postman-collection.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/define-postman-collection.md)
* Service: **connectors**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by natalie-pienkowska** [comment]
Thank you for your feedback! We are happy to announce that we will begin supporting Postman V2 in the next few weeks :)
