### ISSUE TITLE
Postman v1 deprecated

### ISSUE THREAD

**Issue by Arcalight** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#369]
Postman v1 is no longer available for exporting collections from Postman; only v2 and v2.1 are available now. Information is out of date.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a54d3a6-8cc5-37c2-a37e-b46054d22a73
* Version Independent ID: ae119da7-b9cc-e6eb-3dac-8ba8ac704ccd
* Content: [Create a Postman collection for a custom connector](https://docs.microsoft.com/en-us/connectors/custom-connectors/create-postman-collection)
* Content Source: [docs/custom-connectors/create-postman-collection.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/create-postman-collection.md)
* Service: **connectors**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by natalie-pienkowska** [comment]
Thank you for your feedback! We are happy to announce that we will be supporting Postman V2 in the next few weeks :)
