### ISSUE TITLE
coma instead of comma

### ISSUE THREAD

**Issue by JeroenTournierSubotic** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#37]
coma instead of comma

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8635712-d5a2-e58a-301f-cf849f2cf2e4
* Version Independent ID: 4cfdd73e-f074-0446-2aee-2dd013a8b30f
* Content: [Office 365 Users - Connectors](https://docs.microsoft.com/en-us/connectors/office365users/)
* Content Source: [docs/office365users/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/office365users/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment]
Thank you for your feedback. This is now under review and no further action is required at this time.

**Comment by v-aangie** [comment]
@JeroenTournierSubotic - Thank you for your feedback. The type has been corrected and will be live later today. Closing the issue.
