### ISSUE TITLE
Excel Business connector not available when importing package into PowerApps

### ISSUE THREAD

**Issue by SnehalTajave** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#370]
when user trying to import the package and try to add Excel business connector. It is not available.
![image](https://user-images.githubusercontent.com/86424617/123292689-eca03180-d530-11eb-8a41-81604bad0c6e.png)

**Comment by v-aangie** [comment]
@SnehalTajave - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
