### ISSUE TITLE
Get Plan Details (Preview) Not returning all 25 Labels

### ISSUE THREAD

**Issue by SthanDust** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#371]
Using Power Automate in the GCC and this function only returns the 6 labels, even when we've added more than 6.  Get Task Details does return all the labels for a task, but not the description of the label.

**Comment by v-aangie** [comment]
@SthanDust - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
