### ISSUE TITLE
Missing known issue regarding old and new API on JIRA site

### ISSUE THREAD

**Issue by michael-heidweiller** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#372]
There are two API versions running on JIRA.

* https://**instance**.atlassian.net/
and 
* https://**instance**.atlassian.net

These have major differences in how the GetProjects works, and with that the Create Issue (V2). With slash (/) gives all projects, while without slash only shows a few projects.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76d2c23e-c66c-3e66-f61d-681c4327e461
* Version Independent ID: 0c4a4d9e-d055-d56e-6b48-c70cb753aa60
* Content: [JIRA - Connectors](https://docs.microsoft.com/en-us/connectors/jira/)
* Content Source: [docs/JIRA/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/JIRA/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@michael-heidweiller - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
