### ISSUE TITLE
Possible Connector update to reference? 

### ISSUE THREAD

**Issue by almertes** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#373]
Blue Prism RPA offers a Power Platform connector. I am unable to find it when searching our Connector list here, but can via the Azure Marketplace.   Just thinking we should/may want to include it in the Non-MS Connector list via the Power Platform reference here  https://docs.microsoft.com/en-us/connectors/connector-reference/ ?

the Azure Marketplace: Blue Prism Intelligent Automation (microsoft.com)
https://azuremarketplace.microsoft.com/en-us/marketplace/apps/blueprismlimited-4827145.blueprismweb?tab=Overview

Thank you! 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7741d635-bb14-0cbb-6ddc-d53108b59423
* Version Independent ID: c52d6e84-dc16-af82-9e1f-923659e25c54
* Content: [Connector reference overview](https://docs.microsoft.com/en-us/connectors/connector-reference/)
* Content Source: [docs/connector-reference/index.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/connector-reference/index.md)
* Service: **connectors**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by v-aangie** [comment]
@almertes - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
