### ISSUE TITLE
Container parameters are only visible when a specific group of parameters are added

### ISSUE THREAD

**Issue by BryanSoltis** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#374]
For many of the available parameters, users must add an entire parameter group for them to be visible.

Example:
When using an Azure Container Registry for the image, the *ContainerGroup Image Registries* parameter needs to be added to the connector in order to specify the server, username, and password parameters. 

The documentation should include a note for the parameters that are only available once a specific "group" parameter option is selected. Additionally, specifying the "group" that is required for the parameter to be available would be very beneficial.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fdac925-5f7a-fad6-036e-1a9d92f23fef
* Version Independent ID: 98799be2-767f-6dbf-600e-b68c1e4d935e
* Content: [Azure Container Instance - Connectors](https://docs.microsoft.com/en-us/connectors/aci/#create-or-update-a-container-group)
* Content Source: [docs/aci/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/aci/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@BryanSoltis - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
