### ISSUE TITLE
Create a Chat action - Invalid OData type specified: "Microsoft.Teams.GraphSvc.aadUserConversationMember

### ISSUE THREAD

**Issue by expiscornovus** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#375]
Hi All,

I have been using the new Create a Chat action from Power Automate:
https://docs.microsoft.com/en-us/connectors/teams/#create-a-chat

It's has been working great and it is a nice addition to the Teams Connector. I used the action a couple of weeks ago and that flow was running fine.

However, since a couple of days I am getting this error in my demo tenant in the UK South region. Same flow action suddenly errored. Try creating a new flow with the create a chat action, same result. Tried using an Azure Object id instead of e-mail, same result. 

Also tried it with other tenants, same result. Now I am also seeing it being reported by other users on the Power Automate community:
https://powerusers.microsoft.com/t5/Building-Flows/Send-message-to-individual-users-on-teams-as-user-not-flow-bot/m-p/972574

Any ideas on what is causing this issue? Thanks for your help!

I am able to reproduce it with this input:
`{
    "host": {
        "connectionReferenceName": "shared_teams",
        "operationId": "CreateChat"
    },
    "parameters": {
        "item/members": "jane@contoso.onmicrosoft.com",
        "item/topic": "Test Title"
    }
}`

This is the output, a 400 with a invalid odata type error.
`{
    "statusCode": 400,
    "headers": {
        "Transfer-Encoding": "chunked",
        "Vary": "Accept-Encoding",
        "Strict-Transport-Security": "max-age=31536000",
        "request-id": "",
        "client-request-id": "",
        "x-ms-ags-diagnostic": "{\"ServerInfo\":{\"DataCenter\":\"UK South\",\"Slice\":\"E\",\"Ring\":\"3\",\"ScaleUnit\":\"001\",\"RoleInstance\":\"LN2PEPF00003B3D\"}}",
        "Timing-Allow-Origin": "*",
        "x-ms-apihub-cached-response": "false",
        "Date": "Tue, 06 Jul 2021 08:31:07 GMT",
        "Content-Type": "application/json",
        "Content-Length": "348"
    },
    "body": {
        "error": {
            "code": "BadRequest",
            "message": "Invalid OData type specified: \"Microsoft.Teams.GraphSvc.aadUserConversationMember\"",
            "innerError": {
                "date": "2021-07-06T08:31:08",
                "request-id": "",
                "client-request-id": ""
            }
        }
    }
}`

**Comment by FincyRosePhilip** [comment]
Hi , I was also getting the error, but i am a new user of Power automate flow. Usually when we create a group manually in teams, the group gets created only after the first ping, not just as we entered the mail ids and title. do this is getting the error?

**Comment by AntClay72** [comment]
Yeh I'm getting the same issue, tenant based in North Europe, it was working on 2nd July (last time it ran successfully), now failing with the same error as you've reported above.

**Comment by FincyRosePhilip** [comment]
Hello all, Create a chat will work , but the owners mail id must not included while creating the chat.like if i am not supposed to include my mailid .

**Comment by expiscornovus** [comment]
@FincyRosePhilip, I was aware of that limitation. But I think it is unrelated to this issue. In that scenario the error would be different:
_Duplicate chat members is specified in the request body._
https://powerusers.microsoft.com/t5/Building-Flows/Can-t-Create-a-Teams-Group-Chat-in-Flow/m-p/962923

But the good news is, it works again. Thanks for sharing! I am unable to reproduce the error anymore. Looks like it is fixed in the connector!
