### ISSUE TITLE
Delete Environment returns 404 - document as expected behaviour

### ISSUE THREAD

**Issue by manuelap-msft** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#376]
On the PowerShell cmdlet for deleting an environment, it is highlighted that this "This operation can take some time depending on how many resources are stored in the environment. If the operation returns a 404 NotFound, the environment was successfully deleted." see  https://docs.microsoft.com/en-us/powershell/module/microsoft.powerapps.administration.powershell/remove-adminpowerappenvironment?view=pa-ps-latest#description

The same is true for the action of the connector, so Delete Environment returns 404 when the environment was successfully deleted. Could this be highlighted here as a limitation / known issue or expected behaviour?

Thank you
Manuela 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23643230-6ac3-2db9-58fa-5cade62a3808
* Version Independent ID: 272a10c3-d672-f035-20a0-8a272cb93a81
* Content: [Power Platform for Admins - Connectors](https://docs.microsoft.com/en-us/connectors/powerplatformforadmins/)
* Content Source: [docs/powerplatformforadmins/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/powerplatformforadmins/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@manuelap-msft - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
