### ISSUE TITLE
Azure IP Ranges

### ISSUE THREAD

**Issue by ezaromb** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#377]
Document states as one of the pre-requisites: "The user must configure the SAS Intelligent Decisioning environment to allow calls coming from the IP Addresses described in Azure IP Ranges"

The list of Azure IP ranges mentioned in this document is enormous and requires a great deal of work to configure. Can you provide a more succinct list of the necessary IP ranges that need to be opened for this to work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 229f0900-e594-85d6-99f2-16a1cff571c7
* Version Independent ID: 4a17f80a-f099-342a-54e5-fd9ff54758ea
* Content: [SAS Decisioning - Connectors](https://docs.microsoft.com/en-us/connectors/sasdecisioning/)
* Content Source: [docs/sasdecisioning/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/sasdecisioning/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@ezaromb - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
