### ISSUE TITLE
Documentation Without Examples Is Not Too Helpful

### ISSUE THREAD

**Issue by klawrawkz** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#378]
why don't you provide some examples for creating a connection? It is not helpful to list a bunch of properties without giving concrete examples. Is there some other documentation where you show us how this stuff is supposed to work?

Thanks.

klaw

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ccaa582-2cd7-b1ab-f13d-6f7387ad38e8
* Version Independent ID: ddb977e0-030a-978a-7e21-44a1d955d6b7
* Content: [MQ - Connectors](https://docs.microsoft.com/en-us/connectors/mq/)
* Content Source: [docs/Mq/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Mq/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by natalie-pienkowska** [comment]
Thanks @klawrawkz for submitting this documentation idea :) We have added it to our backlog and will prioritize accordingly.
