### ISSUE TITLE
Incomplete/Incorrect information in CreateTeamsMeeting

### ISSUE THREAD

**Issue by Spamrancher** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#379]
Hi,

The information for "CreateTeamsMeeting" is incomplete. It skips from "End Time" to "Required Attendees", but the connector requires "isOnlineMeeing" and "onlineMeetingProvider". Thankfully the intellisense lets me know what the default values are, but it should be included in the documentation, right? Also, parts of the information appear to be wrong. The "Message" parameter says it's text, but it requires a record. "Start time" and "End time" parameters show a type of datetimes but also require the values to be wrapped in a record. (See http://powerappsguide.com/blog/post/using-the-teams-connector for an example)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb4ba692-98a2-2ec7-319b-d75b59d3fa50
* Version Independent ID: c24a9495-e4cb-28db-3657-ecf81005757b
* Content: [Microsoft Teams - Connectors](https://docs.microsoft.com/en-us/connectors/teams/#create-a-teams-meeting)
* Content Source: [docs/Teams/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Teams/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@Spamrancher - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
