### ISSUE TITLE
Getting an error on my org?

### ISSUE THREAD

**Issue by JohnDev66** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#380]
Hello:

I entered "blueprismdev3" as my org name which  is valid (see attachment, Org), but I am getting an error (see attachment, orgerror)
![Org](https://user-images.githubusercontent.com/87654648/126168359-00c6a1c6-d3f6-498a-8006-96cc9047a66f.PNG)
![OrgError](https://user-images.githubusercontent.com/87654648/126168360-898ce68d-9d4d-497b-a752-a242c4598f2b.png)
![Org](https://user-images.githubusercontent.com/87654648/126168373-c22f2bc6-e2e5-4625-8d92-db31d99f73b6.PNG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2294a2b5-f7af-95bf-5a38-4391dd90cdd6
* Version Independent ID: 4221f8bb-e548-5e5f-ce3a-b477d221a468
* Content: [Dynamics 365 (deprecated) - Connectors](https://docs.microsoft.com/en-us/connectors/dynamicscrmonline/#create-a-new-record-(deprecated))
* Content Source: [docs/dynamicscrmonline/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/dynamicscrmonline/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@JohnDev66 - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
