### ISSUE TITLE
Flows url is broken

### ISSUE THREAD

**Issue by Jebarson** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#384]
the flows.powerapps.com url isnt valid anymore. Please update the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dbf42aa-0909-54d4-e487-55c268d387ae
* Version Independent ID: 7b2d3208-3495-feca-5a2b-2529d7b00ec0
* Content: [Create a custom connector for a web API](https://docs.microsoft.com/en-us/connectors/custom-connectors/create-web-api-connector)
* Content Source: [docs/custom-connectors/create-web-api-connector.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/create-web-api-connector.md)
* Service: **connectors**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by v-aangie** [comment]
@Jebarson - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
