### ISSUE TITLE
GitHub Connector: Add/Invite User Trigger/Action

### ISSUE THREAD

**Issue by 3copelan** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#385]
Would love to see the GitHub Connect get some admin features, such as inviting/adding users to an org or repo.

Use case, create a Form for people requesting access, flow triggers approval email from manager, then adds user to the desired repo. Right now I'm looking at going REST route however if this was something added to the connector, would make life much easier.

Cheers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90cc63c5-330d-3be1-73c7-ef14c3531007
* Version Independent ID: 16bc26a2-2aee-7438-40b3-30732c7ed1f8
* Content: [GitHub - Connectors](https://docs.microsoft.com/en-us/connectors/github/#feedback)
* Content Source: [docs/GitHub/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/GitHub/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@3copelan - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
