### ISSUE TITLE
Need to add information about companies using SSO

### ISSUE THREAD

**Issue by lopezg21** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#386]
So it seems like the information on how to log in to ServiceNow in companies that use SSO (like mine) is not here. I tried using my company's username and password but of course that didn't work and I was hoping to find information here on how to pass on those credentials to the the connector.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00a0a61d-f2fc-aa31-042b-0b472c8bff1c
* Version Independent ID: 1650d41c-0ec7-d8b4-a98b-5f96bc8b0bdb
* Content: [ServiceNow - Connectors](https://docs.microsoft.com/en-us/connectors/service-now/)
* Content Source: [docs/service-now/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/service-now/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by televisi** [comment]
Agree, it would be nice to be able to use Power Automate ServiceNow connector with the O365 SSO setting.

**Comment by v-aangie** [comment]
@lopezg21 Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
