### ISSUE TITLE
Get Route (preview) action returns body fields

### ISSUE THREAD

**Issue by expiscornovus** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#387]
Hi,

I have started using the Bing Maps - Get Route (preview) action.

When using fields like TravelDistance I noticed that the output was empty. The body of the response has a TravelDistance field value (in my test 1827.112 km, for a route from Seattle to LA). After some troubleshooting I noticed that the dynamic content field points to body/travelDistance:
`outputs('Get_route')?['body/travelDistance']`

Are those fields correct in the connector? It looks like those fields are pointing to the wrong part of the json schema.

My workaround btw is to use this expression instead:
`outputs('Get_route')?['body']['resourceSets'][0]['resources'][0]['travelDistance']`

**Comment by natalie-pienkowska** [comment]
Hi @expiscornovus! Thank you for raising this question. This sounds like it's product support related feedback.  Please submit this post to the forum: https://powerusers.microsoft.com/t5/Connecting-To-Data/bd-p/ConnectingToData

**Comment by expiscornovus** [comment]
Hi @natalie-pienkowska,

Thank you for your reply. That is actually were I spotted the error, on the Power Users forum. 

Sorry for posting it in the wrong area, appreciate your help :)
