### ISSUE TITLE
Chart Type definitions missing

### ISSUE THREAD

**Issue by stevewithey** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#389]
There isn't a link through to any documentation stating what the options for the chartType parameter are.. I wasn't able to find a good resource online either..

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41b5b46a-c9a9-c66a-2575-5a99fd144a27
* Version Independent ID: ee6a18cb-cdd5-cbdf-e953-6ea9bc5568f3
* Content: [Azure Application Insights - Connectors](https://docs.microsoft.com/en-gb/connectors/applicationinsights/#visualize-analytics-query)
* Content Source: [docs/ApplicationInsights/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/ApplicationInsights/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@stevewithey - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
