### ISSUE TITLE
Update Plivo brand icon

### ISSUE THREAD

**Issue by huzaif-plivo** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#391]
Hi Team,

The Plivo's brand icon on this page needs to be updated with the one attached along with this note.
![Plivo-Icon](https://user-images.githubusercontent.com/43034298/128454633-6bbee142-e0b1-4cef-ab15-464a191e486a.png)

Let us know if there is any other information required.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95547e3d-4914-2dac-3fa9-062756d86c6e
* Version Independent ID: 31830c88-7b2b-9190-4644-7defba10890e
* Content: [Plivo - Connectors](![Plivo-Icon](https://user-images.githubusercontent.com/43034298/128454601-e05f00cb-74eb-4f41-b955-4a0485ad608e.jpg))
* Content Source: [docs/plivo/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/plivo/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by natalie-pienkowska** [comment]
Hi @huzaif-plivo Thanks for your feedback :) The [Plivo connector](https://docs.microsoft.com/en-us/connectors/plivo/) is owned and maintained by the Plivo team, so I suggest reaching out to your internal dev team and having them update their icon through our certification process: https://docs.microsoft.com/en-us/connectors/custom-connectors/certification-updates
