### ISSUE TITLE
Documentation page refers to having "a Visual Studio Team Services account with API access enabled" but it's not clear how to enable API access

### ISSUE THREAD

**Issue by drk-mtr** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#392]
It would be useful to understand how to enable API access for the person trying to use the connector.

Thanks in advance for the help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1992475b-648a-9ebc-f165-abef6b5180a4
* Version Independent ID: da0b9096-309c-5d3f-11c2-0dba2c029c39
* Content: [Azure DevOps - Connectors](https://docs.microsoft.com/en-us/connectors/visualstudioteamservices/)
* Content Source: [docs/VisualStudioTeamServices/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/VisualStudioTeamServices/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@drk-mtr - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
