### ISSUE TITLE
Forwarding and transform script sample code error

### ISSUE THREAD

**Issue by matthewdevaney** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#393]
I found an error in the "Forwarding and transform script" code:

var newResult = new JObject
{
    ["wrapped"] = newResult,
};

It should be this instead.

var newResult = new JObject
{
    ["wrapped"] = result,
};

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0293dbc2-1f0f-ff7b-d155-536fdcbfbc9d
* Version Independent ID: 710f2fe8-ca11-2a2f-2faa-86749a42b55a
* Content: [Write code in a custom connector](https://docs.microsoft.com/en-us/connectors/custom-connectors/write-code)
* Content Source: [docs/custom-connectors/write-code.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/write-code.md)
* Service: **connectors**
* GitHub Login: @shgogna
* Microsoft Alias: **shgogna**

**Comment by natalie-pienkowska** [comment]
Thank you so much for providing this feedback :) Our team has addressed this and the changes will go live shortly.
