### ISSUE TITLE
"Reply to" Parameter in Sendgrid Logic App Connector

### ISSUE THREAD

**Issue by RharoLP** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#395]
Is there a way to enter the "Replyto" parameter using the Sengrid Logic App Connector?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 318526ef-736e-a42e-87df-2ae3f5b5a8a7
* Version Independent ID: 8333dcc0-24a0-ee5f-1be7-875ec575d806
* Content: [SendGrid - Connectors](https://docs.microsoft.com/en-us/connectors/sendgrid/)
* Content Source: [docs/SendGrid/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/SendGrid/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@RharoLP - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
