### ISSUE TITLE
Multiple authentications on a custom connector - oauthSetting secrets

### ISSUE THREAD

**Issue by dominicusmento** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#396]
Hi,

from the documentation it is clear that multiple oauth settings can be used. However it is unclear how to enter multiple secrets for them as authorization_code flow is used.

Command mentioned [here](https://docs.microsoft.com/en-us/connectors/custom-connectors/paconn-cli#update-an-existing-custom-connector) seems to be able to insert only one secret.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdb8f2bf-afba-b0c6-0dfd-2bef4ca31a30
* Version Independent ID: 4154610b-5543-42ee-cf81-ebb9313d06e6
* Content: [Multi-auth on custom connectors](https://docs.microsoft.com/en-us/connectors/custom-connectors/multi-auth)
* Content Source: [docs/custom-connectors/multi-auth.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/multi-auth.md)
* Service: **connectors**
* GitHub Login: @laborbol
* Microsoft Alias: **laborbol**

**Comment by v-aangie** [comment]
@dominicusmento - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
