### ISSUE TITLE
v1 is not supported by postman.

### ISSUE THREAD

**Issue by arashaga** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#397]
Postman does not support v1 anymore. What is the workaround?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a54d3a6-8cc5-37c2-a37e-b46054d22a73
* Version Independent ID: ae119da7-b9cc-e6eb-3dac-8ba8ac704ccd
* Content: [Create a Postman collection for a custom connector](https://docs.microsoft.com/en-us/connectors/custom-connectors/create-postman-collection)
* Content Source: [docs/custom-connectors/create-postman-collection.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/create-postman-collection.md)
* Service: **connectors**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by natalie-pienkowska** [comment]
Thanks for your feedback :) We are looking to add support for postman v2 in the next few weeks!
