### ISSUE TITLE
Add link regarding office scripts

### ISSUE THREAD

**Issue by MiyukiAmino** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#398]
[Enter feedback here]

Thank you for always updating the document, this page is one of most useful pages!
I want to add these links to this page.

Be able to use macro.
https://docs.microsoft.com/en-us/office/dev/scripts/testing/macros-power-automate
* connector doc says *.xlsx is only supported extension, but is *.xlsm supported?

limitation on office side
https://docs.microsoft.com/ja-jp/office/dev/scripts/testing/platform-limits#power-automate

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63dd2d5e-d90f-4654-c406-256e3e680e6d
* Version Independent ID: f2cd384b-2690-393d-3058-a363523f7d62
* Content: [Excel Online (Business) - Connectors](https://docs.microsoft.com/en-us/connectors/excelonlinebusiness/)
* Content Source: [docs/excelonlinebusiness/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/excelonlinebusiness/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@MiyukiAmino - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
