### ISSUE TITLE
Post a message (V3) - I am confusion

### ISSUE THREAD

**Issue by sparkitect** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#399]
When using the [Post a message (V3)](https://docs.microsoft.com/en-us/connectors/teams/?source=docs#post-a-message-(v3)-[deprecated]) action in a Flow, it displays as (Preview):
![image](https://user-images.githubusercontent.com/9206808/129365614-acb5a012-2c00-4eb3-8438-f6b271522cb7.png)

However, the documentation indicates it is [DEPRECATED]:
![image](https://user-images.githubusercontent.com/9206808/129365775-c5105a21-62e5-4376-b82b-c988186c7375.png)

So which is it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb4ba692-98a2-2ec7-319b-d75b59d3fa50
* Version Independent ID: c24a9495-e4cb-28db-3657-ecf81005757b
* Content: [Microsoft Teams - Connectors](https://docs.microsoft.com/en-us/connectors/teams/?source=docs#actions)
* Content Source: [docs/Teams/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Teams/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@sparkitect - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
