### ISSUE TITLE
Where to find after the "[DEPRECATED]" flag

### ISSUE THREAD

**Issue by v-tujita** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#4]
This page was helpful. 
I would like to know where the updated information is located after the "[DEPRECATED]" flag is attached. Where can I find the most up-to-date information. and why was it "[DEPRECATED]"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 402a2b5f-beb6-2370-3d36-d07fc52eff36
* Version Independent ID: 2409cbb0-5507-2348-fb90-8759d64c3715
* Content: [Azure Log Analytics - Connectors](https://docs.microsoft.com/en-us/connectors/azureloganalytics/#visualizeresults)
* Content Source: [docs/azureloganalytics/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/azureloganalytics/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment]
Thank you for your feedback.

We generally do not document reasons for deprecation and if there exists a newer version a link should be provided.

In this connector's case, it seems it was deprecated without a newer version being linked. We will investigate if there is a newer recommended connector or actions

**Comment by dougelliott** [comment]
Hey @v-tujita,

I wanted to let you know that I am engaging the connector owners to check in on your question. I will let you know once I hear more from them.

**Comment by dougelliott** [comment]
Hey @v-tujita - I heard back from the team and they've noted the feedback that you provided. They also offered forward the replacement connector that can be used, [Azure Monitor Logs](https://docs.microsoft.com/en-us/connectors/azuremonitorlogs/). We'll consider this item as closed since the team has noted the feedback. Thanks!
