### ISSUE TITLE
(Preview) and [DEPRECATED]

### ISSUE THREAD

**Issue by sparkitect** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#400]
What do (Preview) and [DEPRECATED] actually mean?

Should we not use (Preview) actions in our Production Flows, because they may change in the future, breaking our Flows?
Should we remove/replace [DEPRECATED] actions in our existing Flows so that they do not break if the Action is removed?
Documentation, definitions and quidance would be helpful...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb4ba692-98a2-2ec7-319b-d75b59d3fa50
* Version Independent ID: c24a9495-e4cb-28db-3657-ecf81005757b
* Content: [Microsoft Teams - Connectors](https://docs.microsoft.com/en-us/connectors/teams/?source=docs#post-a-message-(v3)-[deprecated])
* Content Source: [docs/Teams/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Teams/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by natalie-pienkowska** [comment]
Thank you, @sparkitect, for raising this issue as well as the previous issue. Our team is looking into this now.

**Comment by rootsmusic** [comment]
#287

**Comment by v-aangie** [comment]
@sparkitect - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.

**Comment by sparkitect** [comment]
So.....

What do (Preview) and [DEPRECATED] actually mean?

(the question stands unanswered; not sure why this was closed)
