### ISSUE TITLE
Typo "Github"→"GitHub"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#401]
https://docs.microsoft.com/en-us/connectors/github/
![connectors_github_e](https://user-images.githubusercontent.com/40815708/129473149-16964807-ed76-4d11-b9ae-c69c95bae9a3.png)

#PingMSFTDocs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90cc63c5-330d-3be1-73c7-ef14c3531007
* Version Independent ID: 16bc26a2-2aee-7438-40b3-30732c7ed1f8
* Content: [GitHub - Connectors](https://docs.microsoft.com/en-us/connectors/github/)
* Content Source: [docs/GitHub/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/GitHub/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by natalie-pienkowska** [comment]
Thank you, @hyoshioka0128, for raising this typo! We have added it to our documentation bug backlog and will prioritize accordingly.
