### ISSUE TITLE
Wrong description for end time

### ISSUE THREAD

**Issue by dcbrown16** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#402]
In the section below, the description needs to say "The end time", not "The start time." Start time is the row above this one.

<html>
<body>

Query End Time | additionalData.Query End Time UTC | string | The start time of the query used to decide if the alert should be triggered (Schedule Alert Only).
-- | -- | -- | --

</body>
</html>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 685e689b-8d6c-d138-955e-9d230889c542
* Version Independent ID: d026d398-9998-fef5-823c-2b3a9a9af251
* Content: [Azure Sentinel - Connectors](https://docs.microsoft.com/en-us/connectors/azuresentinel/)
* Content Source: [docs/azuresentinel/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/azuresentinel/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@dcbrown16 - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
