### ISSUE TITLE
Authorisation

### ISSUE THREAD

**Issue by RoboMikkel** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#403]
Hi

Could you specify what kinds of permissions these functions use?

Best regards Mikkel
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edd81673-4c78-5dfe-b2ae-fd94ea351b44
* Version Independent ID: fca7ea7a-8190-a246-c1bd-a9308596d3b9
* Content: [Azure VM - Connectors](https://docs.microsoft.com/en-gb/connectors/azurevm/)
* Content Source: [docs/azurevm/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/azurevm/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@RoboMikkel - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
