### ISSUE TITLE
Please rename Microsoft Defender ATP to Microsoft Defender for Endpoint

### ISSUE THREAD

**Issue by ilantz** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#405]
Please rename Microsoft Defender ATP to Microsoft Defender for Endpoint
https://www.microsoft.com/en-us/security/business/threat-protection/endpoint-defender

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3052a39-0e08-62c1-1262-04f8eafd3d10
* Version Independent ID: 108d8384-714d-970d-1b4d-8e3a366c5504
* Content: [Microsoft Defender ATP - Connectors](https://docs.microsoft.com/en-us/connectors/wdatp/)
* Content Source: [docs/wdatp/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/wdatp/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@ilantz - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
