### ISSUE TITLE
How to get VM running status by using "Get virtual machine" action?

### ISSUE THREAD

**Issue by doggy8088** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#406]
With REST API, I can append `$expand=instanceView` to the API request to get the running status of the VM. With the Logic App's Action, I can't do this operation. This is very common usage. Please add this feature to the action. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edd81673-4c78-5dfe-b2ae-fd94ea351b44
* Version Independent ID: fca7ea7a-8190-a246-c1bd-a9308596d3b9
* Content: [Azure VM - Connectors](https://docs.microsoft.com/en-us/connectors/azurevm/#get-virtual-machine?WT.mc_id=DT-MVP-4015686)
* Content Source: [docs/azurevm/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/azurevm/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@doggy8088 - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.

**Comment by doggy8088** [comment]
Thanks. I posted an idea here: https://feedback.azure.com/d365community/idea/f3db8880-6ee9-ec11-a81b-6045bd7ac9f9
