### ISSUE TITLE
File support for Excel Online (Business) connector needs caveat

### ISSUE THREAD

**Issue by AlexJerabek** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#409]
The bulletpoint "The connector supports files only in Microsoft Excel Open XML Spreadsheet format (*.xlsx)." under **Known Issues and Limitations** is not entirely accurate. The **Run script** action supports .xslm files, even though the file browser limits their selection (necessitating use of the file's metadata). This support is documented here: https://docs.microsoft.com/en-us/office/dev/scripts/develop/macros-power-automate

Can we please add a caveat that .xslm files are supported by the **Run script** action?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63dd2d5e-d90f-4654-c406-256e3e680e6d
* Version Independent ID: f2cd384b-2690-393d-3058-a363523f7d62
* Content: [Excel Online (Business) - Connectors](https://docs.microsoft.com/en-us/connectors/excelonlinebusiness/#feedback)
* Content Source: [docs/excelonlinebusiness/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/excelonlinebusiness/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@AlexJerabek - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
