### ISSUE TITLE
Sharepoint HTTP Requests

### ISSUE THREAD

**Issue by mdhruv1** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#410]
[Enter feedback here]
Will be helpfull if you can share with us step by step how to use logic apps and power automate
to download and upload files using the sharepoint http connector.  
I think that is the only way I can push a file which is more than 100mb to an azure blob.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69a01872-3062-4100-f807-7d43e8111e9f
* Version Independent ID: 48560378-76ed-cb42-e816-894179e1f16d
* Content: [SharePoint - Connectors](https://docs.microsoft.com/en-us/connectors/sharepointonline/#get-file-metadata-using-path)
* Content Source: [docs/sharepointonline/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/sharepointonline/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@mdhruv1 - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
