### ISSUE TITLE
Key vault connector - Managed identity authentication preview

### ISSUE THREAD

**Issue by cveld** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#411]
The UX within Logic apps state that the Key vault connector - Managed identity authentication feature is currently in preview. Are you already supporting production usage, or is the guidance to wait until general availability?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69488baa-bdb4-59e0-6c80-a62edf60e594
* Version Independent ID: 86b47cc1-4736-bf4b-654e-036a7104b242
* Content: [Azure Key Vault - Connectors](https://docs.microsoft.com/en-us/connectors/keyvault/)
* Content Source: [docs/keyvault/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/keyvault/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@cveld - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
