### ISSUE TITLE
Can Sort / Filter be added to the page so it is easier to determine which cloud instances each connector is available in?

### ISSUE THREAD

**Issue by gZip34** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#412]

**Comment by v-aangie** [comment]
@gZip34 - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
