### ISSUE TITLE
AddRows function description should indicate that it applies only to Streaming Datasets

### ISSUE THREAD

**Issue by lordneeko** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#413]
AddRows function description should indicate that it applies only to Streaming Datasets. 

Replace:
Use Power BI REST API to add rows to a dataset.

With:
Use Power BI REST API to add rows to a **_Streaming_** dataset.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1214f622-5b88-afa0-54cb-eae8ea4b3bfd
* Version Independent ID: d5efdba5-d278-73e4-1571-13abe8474c40
* Content: [Power BI - Connectors](https://docs.microsoft.com/en-us/connectors/powerbi/)
* Content Source: [docs/PowerBI/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/PowerBI/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@lordneeko - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.

**Comment by lordneeko** [comment]
Nothing was done, the page hasn't been updated. And you didn't even address the inputs. Reopening
