### ISSUE TITLE
When a record is selected missing from this page and flow

### ISSUE THREAD

**Issue by VFXpro** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#414]
With the OLD CDS, or Legacy Dataverse, there is an important trigger called "When a record is selected".  That is missing with the green dataverse actions, please report ASAP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78bf3518-bce4-ecc5-8bf6-1fb627b9105e
* Version Independent ID: d46568f2-e080-cbbe-2f7e-a655bce20b64
* Content: [Microsoft Dataverse - Connectors](https://docs.microsoft.com/en-us/connectors/commondataserviceforapps/#triggers)
* Content Source: [docs/commondataserviceforapps/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/commondataserviceforapps/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@VFXpro - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
