### ISSUE TITLE
Ehe email adress in the Important box on the page doesn't work

### ISSUE THREAD

**Issue by Daniel-labs** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#415]
The email address connectorpartnermgmtteam@microsoft.com givs a 550 5.4.1  status. I.e, the email adress in the Important box on the page, can't be found at microsoft.com

Rgs
Daniel

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b3a1855-a1b9-bc71-b259-b23a7d9c388c
* Version Independent ID: aa680db2-3b73-f0de-97b3-1a9a14cad4e2
* Content: [Independent publisher certification process](https://docs.microsoft.com/en-us/connectors/custom-connectors/certification-submission-ip)
* Content Source: [docs/custom-connectors/certification-submission-ip.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/certification-submission-ip.md)
* Service: **connectors**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by v-aangie** [comment]
@Daniel-labs - Thanks for your feedback. We have updated the docs to fix information about the email,, and the updated content will be live later today. Closing this issue.
