### ISSUE TITLE
.Net Framework Target not specified in documentation

### ISSUE THREAD

**Issue by coatsy** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#416]
I've noticed that it's not possible to use recent (.Net Standard 2.1) methods, for example

`string.Join(char, string[])`

While it is possible to use older overloads, for example

`string.Join(char, IEnumerable<string>)`

It would be very helpful to have the target framework documented, especially as the error message thrown when trying to save a script using the modern overload is not at all descriptive.

It would probably be a useful addition to the FAQ at the very least.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0293dbc2-1f0f-ff7b-d155-536fdcbfbc9d
* Version Independent ID: 710f2fe8-ca11-2a2f-2faa-86749a42b55a
* Content: [Write code in a custom connector](https://docs.microsoft.com/en-us/connectors/custom-connectors/write-code)
* Content Source: [docs/custom-connectors/write-code.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/write-code.md)
* Service: **connectors**
* GitHub Login: @shgogna
* Microsoft Alias: **shgogna**

**Comment by v-aangie** [comment]
@coatsy - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
