### ISSUE TITLE
"Set Host URL" can´t be used when a custom connector in Power Platform uses a gateway.

### ISSUE THREAD

**Issue by Ydr** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#418]
[Enter feedback here]
Hello team,

I am Yader Morales Support Escalation Engineer from the Power Platform team. We found that this template "Set Host URL" can't be used when the users use a gateway. We need the backendUrl to specify the gateway service, but the policy specifies the actual server directly.  That server is not accessible on the open internet, hence an error mentioning that "The remote name could not be resolved" appears.

Being said that would be even better to state in the doc that this is by design. Or if there is a plan to support this in the future please let us know.

Kind regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3817394-e2f3-da6b-797c-552ae6f3e71f
* Version Independent ID: b0e24b14-8f7c-57e4-e7e7-4e0447dcf354
* Content: [Set Host URL](https://docs.microsoft.com/en-us/connectors/custom-connectors/policy-templates/dynamichosturl/dynamichosturl)
* Content Source: [docs/custom-connectors/policy-templates/dynamichosturl/dynamichosturl.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/policy-templates/dynamichosturl/dynamichosturl.md)
* Service: **connectors**
* GitHub Login: @natalie-pienkowska
* Microsoft Alias: **napienko**

**Comment by rootsmusic** [comment]
Is [this repo's issues](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors-public/issues) being assigned to anyone on the team?

**Comment by v-aangie** [comment]
@Ydr - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
