### ISSUE TITLE
Cli 

### ISSUE THREAD

**Issue by mdhruv1** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#42]
Many will be citizen developers learning about dev ops.

So to get this working and have it would be helpful to include a detailed checklist 

This checklist should include 
These are the steps and this is the role or person you can get the answers from
Or can give you permission 

What would be even more cool is Microsoft can make some azure function which 
Give a custom checklist after checking the email is originating from the same powerapps tenant

This is a great start but not good enough to reach the finish line 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ae4e2ec-bb1d-8e70-bdb4-c2ecb57e6d73
* Version Independent ID: ba1cfb3e-51b1-02ce-7654-969ee500b0f5
* Content: [Microsoft Power Platform Connectors CLI](https://docs.microsoft.com/en-us/connectors/custom-connectors/paconn-cli#feedback)
* Content Source: [docs/custom-connectors/paconn-cli.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/paconn-cli.md)
* Service: **connectors**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by bezhan-msft** [comment]
Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) or to the connector-specific support contact (if applicable).
