### ISSUE TITLE
Convert SentimentDemo.postman_collection.json to Postman Version 2

### ISSUE THREAD

**Issue by Lukejvv** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#422]
The current version of Postman does not support importing V1 files such as that at https://procsi.blob.core.windows.net/docs/SentimentDemo.postman_collection.json

Recommend Upgrade to v2 for a better user experience.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd4ed455-8e17-4699-da0f-c7dc01d72c12
* Version Independent ID: a1662685-6c0b-d920-f6d8-929b176fbe6c
* Content: [Create a custom connector from a Postman collection](https://docs.microsoft.com/en-us/connectors/custom-connectors/define-postman-collection)
* Content Source: [docs/custom-connectors/define-postman-collection.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/define-postman-collection.md)
* Service: **connectors**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by v-aangie** [comment]
@Lukejvv - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
