### ISSUE TITLE
Additional Details on Locating Planner's Group ID

### ISSUE THREAD

**Issue by iUnknwn** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#423]
The planner connector documentation references a plan's Group Id, but doesn't explain where to find it from Planner. 

The group id is visible in the URL when looking at a planner board, via the web interface (?groupId=[ID]), but is not exposed elsewhere in the UI (at least, as far as I can tell). 

It would be great if this was mentioned in the documentation - knowing it's part of the URL makes selecting the correct group much easier.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24185ffe-d266-c113-9327-4e305c276697
* Version Independent ID: 98978ace-f736-e07a-bde3-9156cd815100
* Content: [Planner - Connectors](https://docs.microsoft.com/en-us/connectors/planner/#create-a-task)
* Content Source: [docs/Planner/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Planner/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@iUnknwn - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.

**Comment by v-aangie** [comment]
@iUnknwn - I'm responding to your IM, "The bug was about how the current documentation does not appear to explain how to get the group id. As I mentioned in the bug, our team was able to figure out that the group ID was extractable from the URL of the plan, but that wasn't covered in the documentation." We will soon look into this issue. Thanks for your feedback.
