### ISSUE TITLE
Is the AddRowsV2 an async operation?

### ISSUE THREAD

**Issue by samadane** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#426]
https://docs.microsoft.com/en-us/connectors/excelonlinebusiness/#add-a-row-into-a-table

Is AddRowsV2 an async operation, meaning that the flow still has to be up even though this action has passed?

Having to add a delay after adding 100 or so rows to an Excel file.  Without a delay, not all rows get added to the table before the flow ends.

**Comment by v-aangie** [comment]
@samadane Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
