### ISSUE TITLE
No support for SSL

### ISSUE THREAD

**Issue by desaiak** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#427]
[Enter feedback here]

I think it should be very clearly mentioned on this page that the connector currently does not support SSL.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7a3704-e342-64bc-9893-b0fe8923897e
* Version Independent ID: 011ebda2-6fcf-3abc-5ee9-bb066ed2c894
* Content: [PostgreSQL - Connectors](https://docs.microsoft.com/en-us/connectors/postgresql/)
* Content Source: [docs/postgresql/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/postgresql/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by natalie-pienkowska** [comment]
Hi @desaiak thanks for reporting this issue. We will be adding this to the PostgreSQL doc.
