### ISSUE TITLE
Delivery frequency (dev->master)

### ISSUE THREAD

**Issue by hassbring** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#429]
Hi! 

I'm curious to know if it would be possible to speed up the frequency of delivery, e.g. merging the dev branch to the master branch? Currently it is done every 8-12 days or so. The process should in theory be able to run autonomously. Would strengthen the contributive concept a bit. 

If it could come down to at least e.g. every 2-3 days it would be much appreciated, would it be possible?
Meanwhile, I do understand that the matter could be more complex than it seems.

**Comment by v-aangie** [comment]
@hassbring - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
