### ISSUE TITLE
Typo exist

### ISSUE THREAD

**Issue by eltociear** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#43]
3 typo found in this article.
Issue Type Id→Isue Type Id

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76d2c23e-c66c-3e66-f61d-681c4327e461
* Version Independent ID: 0c4a4d9e-d055-d56e-6b48-c70cb753aa60
* Content: [JIRA - Connectors](https://docs.microsoft.com/en-us/connectors/jira/)
* Content Source: [docs/JIRA/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/JIRA/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment]
Thank you for your feedback. This is now under review and no further action is required at this time.

**Comment by v-aangie** [comment]
@eltociear - Thanks for your feedback. We have updated the docs to fix information about the issue typo, and the updated content is live. Closing this issue.
