### ISSUE TITLE
No example for PowerApps 

### ISSUE THREAD

**Issue by jasonwbaxter** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#432]
Hi , I don't see an example on how to use this connector in Powerapps.
AzureMonitorLogs.QueryData(Subscription,Resourcegroup,Type ,Name,Timeseries,query)

there are no examples on what type of values need to go into this formula , Is it the ID , name , what does Time series in string mean , etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d0739bd-fe72-43e5-9ea7-354eec3b3636
* Version Independent ID: 40cb6b9a-100e-199a-ef3d-d9770514ca44
* Content: [Azure Log Analytics Data Collector - Connectors](https://docs.microsoft.com/en-us/connectors/azureloganalyticsdatacollector/#using-this-connector)
* Content Source: [docs/azureloganalyticsdatacollector/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/azureloganalyticsdatacollector/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@jasonwbaxter - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
