### ISSUE TITLE
Outline Operations for Twitter Search Text

### ISSUE THREAD

**Issue by cecilphillip** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#434]
Could a more detailed section be added the explains the types of query operations that can be added to the Search Text filed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4362ac6-b761-f114-a78d-1c1a7a19b67a
* Version Independent ID: d2d21050-f068-b115-3755-e4752766b8c1
* Content: [Twitter - Connectors](https://docs.microsoft.com/en-us/connectors/twitter/#when-a-new-tweet-is-posted)
* Content Source: [docs/twitter/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/twitter/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by natalie-pienkowska** [comment]
Hi @cecilphillip thanks for providing this feedback. We've added it to our doc bug backlog and will prioritize accordingly.
