### ISSUE TITLE
Outcomes vs. Responses

### ISSUE THREAD

**Issue by Ukiman1014** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#439]
Please include this valuable information.  I struggled with approval logic to work because, at first, I did not understand what outcomes were vs. responses.  I had obtained the information below after opening a ticket with Microsoft.

_Outcome is a property that summarizes all the responses from multiple users_.  So if the Approval is set to First to Approve then Outcome will be either Approve or Reject.  if the approval is set to All must approve then it will be a string like "Approve Reject Approve" (if you have three approvers and one rejects.) But that will be outside the loop and independent from Responses.

_Responses is a collection of individual Response objects_.  So you can see that once you load Responses into an Apply to Each loop you have access to the individual properties of each Response in the collection.  For the response itself you want the Responses Approver Response.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc3be4e8-204a-a1f5-21ea-a289dc8a0583
* Version Independent ID: 167b2834-1025-136b-9c25-4ba80e3c3410
* Content: [Approvals - Connectors](https://docs.microsoft.com/en-us/connectors/approvals/)
* Content Source: [docs/Approvals/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Approvals/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@Ukiman1014 - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
