### ISSUE TITLE
How do you pay for premium connectors?

### ISSUE THREAD

**Issue by dombat** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#441]
Its very hard to find out how much premium connectors are. There is no link through to the pricing page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 194425b5-98ca-e705-ad22-9d9297ea2da1
* Version Independent ID: 74dab439-bdd4-b1f3-307f-3a810d91e507
* Content: [List of all Preview connectors](https://docs.microsoft.com/en-us/connectors/connector-reference/connector-reference-preview-connectors)
* Content Source: [docs/connector-reference/connector-reference-preview-connectors.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/connector-reference/connector-reference-preview-connectors.md)
* Service: **connectors**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by natalie-pienkowska** [comment]
Hi @dombat Our team does not handle licensing and pricing. Please go to this page and request help from there: https://powerautomate.microsoft.com/en-us/pricing/
