### ISSUE TITLE
GA availability of the Power Automate/Logic Apps Marketo Connector 

### ISSUE THREAD

**Issue by philipverlinden** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#442]
I'm looking to connect with the progam manager/engineers that manage/developed this connector to understand it's timeline, ins and outs, etc...

We working with a stratigic customer that's almost ready to implemt it, but the Preview tag raises conserns...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88df0f0c-5a56-f45c-2e33-924e83344d2b
* Version Independent ID: 1cbf7e49-0f06-b8f6-7058-046a962f3141
* Content: [Marketo - Connectors](https://docs.microsoft.com/en-us/connectors/marketo/)
* Content Source: [docs/marketo/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/marketo/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by natalie-pienkowska** [comment]
Thank you @philipverlinden for raising this issue. The Marketo connector needs to reach these criteria before it moves to GA- https://docs.microsoft.com/en-us/connectors/custom-connectors/certification-to-ga. Currently, it has below an 80% success rate, so it will take about 3 months to get it to GA.
