### ISSUE TITLE
When was the trigger limitation added?

### ISSUE THREAD

**Issue by MiyukiAmino** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#443]
Cx wants to know below when was trigger limitation added?
I can't see git-hub history, so would be appreciate for checking it.

---------
The When a new email arrives, When a new email arrives (V3), When a new email mentioning me arrives (V3), When an email is flagged (V3), When an event is added, updated or deleted (V3) triggers fire on the corresponding event's occurrence almost immediately in most cases, but there could be rare circumstances when the trigger's delay to fire may take up to one hour.
---------

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc40a098-af8c-d8a9-4538-71d184efbe91
* Version Independent ID: 0ee8cf79-18e9-d923-607f-ef40cdd23e4d
* Content: [Office 365 Outlook - Connectors](https://docs.microsoft.com/en-us/connectors/office365/?source=docs)
* Content Source: [docs/office365/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/office365/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@MiyukiAmino - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
