### ISSUE TITLE
"Upload a file or an image" "Content name" doesn't work with non-single-byte characters, clarification required

### ISSUE THREAD

**Issue by user0604** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#444]
[Enter feedback here]
It is confirmed that using 2-byte or 3-byte characters in "Content name" field of "Upload a file or an image" action causes the flow to fail (Bad request), or to set the wrong name to the indicated file (if it does not fail in some cases).
You can refer to IcM #257644679 or #244744416 for more details, as well as the following work item 
https://msazure.visualstudio.com/One/_workitems/edit/10360756

As long as no clarification is stated on MS official documents, this is considered a defect. 
Devs said this can't be fixed easily so until the fix is delivered in the unseen future we should put a notice to let the user know, and to deflect support requests too (thank you).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78bf3518-bce4-ecc5-8bf6-1fb627b9105e
* Version Independent ID: d46568f2-e080-cbbe-2f7e-a655bce20b64
* Content: [Microsoft Dataverse - Connectors](https://docs.microsoft.com/en-us/connectors/commondataserviceforapps/#feedback)
* Content Source: [docs/commondataserviceforapps/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/commondataserviceforapps/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@user0604 - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
