### ISSUE TITLE
Need a public API for getting list of connectors and their Region Status

### ISSUE THREAD

**Issue by lordneeko** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#445]
Currently, I'm using Web Scraping to get the current availability of connectors within each region. This is obviously very slow and abusive against your web server.  Better, would be an API that gets List of all connectors, Their "Service: [Apps, Automate, "LogicApps]", Their class: [Standard, premium], Their Available Regions, All Actions, All Triggers.

This data is freely available on the web site but I am unable to scrape this data efficiently. Would be better to get it as data objects. The PowerAutomate "List Connectors" action is extremely limited and it only lists what is in YOUR region. Looking to build something that shows all connectors and their available regions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7741d635-bb14-0cbb-6ddc-d53108b59423
* Version Independent ID: c52d6e84-dc16-af82-9e1f-923659e25c54
* Content: [Connector reference overview](https://docs.microsoft.com/en-us/connectors/connector-reference/)
* Content Source: [docs/connector-reference/index.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/connector-reference/index.md)
* Service: **connectors**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by v-aangie** [comment]
@lordneeko - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
