### ISSUE TITLE
North Europe Outbound IP Ranges - Overlapped Address

### ISSUE THREAD

**Issue by asos-andrewgoad** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#446]
For North Europe Outbound IP Ranges, the IP Address 13.69.231.198 is covered by the range 13.69.231.192 - 13.69.231.223 (13.69.231.192/27)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80b88b63-df14-773f-5a88-8b2ea1157665
* Version Independent ID: a0da6c99-a285-9904-b52f-e1a2cc2426d5
* Content: [Managed connectors outbound IP addresses](https://docs.microsoft.com/en-us/connectors/common/outbound-ip-addresses#azure-logic-apps)
* Content Source: [docs/common/outbound-ip-addresses.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/common/outbound-ip-addresses.md)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@asos-andrewgoad - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
