### ISSUE TITLE
Planner Not Setting 'Urgent' if Priority set to 0

### ISSUE THREAD

**Issue by iUnknwn** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#449]
Using the 'Create A Task' function, if priority is set to 0, the generated task has 'Medium' priority in the planner UI. Setting the priority to '1' marks the task as 'Urgent'.

Currently the docs say either 0 or 1 should result in an 'Urgent' task. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24185ffe-d266-c113-9327-4e305c276697
* Version Independent ID: 98978ace-f736-e07a-bde3-9156cd815100
* Content: [Planner - Connectors](https://docs.microsoft.com/en-us/connectors/planner/)
* Content Source: [docs/Planner/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Planner/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by natalie-pienkowska** [comment]
Thanks for reporting this issue @iUnknwn. It seems like this may be an issue with the connector. We will investigate this.
