### ISSUE TITLE
Missing a daily limit

### ISSUE THREAD

**Issue by FerretyWorld** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#450]
Received an error from my flow on the action "Refresh a dataset" = 

{
  "error": {
    "code": "Request Throttled",
    "message": "Invalid dataset refresh request. Number of refresh requests in last 24 hours exceeded limit"
  }
}

The page is missing what this limit is referring to because it is not related to the documented throttling of Calls per second, 100/60 secs.

The page should include the # of refreshes allowed in a 24 hour period since it is much less than the 100 calls per 60 second possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1214f622-5b88-afa0-54cb-eae8ea4b3bfd
* Version Independent ID: d5efdba5-d278-73e4-1571-13abe8474c40
* Content: [Power BI - Connectors](https://docs.microsoft.com/en-us/connectors/powerbi/#limits)
* Content Source: [docs/PowerBI/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/PowerBI/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by natalie-pienkowska** [comment]
Thank you @FerretyWorld we will investigate this issue to confirm and then update the docs accordingly.
