### ISSUE TITLE
Register a connector as a Standard Connector

### ISSUE THREAD

**Issue by maximelokel** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#452]
[Enter feedback here]
How can we be registered as a Standard Connector? (as opposed to Custom or Premium connectors)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40aa840d-4e59-9953-f052-a4560f4d3367
* Version Independent ID: 398a8a7d-ca1b-8968-44cc-46639bb40d5f
* Content: [Non-Microsoft publisher certification process](https://docs.microsoft.com/en-gb/connectors/custom-connectors/certification-submission#feedback)
* Content Source: [docs/custom-connectors/certification-submission.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/certification-submission.md)
* Service: **connectors**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by natalie-pienkowska** [comment]
Hi @maximelokel all net new connectors fit into the premium category unless there is a very strong exception.
