### ISSUE TITLE
ChainPoint connector is broken - either fix or remove it

### ISSUE THREAD

**Issue by zylantha** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#454]
The ChainPoint connector has been broken for a week now, returning an unresolved host failure.

Please either fix or remove the connector.

Refer:
https://powerusers.microsoft.com/t5/I-Found-A-Bug/ChainPoint-actions-failing-remote-name-cannot-be-resolved/m-p/1335814#M9851

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f70ab721-5e26-be44-0ef6-182298ec5955
* Version Independent ID: 7375b7a0-3fa3-3a97-872b-30cf8f5f2baa
* Content: [Chainpoint - Connectors](https://docs.microsoft.com/en-au/connectors/chainpointnode/#generate-a-sha256-hash-from-a-string)
* Content Source: [docs/chainpointnode/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/chainpointnode/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by natalie-pienkowska** [comment]
Hi @zylantha thank you for raising this. We have deprecated the Chainpoint connector.
