### ISSUE TITLE
PowerApps Custom Connector OpenAPI 3 support?

### ISSUE THREAD

**Issue by haneef95** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#456]
Hi,

I believe the OpenAPI 3 (formerly swagger 2.0) was released back in 2017 (4 yrs ago), however, PowerApps still only support OAS 2.0.

Any timeline as to when we could see support for OAS 3 please?

It's been quite a long wait!

Hardly any APIs could be imported at the moment, even the [Microsoft Graph API Spec](https://github.com/microsoftgraph/msgraph-sdk-powershell/tree/dev/openApiDocs/v1.0) is on 3.0, so, importing that has become impossible!

Kindly advise on the timeline for OAS 3 support.

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9659a345-1116-5020-4300-386f3a591c2e
* Version Independent ID: e2a3861f-d3d5-f542-28db-1897d4c7feb0
* Content: [Create a custom connector from an OpenAPI definition](https://docs.microsoft.com/en-us/connectors/custom-connectors/define-openapi-definition)
* Content Source: [docs/custom-connectors/define-openapi-definition.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/define-openapi-definition.md)
* Service: **connectors**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by natalie-pienkowska** [comment]
Hi @haneef95 thank you for raising this important issue. We are hoping to provide support for Open API 3.0 some time in 2022.

**Comment by haneef95** [comment]
Is there an entry for this on the official road map?

**Comment by ChrisonSimtian** [comment]
bump... been 2 years, still urgent ... was on the roadmap for preview in 2022 ... nothing happend... very disappointing :-( basically renders custom connectors useless
