### ISSUE TITLE
How shall the user specify the api key for text analysis API?

### ISSUE THREAD

**Issue by susanhuhu** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#457]
[Enter feedback here]
The instruction only gives step on how to specify an action from the customer connector, but it doesn't provide instruction on where to provide the API key to authenticate with Cognitive service text analysis.   Does this mean the customer connector somehow has a hard coded API key?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9dab1ed-5c9d-a077-857b-df6848008a73
* Version Independent ID: 346c3991-d3bb-bdbd-b9d6-a3b733e94f65
* Content: [Use a custom connector from a flow](https://docs.microsoft.com/en-us/connectors/custom-connectors/use-custom-connector-flow)
* Content Source: [docs/custom-connectors/use-custom-connector-flow.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/use-custom-connector-flow.md)
* Service: **connectors**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by v-aangie** [comment]
@susanhuhu  - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
