### ISSUE TITLE
We need some example

### ISSUE THREAD

**Issue by ntatschner** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#459]
It would be really helpful to get some examples here

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00a0a61d-f2fc-aa31-042b-0b472c8bff1c
* Version Independent ID: 1650d41c-0ec7-d8b4-a98b-5f96bc8b0bdb
* Content: [ServiceNow - Connectors](https://docs.microsoft.com/en-us/connectors/service-now/)
* Content Source: [docs/service-now/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/service-now/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by natalie-pienkowska** [comment]
Hi @ntatschner can you please be more specific with what kind of examples you're looking for? I also suggest viewing Power Automate templates with ServiceNow as a great place to start.
