### ISSUE TITLE
what are the additional properties options

### ISSUE THREAD

**Issue by supportguy** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#460]
When using the 'update user' action, there is an option to add ' additional properties'. I'm wondering if these are additional Azure AD user account properties? 

Can this document be updated to provide what these additional properties are?

image

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd854166-65d2-2bc3-5fc6-bb89b93f7b2a
* Version Independent ID: 3be5703b-0f16-18e9-8f15-5b6ca32cb6c1
* Content: [Azure AD - Connectors](https://docs.microsoft.com/en-us/connectors/azuread/#update-user)
* Content Source: [docs/AzureAD/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/AzureAD/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by natalie-pienkowska** [comment]
Thanks @supportguy  for reporting this issue. We've added it to our list of documentation bugs and will prioritize accordingly.
