### ISSUE TITLE
More information about Send an HTTP request' needed.

### ISSUE THREAD

**Issue by pagejustin** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#461]
Where can we find more information about the 'Send an HTTP request.' What are we supposed to put in the required 'file' parameter?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66d136b3-75bc-fd53-2d17-15f0904a0b54
* Version Independent ID: 71609855-7cb2-9994-e8f3-13fe93d9aa54
* Content: [Office 365 Groups - Connectors](https://docs.microsoft.com/en-us/connectors/office365groups/#send-an-http-request-(preview))
* Content Source: [docs/office365groups/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/office365groups/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by natalie-pienkowska** [comment]
Thank you @pagejustin for your feedback. We've added this documentation bug to our backlog and will prioritize accordingly.
