### ISSUE TITLE
YouTube 

### ISSUE THREAD

**Issue by tinagallant81** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#463]
[gallant670-subscriptions-2021-11-05-12_27_18.zip](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors-public/files/7587142/gallant670-subscriptions-2021-11-05-12_27_18.zip)
[My youtube ](https://youtube.com/c/TinaGallant1981)  ##[](google-site-verification: google5036f30526c23a54.html) 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74435782-e494-82fa-32fb-801c7aa3f2ad
* Version Independent ID: 12e4c9b8-97c0-bd22-6d67-8de09391cad2
* Content: [YouTube - Connectors](https://docs.microsoft.com/en-us/connectors/youtube/)
* Content Source: [docs/YouTube/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/YouTube/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by tinagallant81** [comment]
`
[619005ae55ae2619005ae55ae4-1.docx](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors-public/files/7587020/619005ae55ae2619005ae55ae4-1.docx)
`

**Comment by natalie-pienkowska** [comment]
Hi @tinagallant81. Due to security concerns, I will not be opening up the zip file. Please resubmit your issue and write out the details. Thank you!

**Comment by tinagallant81** [comment]
Thanks anyways
