### ISSUE TITLE
Task editing through connector

### ISSUE THREAD

**Issue by IdoMann** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#464]
Hi, Are you working on creating a connector that will enable to edit a task through a connector and save the change logs? 
I want to create a project management app that will use daily logs from which I will automatically update the gantt. 
Do you think this is something that will happen in the short - medium term? 

Warm Regards, 
Ido Mann

---
#### פרטי המסמך

⚠ *אין לערוך מקטע זה. פעולה זו נדרשת עבור קישור לנושאים ב- docs.microsoft.com ← GitHub.*

* ID: c6ca2325-c4dd-a73e-0440-9b1881ea415b
* Version Independent ID: 88ca21f2-2440-6ab3-8b9e-fe5e4860996c
* Content: [Project Online - Connectors](https://docs.microsoft.com/he-il/connectors/projectonline/)
* Content Source: [docs/ProjectOnline/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/ProjectOnline/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by natalie-pienkowska** [comment]
Hi @IdoMann please add feature and connector requests here: https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity This repository is for documentation bugs. Thank you!
