### ISSUE TITLE
Microsoft Forms Connector Regional Availability

### ISSUE THREAD

**Issue by ballard297** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#466]
To my understanding and experience, the Microsoft Forms connector in Power Automate is not currently available in GCC High. However, this documentation page lists that it is only unavailable for DoD, but not GCC High. Can this please be adjusted accordingly?

I work in a GCC High environment and do not have access to the Microsoft Forms connector and the below URL seems to confirm that it is not available in GCC High as well. This omission is confusing to our citizen developers, who reference the documentation frequently. 

URL reference for Forms Connector limitation: https://support.microsoft.com/en-us/office/microsoft-forms-features-for-u-s-government-community-cloud-gcc-gcc-high-and-dod-environments-5cbd407a-eef7-431e-8e3a-eb666eab4b4c

You can see that the Excel Online Connector documentation does correctly specify the limitation for GCC High: https://docs.microsoft.com/en-us/connectors/excelonlinebusiness/

Please let me know what is correct and adjust the documentation accordingly. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a5a57d-aa82-9c07-5502-bd3be89773dc
* Version Independent ID: 5bdbf2ae-5c31-7a59-56f0-09d568602012
* Content: [Microsoft Forms - Connectors](https://docs.microsoft.com/en-us/connectors/microsoftforms/)
* Content Source: [docs/MicrosoftForms/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/MicrosoftForms/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by natalie-pienkowska** [comment]
Hi @ballard297 as of last week, the Microsoft Forms connector is available in both DoD and GCC High!
