### ISSUE TITLE
Removal of Teamwork Connector Page 

### ISSUE THREAD

**Issue by holly-mcgill** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#467]
[Enter feedback here]
Hi there,

Can we please get the Teamwork connector page removed? It is not longer available to our users. Let me know if there is anything needed on our end.

Holly @teamwork. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa2f08e-238c-92d5-5c2e-bd3d4c1659f9
* Version Independent ID: bc62fa9a-10c5-c290-d318-781110cd40cf
* Content: [Teamwork Projects - Connectors](https://docs.microsoft.com/en-us/connectors/teamwork/)
* Content Source: [docs/Teamwork/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Teamwork/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by natalie-pienkowska** [comment]
Hi @holly-mcgill it looks like this connector is currently working. If you're an admin and you want to remove it from your tenant, please put this connector in the Blocked category.

**Comment by holly-mcgill** [comment]
@natalie-pienkowska could you please link a doc to explain how to do this? The dev working on this has since left Teamwork, and we need to figure out where this lives and how to remove it. Thank you!
