### ISSUE TITLE
How to reference request body within expressions

### ISSUE THREAD

**Issue by Blackbaud-BenLambert** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#468]
This page mentions referencing the request body along with headers, query parameters, and connection parameters in the phrase _(for example, request headers or body, queryParameters, connection parameters, and so on_)`.  There are examples for referencing headers, query parameters, and connection parameters shown, but no example for referencing the request body.  Is it possible to reference the request body in an expression?  If so, showing an example would be helpful.  If no, that phrase should be updated to remove confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41458bed-f93a-5a9a-7cc2-24ad4a615fec
* Version Independent ID: 8e286b44-d1ee-409d-5665-af213a1c7789
* Content: [Expressions in custom connectors](https://docs.microsoft.com/en-us/connectors/custom-connectors/policy-templates/expressions/expressions)
* Content Source: [docs/custom-connectors/policy-templates/expressions/expressions.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/policy-templates/expressions/expressions.md)
* Service: **connectors**
* GitHub Login: @schabungbam
* Microsoft Alias: **sameerch**

**Comment by natalie-pienkowska** [comment]
Thanks @Blackbaud-BenLambert for pointing this out! We have added this as a documentation bug internally and will take a look.

**Comment by Blackbaud-BenLambert** [comment]
Thanks Natalie - since you marked this as closed, how will I get notified when the issue is resolved and the docs are updated?
