### ISSUE TITLE
Need to mention connector can only be used from flows created from solutions

### ISSUE THREAD

**Issue by lukecolburn** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#47]
According to the following blog post, this connector can only be used from flows created from solutions. This limitation should be documented here, as it is very difficult to discover otherwise: https://flow.microsoft.com/en-us/blog/work-better-with-the-common-data-service-in-power-automate/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78bf3518-bce4-ecc5-8bf6-1fb627b9105e
* Version Independent ID: d46568f2-e080-cbbe-2f7e-a655bce20b64
* Content: [Common Data Service (current environment) - Connectors](https://docs.microsoft.com/en-us/connectors/commondataserviceforapps/)
* Content Source: [docs/commondataserviceforapps/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/commondataserviceforapps/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by JimDaly** [comment]
This will change soon. I understand this will become available outside of solutions within a week or so.

**Comment by lukecolburn** [comment]
Great Jim, thanks for the quick reply
