### ISSUE TITLE
Pushpin links not working

### ISSUE THREAD

**Issue by yosoyx** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#470]
A lot of the pushpin definitions have aka links that are not working
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ceeb123-8398-c312-617e-0c40cc85cd05
* Version Independent ID: 4f59f3b8-b4df-bb22-d0cc-6c5bac66abf2
* Content: [Bing Maps - Connectors](https://docs.microsoft.com/en-us/connectors/bingmaps/?source=docs)
* Content Source: [docs/BingMaps/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/BingMaps/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by natalie-pienkowska** [comment]
Hi @yosoyx do you mind providing more details on your feedback?

**Comment by yosoyx** [comment]
Sure. The documentation on pushpins has a good number of links to other resources. At the time they pointed to broken links
