### ISSUE TITLE
Page does not indicate that nested content control recursion is not supported.

### ISSUE THREAD

**Issue by samrueby** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#471]
Nested content controls recursion is not supported with this connector. When you use a file that contains nested repeater content controls, the designer only presents you with a single level. This feedback item indicates this is not supported: https://powerusers.microsoft.com/t5/Power-Automate-Ideas/Word-Online-Business-Connector-Populate-a-Microsoft-Word/idi-p/367395 . Please help out users reading the documentation by indicating this is not yet supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d39ce977-b1fc-d4be-3776-ad31a5b780ec
* Version Independent ID: 21c81572-7742-f033-cdc1-07c1090e9878
* Content: [Word Online (Business) - Connectors](https://docs.microsoft.com/en-us/connectors/wordonlinebusiness/#populate-a-microsoft-word-template)
* Content Source: [docs/wordonlinebusiness/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/wordonlinebusiness/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by natalie-pienkowska** [comment]
Thank you @samrueby for calling this out! We will certainly add this to the Word doc.
