### ISSUE TITLE
Text Analytics API link confusion

### ISSUE THREAD

**Issue by heatherr-nz** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#472]
__
The link to request access to the Text Analytics API says you don't need an Azure account.  The link takes you to a sign up page to create an account.  On doing this, you must provide credit card details.  So I searched for Text Analytics and clicked a link there, which took me back to the same sign up page.  So either, the link is not right OR you can no longer access without and account.  I don't really want to create an account just to do training, but it looks like I have no choice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f873de3b-82f2-8cbc-0de3-6dbdc968b9fa
* Version Independent ID: ca3ccf84-5de8-ef66-9bda-b804404b5085
* Content: [Custom connectors overview](https://docs.microsoft.com/en-us/connectors/custom-connectors/#get-an-api-key)
* Content Source: [docs/custom-connectors/index.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/index.md)
* Service: **connectors**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by natalie-pienkowska** [comment]
Thank you @heatherr-nz for reporting this! We have added this to the backlog and will prioritize accordingly.
