### ISSUE TITLE
PostgresSQL connector doesn't support SSL

### ISSUE THREAD

**Issue by tlourey** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#473]
SSL isn't supported with the PostgreSQL connector when using Power Automate and also PowerApps. 

I think this caveat should be included in the connector notes. 

https://powerusers.microsoft.com/t5/Power-Automate-Ideas/Offer-SSL-for-PostgreSQL-connection/idi-p/945719
https://powerusers.microsoft.com/t5/Connecting-To-Data/Encrypted-PostgreSQL-connection-to-Power-Automate/td-p/554284
https://powerusers.microsoft.com/t5/Building-Power-Apps/PowerApps-Postgres-Connection-failing-for-Azure-Hosted/td-p/342272

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7a3704-e342-64bc-9893-b0fe8923897e
* Version Independent ID: 011ebda2-6fcf-3abc-5ee9-bb066ed2c894
* Content: [PostgreSQL - Connectors](https://docs.microsoft.com/en-us/connectors/postgresql/)
* Content Source: [docs/postgresql/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/postgresql/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by natalie-pienkowska** [comment]
Thanks so much @tlourey for noting this. We will add this as an update to the documentation!
