### ISSUE TITLE
Images in document are hard to read

### ISSUE THREAD

**Issue by ecardakaris-knowledgeonecorp** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#474]
Images in this document are very blurry, can you replace them with some better quality please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54a9dbfc-59c8-3b66-af5c-7afe0e312384
* Version Independent ID: a34a4759-a955-870c-5566-d2101f0654cb
* Content: [Policy support in custom connectors](https://docs.microsoft.com/en-us/connectors/custom-connectors/policy-templates)
* Content Source: [docs/custom-connectors/policy-templates.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/policy-templates.md)
* Service: **connectors**
* GitHub Login: @shyamsu
* Microsoft Alias: **shyamsu**

**Comment by natalie-pienkowska** [comment]
Thanks for the feedback @ecardakaris-knowledgeonecorp If you zoom into the images, they are very clear.
