### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by pcasti** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#476]
This is an basic example:
---------------------------
![image](https://user-images.githubusercontent.com/5353147/147416845-3756dc2a-3a84-45f1-b032-4ea0e42a324a.png)

NotificationPowerAppsv2.SendPushNotificationV2(
    "PowerApps";                                                        // 'Field Service', 'Power Apps', '...365'
    JSON({ appIdentifier: "50xxxx-axxxx-43xxx1c2-d0xxx1238f" });    // Your AppID
    ["pascal@contoso.com"];                                        // Recipients      ["r1@contoso.com";"r2@contoso.com"];
    "This is it !";                                                     // Message
    true;                                                               // Open App ? YES=true NO=false
    {} )                                                                // custom parameters

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e319372-14e5-4c26-529c-ee49cfd7d011
* Version Independent ID: a3bc5df8-92f9-1f45-12a5-9b3fb4ed4668
* Content: [Power Apps Notification V2 - Connectors](https://docs.microsoft.com/en-us/connectors/powerappsnotificationv2/?source=docs)
* Content Source: [docs/powerappsnotificationv2/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/powerappsnotificationv2/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@pcasti - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
