### ISSUE TITLE
Outlook Connector Known Issues: EWS+ApplicationImpersonation no longer applicable

### ISSUE THREAD

**Issue by tx5westmt** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#477]
Perhaps add to the Known Issues/Limitations section a note that using global 'Send As' permission configured via EWS (exchange web services) API and ApplicationImpersonation does not appear to work any more (403 Forbidden error).  Instead of being able to apply ApplicationImpersonation and enable tenant-wide 'send as' permission for a powerful individual account you must now individually/explicitly apply the permission. I assume this is because the flow connector migrated from EWS to Graph API and I am unable to find documentation on how to register a flow application as a registered application in azure ad to grant the Graph API permissions globally.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc40a098-af8c-d8a9-4538-71d184efbe91
* Version Independent ID: 0ee8cf79-18e9-d923-607f-ef40cdd23e4d
* Content: [Office 365 Outlook - Connectors](https://docs.microsoft.com/en-us/connectors/office365/#send-email-with-options)
* Content Source: [docs/office365/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/office365/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@tx5westmt - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
