### ISSUE TITLE
Specified swagger has the following errors: 'Definition is not valid.  Error: 'Error : paths/~1text~1analytics~1v2.0~1sentiment/post/parameters/0/schema/properties/documents/items/properties/id/default : The 'default' value is of type 'Integer', but should match the given type 'String'. '

### ISSUE THREAD

**Issue by janaki77** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#480]
Hi there,
The URL which is used while updating connector is

https://westus.api.cognitive.microsoft.com/text/analytics/v2.0/sentiment

the above URL do not work and shows error as:

Specified swagger has the following errors: 'Definition is not valid.  Error: 'Error : paths/~1text~1analytics~1v2.0~1sentiment/post/parameters/0/schema/properties/documents/items/properties/id/default : The 'default' value is of type 'Integer', but should match the given type 'String'.
'
Can anybody sort this out, please? I am new to Power App and do not know what to do. I have also attached a screenshot. Please see below. Many Thanks.

Janaki

![Screenshot 2022-01-01 04 32 29](https://user-images.githubusercontent.com/47194839/147844052-40a70093-9258-427d-856b-832be0a6abd8.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c443c1c-e4af-1f21-10b3-9c8d81abc1f1
* Version Independent ID: 9aa14809-3da3-23b3-3210-7a2e84608f04
* Content: [Create a custom connector from scratch](https://docs.microsoft.com/en-us/connectors/custom-connectors/define-blank)
* Content Source: [docs/custom-connectors/define-blank.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/define-blank.md)
* Service: **connectors**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by RedsGT** [comment]
Post for help here: https://powerusers.microsoft.com/t5/Connector-Development/bd-p/ConnectorDevelopment
