### ISSUE TITLE
Unable to import v1 postman collection anymore

### ISSUE THREAD

**Issue by M365Bass** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#486]
Postman has stopped supporting v1 postman collection format and the provided sample cannot be imported anymore. Steps for upgrade can be found [here](https://learning.postman.com/docs/getting-started/importing-and-exporting-data/#converting-postman-collections-from-v1-to-v2)

<img width="628" alt="image" src="https://user-images.githubusercontent.com/11630074/148859299-e970fa04-daa2-4ed1-a966-3b623427f130.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd4ed455-8e17-4699-da0f-c7dc01d72c12
* Version Independent ID: a1662685-6c0b-d920-f6d8-929b176fbe6c
* Content: [Create a custom connector from a Postman collection](https://docs.microsoft.com/en-us/connectors/custom-connectors/define-postman-collection)
* Content Source: [docs/custom-connectors/define-postman-collection.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/define-postman-collection.md)
* Service: **connectors**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by v-aangie** [comment]
@M365Bass - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
