### ISSUE TITLE
Update Calendly  Documentation and API

### ISSUE THREAD

**Issue by nirajcalendly** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#487]
Hello, I am Sr. PM at Calendly. We have scheduled deprecation of V1 API and one of the steps was to move the location where API key could be found. Please update the documentation here to reflect the change and also plan to migrate to V2. 
More information of the migration can be found here: https://developer.calendly.com/how-to-migrate-from-api-v1-to-api-v2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9e5c5d2-d262-a43a-037e-b2ac89e9ec85
* Version Independent ID: fdf41e42-9785-5425-a820-f0029efc8681
* Content: [Calendly - Connectors](https://docs.microsoft.com/en-us/connectors/calendly/)
* Content Source: [docs/Calendly/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Calendly/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@nirajcalendly - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
