### ISSUE TITLE
Add @environmentVariables

### ISSUE THREAD

**Issue by filcole** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#489]
[Enter feedback here]
Should this document be updated to include the new (preview) environmentVariables as demonstrated in https://docs.microsoft.com/en-us/connectors/custom-connectors/environment-variables?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41458bed-f93a-5a9a-7cc2-24ad4a615fec
* Version Independent ID: 8e286b44-d1ee-409d-5665-af213a1c7789
* Content: [Expressions in custom connectors](https://docs.microsoft.com/en-us/connectors/custom-connectors/policy-templates/expressions/expressions)
* Content Source: [docs/custom-connectors/policy-templates/expressions/expressions.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/policy-templates/expressions/expressions.md)
* Service: **connectors**
* GitHub Login: @schabungbam
* Microsoft Alias: **sameerch**

**Comment by v-aangie** [comment]
@filcole - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
