### ISSUE TITLE
The connection should be tested after adding it to Flow

### ISSUE THREAD

**Issue by DavidPaf** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#49]
Hi Team,

We should make a testconnection for this File System connection before showing that it is added successfully in Flow  =&gt; Data =&gt; Connections =&gt; Add connection.

I made an "add connection" test for this connector and even if I typed the login credential incorrectly (username without domain), it can still be added to the connection list.

This cause later usage like: "The Folders and files are not available" or "The requested action could not be completed. Check your request parameters to make sure the path '' exists on your file system".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e32f470-9966-6207-ed34-db39f7e79395
* Version Independent ID: a0654443-876d-3d36-afb7-189a559d4e9f
* Content: [File System - Connectors](https://docs.microsoft.com/en-us/connectors/filesystem/)
* Content Source: [docs/filesystem/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/filesystem/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment]
Hello, I'm not sure what the issue in the documentation you are reporting is - is this a feature request for the connector?

**Comment by v-aangie** [comment]
@DavidPaf - Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
