### ISSUE TITLE
Freshdesk custom fields cannot be updated using powerapps

### ISSUE THREAD

**Issue by roncam82** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#494]
Hi,

I cannot manage to update the custom fields of a freshdesk ticket using freshdesk connector in powerapps.

Can you help me please ?

Thanks
Ronald

**Comment by v-aangie** [comment]
@roncam82 - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
