### ISSUE TITLE
Cloud App Security needs to be replaced with Defender for Cloud Apps

### ISSUE THREAD

**Issue by dcurwin** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#495]
Cloud App Security has been renamed Defender for Cloud Apps. 

I'm responsible for Defender for Cloud Apps documentation. Feel free to be in contact with me if you have questions about the rebrand.

Thanks,

David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: daec7818-5d63-252b-b338-cdbfe883d644
* Version Independent ID: be170efb-921d-2ac1-0c44-ce1b6b6dff37
* Content: [Cloud App Security - Connectors](https://docs.microsoft.com/en-us/connectors/cloudappsecurity/)
* Content Source: [docs/cloudappsecurity/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/cloudappsecurity/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by dcurwin** [comment]
@miriver - any updates?

**Comment by v-aangie** [comment]
@dcurwin - Thanks for your feedback. We will soon look into this issue.
