### ISSUE TITLE
EventId not available for Google Calendar

### ISSUE THREAD

**Issue by hpkeong** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#496]
It is easy to Create an event into Google Calendar from PowerApps, using CreateEvent API as provided by PowerApps.
CalenderId = the registered email with Google. It is OK for me
[https://docs.microsoft.com/en-us/connectors/googlecalendar/](url)

But when I wish to 
- Delete
- Update
- Get
I was asked to fill-in EventId.
Where is EventId?

Pls help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 352d2e69-2be4-03c9-9fa8-f3b9795cab42
* Version Independent ID: 8889e801-9db2-aab1-ebf3-1340ae15f0f1
* Content: [Google Calendar - Connectors](https://docs.microsoft.com/en-us/connectors/googlecalendar/#when-an-event-is-updated-in-a-calendar)
* Content Source: [docs/GoogleCalendar/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/GoogleCalendar/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@hpkeong - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
