### ISSUE TITLE
Filesystem connector "root folder" example missing backslash on UNC path

### ISSUE THREAD

**Issue by joncojonathan** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#499]
Under the [_default_ heading](https://docs.microsoft.com/en-gb/connectors/filesystem/#default), the root folder examples suggest a file share.  The UNC path starts with a single backslash, whereas it should begin with a double backslash:

> Root folder path (examples: \MACHINE\myShare or C:\myShare)

should say

> Root folder path (examples: \\\MACHINE\myShare or C:\myShare)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e32f470-9966-6207-ed34-db39f7e79395
* Version Independent ID: a0654443-876d-3d36-afb7-189a559d4e9f
* Content: [File System - Connectors](https://docs.microsoft.com/en-gb/connectors/filesystem/)
* Content Source: [docs/filesystem/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/filesystem/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@joncojonathan - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.

**Comment by joncojonathan** [comment]
Hi @v-aangie, I'm not having a problem, I'm highlighting a bug in your documentation that requires a fix.  Is that something you're able to correct?
