### ISSUE TITLE
All caps?

### ISSUE THREAD

**Issue by nplima** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#5]
Hi,

My Flow picks up new records created in the Common Data Service, in the "Email Message" entity, to convert the contents of "description" field to plain text. The output I am getting in all in capital letters.
Is that unavoidable, or is there a setting I can adjust for the output?
Thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 413f88f9-2b3c-172b-a74a-a533fcd167de
* Version Independent ID: b9ee8f92-b5b8-f2a3-51e6-f93a7c913567
* Content: [Content Conversion - Connectors](https://docs.microsoft.com/en-us/connectors/conversionservice/#htmltotextresponse)
* Content Source: [docs/conversionservice/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/conversionservice/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by nplima** [comment]
Hi again.
That first test I made had a strange result, when I submitted the following HTML:
<h2 style="font-style:italic;"><strong>Title here</strong><br>
<br>
<u>Underline</u></h2>
<p><br>
<strong>BOLD</strong></p>


My other attempts worked, so it might be that the conversion just "disliked" the H2 tags.
I hope this helps.

**Comment by bezhan-msft** [comment]
Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback).
