### ISSUE TITLE
Undocumented OAuth2 restriction

### ISSUE THREAD

**Issue by CodingSinceThe80s** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#50]
Hello team,

I love the concept of connectors because one can securely use the client id and client secrets e.g. in the OAuth2-mechanism and let users do their thing.

However: There seems to be an undocumented issue here. The OAUTH2 flows supported seem to be only accesCode and (maybe) password. If I want e.g. the connector to log in as an application (Azure AD app created) in the Client Credential Flow (in Swagger it would mean flow: application) this does not work. Even if I edit the swagger live in the connector then save, it will revert to the accessCode flow. Please document this, it cost me a lot of trial-and-error to find this out. People are running into this and not getting any replies from Microsoft:
See  [PowerApps forum 1](https://powerusers.microsoft.com/t5/Connecting-To-Data/Custom-connector-to-connect-to-API-using-client-credentials/m-p/381623#M6740)
and also
[PowerApps forum 2](https://powerusers.microsoft.com/t5/Connecting-To-Data/Are-other-flow-than-accessCode-supported-by-OAuth2-custom/td-p/165448)
The user in the second thread resorted - like me - to using a plain HTTP action to get the token, which means storing the App Password **in plaintext** within the flow. 

In my opinion this is an indirect security issue and should be at least documented. Also it would be great to know if there are any plans to support the client credential grant flow any time soon.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f873de3b-82f2-8cbc-0de3-6dbdc968b9fa
* Version Independent ID: ca3ccf84-5de8-ef66-9bda-b804404b5085
* Content: [Custom connectors overview](https://docs.microsoft.com/en-us/connectors/custom-connectors/)
* Content Source: [docs/custom-connectors/index.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/index.md)
* Service: **connectors**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by bezhan-msft** [comment]
Thank you for your feedback. This is now under review and no further action is required at this time.

**Comment by v-aangie** [comment]
@CodingSinceThe80s - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.
