### ISSUE TITLE
Connector List

### ISSUE THREAD

**Issue by gregthece** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#506]
Please make the connector list downloadable in CSV format so that organizations can download and sort based on their criteria.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c86c88f7-3257-6f49-506b-af0c946028a4
* Version Independent ID: c8ba4300-9f35-ad5a-c279-2c6372d13914
* Content: [List of all Standard tier connectors](https://docs.microsoft.com/en-us/connectors/connector-reference/connector-reference-standard-connectors)
* Content Source: [docs/connector-reference/connector-reference-standard-connectors.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/connector-reference/connector-reference-standard-connectors.md)
* Service: **connectors**
* GitHub Login: @bezhan-msft
* Microsoft Alias: **bezhan**

**Comment by TamlinStryk** [comment]
A downloadable version of this list is really needed, I was able to scrap the names using Power BI from the following Links and then merge them together to get a full list.

https://docs.microsoft.com/en-us/connectors/connector-reference/connector-reference-powerapps-connectors
https://docs.microsoft.com/en-us/connectors/connector-reference/connector-reference-powerautomate-connectors

But this doesn't contain any other info like standard vs premium or Microsoft released connectors, really need an RSS feed or CSV that can be exported and sorted.

**Comment by v-aangie** [comment]
@gregthece - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
