### ISSUE TITLE
Note on delegable functions refers to wrong part of table

### ISSUE THREAD

**Issue by biterbit** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#508]
In the 'Power Apps delegable functions and operations for SharePoint' section, note 2 under the table state that 'The SharePoint ID field for a table is a number field in Power Apps. However, SharePoint only supports the equal ('=') operation for delegation on an ID field.' The table itself states that '=' is delegable for Number fields, whereas the note implies the opposite. The note is also tied to the table entry for '<, <=,<>, >, >=' rather than '='. Altogether this makes the section hard to interpret.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69a01872-3062-4100-f807-7d43e8111e9f
* Version Independent ID: 48560378-76ed-cb42-e816-894179e1f16d
* Content: [SharePoint - Connectors](https://docs.microsoft.com/en-us/connectors/sharepointonline/#power-apps-delegable-functions-and-operations-for-sharepoint)
* Content Source: [docs/sharepointonline/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/sharepointonline/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@biterbit - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
