### ISSUE TITLE
StartAndWaitForAnApproval action isn't supported of Power Apps(Canvas App)

### ISSUE THREAD

**Issue by tanimani** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#509]
The second parameter to Approvals.StartAndWaitForAnApproval() is a dynamic type which is not currently supported of Power Apps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc3be4e8-204a-a1f5-21ea-a289dc8a0583
* Version Independent ID: 167b2834-1025-136b-9c25-4ba80e3c3410
* Content: [Approvals - Connectors](https://docs.microsoft.com/en-us/connectors/approvals/)
* Content Source: [docs/Approvals/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Approvals/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@tanimani - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
