### ISSUE TITLE
Business Central (on-premises) Unable to specify journalId for create journalLines

### ISSUE THREAD

**Issue by IllumiC** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#511]
_ErrorCode: Application_DialogException  You must specify a journal batch ID or a journal ID to get a journal line._
Despite this, there is no where to enter a journal batch ID or journal ID.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f4d9705-254f-c3ee-88c1-a483aa280a51
* Version Independent ID: 33d3527e-bc1b-ea89-79e5-c40efcdd9f5b
* Content: [Business Central (on-premises) - Connectors](https://docs.microsoft.com/en-us/connectors/dynamicssmbonprem/)
* Content Source: [docs/dynamicssmbonprem/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/dynamicssmbonprem/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@IllumiC - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
