### ISSUE TITLE
Power BI Actions work in GCC

### ISSUE THREAD

**Issue by Hikmer** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#513]
These Power BI actions are now available and working in Government Community Cloud.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1214f622-5b88-afa0-54cb-eae8ea4b3bfd
* Version Independent ID: d5efdba5-d278-73e4-1571-13abe8474c40
* Content: [Power BI - Connectors](https://docs.microsoft.com/en-us/connectors/powerbi/#known-issues-and-limitations)
* Content Source: [docs/PowerBI/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/PowerBI/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@Hikmer - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
