### ISSUE TITLE
Please set the RSS feed to this page

### ISSUE THREAD

**Issue by reshimiz** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#514]
We are white listing the Power Platform IP address.
Currently, there is no way to notice the change of this article besides checking manually by ourselves.

It's really great if you set the RSS feed to this page.
Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80b88b63-df14-773f-5a88-8b2ea1157665
* Version Independent ID: a0da6c99-a285-9904-b52f-e1a2cc2426d5
* Content: [Managed connectors outbound IP addresses](https://docs.microsoft.com/en-us/connectors/common/outbound-ip-addresses)
* Content Source: [docs/common/outbound-ip-addresses.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/common/outbound-ip-addresses.md)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@reshimiz - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
