### ISSUE TITLE
Port/protocols?

### ISSUE THREAD

**Issue by JSaaS** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#515]
[Enter feedback here]
Hi,

Missing information on what fileshare protocol and subsequently what ports the connector talks over from the on-premise part. is it Samba and port 445?

/Joakim

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e32f470-9966-6207-ed34-db39f7e79395
* Version Independent ID: a0654443-876d-3d36-afb7-189a559d4e9f
* Content: [File System - Connectors](https://docs.microsoft.com/en-us/connectors/filesystem/)
* Content Source: [docs/filesystem/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/filesystem/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@JSaaS - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
