### ISSUE TITLE
HTTP Azure AD Connect not in base64

### ISSUE THREAD

**Issue by samadane** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#516]
https://docs.microsoft.com/en-us/connectors/webcontents/#known-issues-and-limitations

1.	The connector encodes the request body into base64 encoding, hence it should be used to call backend services which expect the request body in this format. You cannot use this connector to call a backend service that expects the request body in raw binary format.

I am not seeing my request body encoded.  Has this been fixed?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ce7ba1f-e39a-b6d7-dcd3-0bba96f28e92
* Version Independent ID: f254a24f-6004-849f-d566-10d7d3e87779
* Content: [HTTP with Azure AD - Connectors](https://docs.microsoft.com/en-us/connectors/webcontents/#known-issues-and-limitations)
* Content Source: [docs/webcontents/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/webcontents/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@samadane - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
