### ISSUE TITLE
ServiceNow Connector

### ISSUE THREAD

**Issue by morencigirl** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#52]
Does this connector support the Madrid and Orlando versions of ServiceNow

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00a0a61d-f2fc-aa31-042b-0b472c8bff1c
* Version Independent ID: 1650d41c-0ec7-d8b4-a98b-5f96bc8b0bdb
* Content: [ServiceNow - Connectors](https://docs.microsoft.com/en-us/connectors/service-now/)
* Content Source: [docs/service-now/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/service-now/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment]
Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) or to the connector-specific support contact (if applicable).
