### ISSUE TITLE
Please give more information about permission scope

### ISSUE THREAD

**Issue by reshimiz** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#523]
We can't identify what scope does HTTP with Azure AD connector have.
Please update this article with the information of allowed permissions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ce7ba1f-e39a-b6d7-dcd3-0bba96f28e92
* Version Independent ID: f254a24f-6004-849f-d566-10d7d3e87779
* Content: [HTTP with Azure AD - Connectors](https://docs.microsoft.com/en-us/connectors/webcontents/)
* Content Source: [docs/webcontents/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/webcontents/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by Mike-Crowley** [comment]
Agreed. This connector has limited capability if it is locked out of most of graph due to a short list of scopes.

**Comment by v-aangie** [comment]
@reshimiz - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.

**Comment by Mike-Crowley** [comment]
The question was for Microsoft to document the product, not that they were "experiencing issues"


- Mike Crowley
________________________________
