### ISSUE TITLE
requires clarity

### ISSUE THREAD

**Issue by nkatz01** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#524]
"App Service Environment to host connector webapps" not sure what connector webapps are. Is only mentioned once on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05311999-5cc3-eb54-779a-5340392b6437
* Version Independent ID: f6958b1c-6fc9-fd34-1535-eef6e36ef793
* Content: [Power Platform connectors overview](https://docs.microsoft.com/en-us/connectors/connectors)
* Content Source: [docs/connectors.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/connectors.md)
* Service: **connectors**
* GitHub Login: @asavaritayal
* Microsoft Alias: **angieandrews**

**Comment by v-aangie** [comment]
@nkatz01 - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
