### ISSUE TITLE
List connectors action in Power Automate doesn't return Independent Publishers connectors

### ISSUE THREAD

**Issue by vbapis** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#528]
Independent publishers connectors are not listed in the ["List Connectors"](https://docs.microsoft.com/en-us/connectors/flowmanagement/#list-connectors) returned output.
Steps to reproduce:
Create a Flow with "List Connectors" Power Automate Management action
Run -> Validate the output -> search for any Independent Publishers connectors

[List Connectors](https://docs.microsoft.com/en-us/connectors/flowmanagement/#list-connectors) Doesn't return all connectors and should be fixed to include Independent publishers connectors.

**Comment by v-aangie** [comment]
@vbapis - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
