### ISSUE TITLE
Japanese pages are corrupted

### ISSUE THREAD

**Issue by reshimiz** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#529]
Hi team, 
the Japanese version of connector references are corrupted.
- Action names are not correct
- in parameter section of each action, name column and explanation column are switced.
- Some deprecated actions' name are not shown.

Please fix them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63dd2d5e-d90f-4654-c406-256e3e680e6d
* Version Independent ID: f2cd384b-2690-393d-3058-a363523f7d62
* Content: [Excel Online (Business) - Connectors](https://docs.microsoft.com/en-us/connectors/excelonlinebusiness/#general-known-issues-and-limitations)
* Content Source: [docs/excelonlinebusiness/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/excelonlinebusiness/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@reshimiz - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
