### ISSUE TITLE
Logic Apps > Dynamically SQL database configuration

### ISSUE THREAD

**Issue by kanwarkakkar** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#53]
In Logic Apps, we can connect to the SQL Database by manually putting the required credentials in the connector's dialog box.
Can we dynamically create SQL connection through code view by fetching credentials ( e.g. Fetching credentials through Azure KeyVault)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58c0b60a-fdc5-6ce7-e73f-c5071c0f9356
* Version Independent ID: 5865c7d1-abc2-4a70-56dd-4ebef0b411c4
* Content: [SQL Server - Connectors](https://docs.microsoft.com/en-us/connectors/sql/#feedback)
* Content Source: [docs/Sql/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Sql/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment]
Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) or to the connector-specific support contact (if applicable).
