### ISSUE TITLE
Get container image without using ACR username and password? i.e. using Managed Identity

### ISSUE THREAD

**Issue by vikramdadwal** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#532]
I am using Logic app to create ACI Container group. I want to use managed identity to pull the container image from ACR, instead of using UserName and password to connect to the ACR. How to accomplish the same ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fdac925-5f7a-fad6-036e-1a9d92f23fef
* Version Independent ID: 98799be2-767f-6dbf-600e-b68c1e4d935e
* Content: [Azure Container Instance - Connectors](https://docs.microsoft.com/en-us/connectors/aci/#create-or-update-a-container-group)
* Content Source: [docs/aci/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/aci/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@vikramdadwal - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.

**Comment by vikramdadwal** [comment]
@v-aangie : The issue still persists as there is not option to use Managed Identity in the connector and our security team has raised flag for this. Please assist here.
