### ISSUE TITLE
Trigger for "When a file is created" needs a note on file may not be uploaded

### ISSUE THREAD

**Issue by RaulSimplicio-MSFT** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#533]
Hello,

In this article, sections "[When a file is created in a folder](https://docs.microsoft.com/en-us/connectors/sharepointonline/#when-a-file-is-created-in-a-folder)" and "[When a file is created or modified in a folder](https://docs.microsoft.com/en-us/connectors/sharepointonline/#when-a-file-is-created-or-modified-in-a-folder)" should have a note mentioning the trigger may occur while the file content itself is still uploading.

Something in the lines of <**Note**: Trigger will occur when upload begins and item is created. File may not be fully uploaded when trigger occurs>.

Similar situation for section "[When a file is created or modified (properties only)](https://docs.microsoft.com/en-us/connectors/sharepointonline/#when-a-file-is-created-or-modified-(properties-only))", as property \<File Size\> will show as 0 (zero), while the file is still uploading, changing to the actual file size when upload completes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69a01872-3062-4100-f807-7d43e8111e9f
* Version Independent ID: 48560378-76ed-cb42-e816-894179e1f16d
* Content: [SharePoint - Connectors](https://docs.microsoft.com/en-us/connectors/sharepointonline/#when-a-file-is-created-in-a-folder)
* Content Source: [docs/sharepointonline/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/sharepointonline/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@RaulSimplicio-MSFT - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
