### ISSUE TITLE
The list of IP addresses is different than what is showing in Azure Logic Apps connector IP addresses

### ISSUE THREAD

**Issue by jonnametso** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#534]
Hi,

How often is Microsoft adding new IP addresses to these products? We have had incidents lately when vendor has done firewall openings in their side for a certain and already HUGE IP address range. And then suddenly our integrations go into error because a new set of IP Addresses have been opened to the Logic Apps West Europe region and those haven't been opened in vendor side. 
We also have vendors who cannot even open such big range.. 

Also your documentation in this page is showing slightly different IP Addresses than what is shown in the Azure Logic Apps as Connector IP addresses. 

In Logic Apps Connector IP addresses:
52.174.88.118, 40.91.208.65, 13.69.64.208**/28**, 13.69.71.192/27, 13.93.36.78, 20.86.93.32/**27**, 20.86.93.64**/28**, 20.126.243.151, 20.126.241.238, 20.103.132.139, 20.103.131.1

In your page IP addresses:
40.68.222.65, 40.68.209.23, 13.95.147.65, 23.97.218.130, 51.144.182.201, 23.97.211.179, 104.45.9.52, 23.97.210.126, 13.69.71.160, 13.69.71.161, 13.69.71.162, 13.69.71.163, 13.69.71.164, 13.69.71.165, 13.69.71.166, 13.69.71.167, 20.103.21.81, 20.103.17.247, 20.103.17.223, 20.103.16.47, 20.103.58.116, 20.103.57.29, 20.101.174.49, 20.101.174.23, 20.93.236.26, 20.93.235.107, 20.103.94.250, 20.76.174.72, 20.82.87.192, 20.82.87.16, 20.76.170.145, 20.103.91.39, 20.103.84.41, 20.76.161.156

BR,
Jonna

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80b88b63-df14-773f-5a88-8b2ea1157665
* Version Independent ID: a0da6c99-a285-9904-b52f-e1a2cc2426d5
* Content: [Managed connectors outbound IP addresses](https://docs.microsoft.com/en-us/connectors/common/outbound-ip-addresses)
* Content Source: [docs/common/outbound-ip-addresses.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/common/outbound-ip-addresses.md)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by ReDaCtD** [comment]
Running into a similar issue, we use a logic App to migrate critical data and our clients are reporting inconsistency and I'm now seeing all timeouts since 3/28 around 10:30 AM ET, I assume that was when the IP ranges were revised. Is there any advanced notice about these range changes or simple recommendations to avoid this issue with a static IP for a logic app?

**Comment by v-aangie** [comment]
@jonnametso - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
