### ISSUE TITLE
API limitations missing

### ISSUE THREAD

**Issue by thomasbragaloni** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#537]
[Enter feedback here]
The Export to file section doesn't explain or link to the API limitation that the report will be exported EVEN IF there is an error in visualization, as long as the report URL loads

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1214f622-5b88-afa0-54cb-eae8ea4b3bfd
* Version Independent ID: d5efdba5-d278-73e4-1571-13abe8474c40
* Content: [Power BI - Connectors](https://docs.microsoft.com/en-us/connectors/powerbi/#export-to-file-for-power-bi-reports)
* Content Source: [docs/PowerBI/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/PowerBI/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@thomasbragaloni - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
