### ISSUE TITLE
implement some more comprehensive samples for these connectors

### ISSUE THREAD

**Issue by roalexan** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#538]
It's entirely possible that I've missed them, but it would be great if there were more comprehensive samples to go along with all of these various connectors APIs. For example, I've filed this Stackoverflow issue - [Get list of all blobs in powerapp using AzureBlobStorage.ListFolderV4](https://stackoverflow.com/questions/71834875/get-list-of-all-blobs-in-powerapp-using-azureblobstorage-listfolderv4) - because I couldn't find any example showing me how to get all the blobs for a container if they are in folders. How to use the paging marker? The syntax for using useFlatListing? The sample [Connect to Azure Blob Storage from Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/canvas-apps/connections/connection-azure-blob-storage) was good to get started, but it's not comprehensive enough.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4a1ef15-eee8-e31f-e05d-34ae84216545
* Version Independent ID: 01cf0d74-3e50-c6c9-fe0d-7d639886318c
* Content: [Azure Blob Storage - Connectors](https://docs.microsoft.com/en-us/connectors/azureblob/)
* Content Source: [docs/azureblob/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/azureblob/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by roalexan** [comment]
and as I mentioned in the stackoverflow issue, I can't seem to get listing the blobs for a folder under the container to work.

**Comment by v-aangie** [comment]
@roalexan - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
