### ISSUE TITLE
MSNWeather CurrentWeather action fails when weather is not found

### ISSUE THREAD

**Issue by last72** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#539]
When the API cannot find weather information for the given location, it fails.

![image](https://user-images.githubusercontent.com/30095306/162910786-fd1fea21-b5bb-4bde-9f29-94906c15b942.png)

Example above: MSNWeather.CurrentWeather("Woong", "Metric").responses.weather.current.temp

Response body:
```
"body": {
    "responses": [
      {
        "error": {
          "code": "LocationNotFound"
        }
      }
    ],
    "units": {
      "system": "Metric",
      "pressure": "mb",
      "temperature": "‎°C",
      "speed": "km/h",
      "height": "cm",
      "distance": "km",
      "time": "s"
    },
    "copyright": "Copyright © 2022 Microsoft and its suppliers. All rights reserved. This API cannot be accessed and the content and any results may not be used, reproduced or transmitted in any manner without express written permission from Microsoft Corporation."
  }
```

![image](https://user-images.githubusercontent.com/30095306/162911258-86cafae0-8e60-4d8d-84f3-9e84010edc5f.png)

It should not fail on formula level and should fail gracefully.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bbeba7f-5c07-3fa6-2d19-d973fb3be68c
* Version Independent ID: 30c3272f-550b-66da-4554-baffe0185e61
* Content: [MSN Weather - Connectors](https://docs.microsoft.com/en-us/connectors/msnweather/)
* Content Source: [docs/MsnWeather/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/MsnWeather/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@last72 - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
