### ISSUE TITLE
rss

### ISSUE THREAD

**Issue by Sidpao** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#54]
[Angiv feedback her]

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: e00bcf3a-a5c1-0c9b-71ef-095a008cba85
* Version Independent ID: abc941c4-8750-993f-d85a-c42ae7922b89
* Content: [RSS - Connectors](https://docs.microsoft.com/da-dk/connectors/rss/#when-a-feed-item-is-published)
* Content Source: [docs/RSS/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/RSS/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment]
Hello - this issue has been closed due to lack of information. If you have more information to provide, please reopen this issue.
