### ISSUE TITLE
The documentation shows an incorrect parameter

### ISSUE THREAD

**Issue by IvanFerrante92** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#540]
The documentation shows an incorrect parameter: "-AssignableScope" not exists the correct parameter is "-Scope"
https://docs.microsoft.com/en-us/connectors/documentdb/#azure-ad-authentication-and-cosmos-db-connector

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6de37f0-2e5d-f0ee-bbf9-c6f5d7cdd6e6
* Version Independent ID: 4db5c39c-b2fb-9ed5-598c-6901fd17d3e3
* Content: [Azure Cosmos DB - Connectors](https://docs.microsoft.com/en-us/connectors/documentdb/#azure-ad-authentication-and-cosmos-db-connector)
* Content Source: [docs/DocumentDB/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/DocumentDB/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@IvanFerrante92 - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
