### ISSUE TITLE
Still not compatible with Form Recognizer Studio (API v3)

### ISSUE THREAD

**Issue by emelus** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#541]
It's been a few months since Studio or API v3 has been released, and the portal still does not produce Model IDs that can be used to implement the models created e.g. for Logic Apps. Yet, the FOTT main page recommends migration to v3

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e84d6396-2e1e-2c2b-3c15-28c34c3d0557
* Version Independent ID: 4b1b05aa-bcab-57f6-9f6d-6ed2014d6d75
* Content: [Form Recognizer - Connectors](https://docs.microsoft.com/en-us/connectors/formrecognizer/#analyze-custom-form)
* Content Source: [docs/formrecognizer/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/formrecognizer/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@emelus - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
