### ISSUE TITLE
Columns in Combobox

### ISSUE THREAD

**Issue by hehe13** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#542]
I need help in populating the information of a Column/s on my powerapp Combobox.

I have a smartsheet with US States as column and I want a Combobox in my powerapp to populate that information. I have tried several ways but unsuccessful.

I have reached out to SmartSheet but as of now no one has able to provide a solution. I am hoping you can help.

https://community.smartsheet.com/discussion/89752/smartsheet-in-powerapps-combobox#latest

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af9eb553-4845-df5e-1a64-75cc167998e5
* Version Independent ID: 2f9f8ae2-65dd-9c90-d1a2-071f181d6aad
* Content: [Smartsheet - Connectors](https://docs.microsoft.com/en-us/connectors/smartsheet/)
* Content Source: [docs/Smartsheet/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Smartsheet/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@hehe13 - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
