### ISSUE TITLE
Page Duty Question on Title

### ISSUE THREAD

**Issue by golden-kang** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#544]
[Enter feedback here]
Question: I am using Power Automate to create incident in PagerDuty.
I created an incident with service key and description which is exactly what this page tells. However, I am seeing "No message included" for the title of the incident. Is this a known issue or I need to create the incident in other ways?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dea53d5-ae0a-2de7-128f-f92cc5d87d55
* Version Independent ID: c36c32a9-2e1c-bebf-9fd4-7bf7cb02b95f
* Content: [PagerDuty - Connectors](https://docs.microsoft.com/en-us/connectors/pagerduty/#feedback)
* Content Source: [docs/PagerDuty/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/PagerDuty/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by golden-kang** [comment]
Finally, I resolved this issue. Power Automate is using Pager Duty API Version 1. Therefore, the integration key should be version's. Maybe it would be better to mention API version in the doc. Or link  this page: https://www.pagerduty.com/docs/guides/microsoft-azure-logic-apps-integration-guide/
:)

**Comment by v-aangie** [comment]
@golden-kang - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
