### ISSUE TITLE
Missing throttling limit for Notification connector 

### ISSUE THREAD

**Issue by NinhGreen123** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#547]
Document : Missing throttling limit for Notification connector : 5 calls/5 mins 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08c4052e-505b-7fe0-8e22-02babc35e8fd
* Version Independent ID: 53d8826f-35bf-d089-efa9-5b48e19d6da4
* Content: [Notifications - Connectors](https://docs.microsoft.com/en-us/connectors/flowpush/)
* Content Source: [docs/FlowPush/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/FlowPush/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@NinhGreen123 - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
