### ISSUE TITLE
Not all events fire Upcoming Event trigger.

### ISSUE THREAD

**Issue by devlinl** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#549]
In the section "When an upcoming event is starting soon (V3)" the only description is "This operation triggers a flow when an upcoming calendar event is starting."

However, it seems that not all events will trigger this flow. For example, I created a multi-day, All day, appointment, and this flow was not triggered for it.

Please update this documentation to provide clearer information on what events will actually trigger this flow and what events won't.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc40a098-af8c-d8a9-4538-71d184efbe91
* Version Independent ID: 0ee8cf79-18e9-d923-607f-ef40cdd23e4d
* Content: [Office 365 Outlook - Connectors](https://docs.microsoft.com/en-us/connectors/office365/#when-an-upcoming-event-is-starting-soon-(v3))
* Content Source: [docs/office365/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/office365/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@devlinl - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
