### ISSUE TITLE
NotFound error when using NewPullRequest trigger for org repos

### ISSUE THREAD

**Issue by arunavs49** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#550]
I am unable to connect to a repository that belongs to an organization when using New Pull Request created trigger. For repository name I am using <org>/<repo name>. Is that the expected format or its something different? I keep getting a NotFound error. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90cc63c5-330d-3be1-73c7-ef14c3531007
* Version Independent ID: 16bc26a2-2aee-7438-40b3-30732c7ed1f8
* Content: [GitHub - Connectors](https://docs.microsoft.com/en-us/connectors/github/#when-a-pull-request-is-created-or-modified)
* Content Source: [docs/GitHub/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/GitHub/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@arunavs49 - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
