### ISSUE TITLE
Are dashes ok in phone numbers for Twilio texting?

### ISSUE THREAD

**Issue by b1c1jones** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#554]
Are dashes ok in phone numbers for Twilio texting?

`<html>
<body>

To Phone Number | to | True | string | The destination phone number. Format with a '+' and country code e.g., +16175551212 (E.164 format).
-- | -- | -- | -- | --

</body>
</html>`
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bce87de8-1bf9-ecb8-1d6e-aa337db9cbdb
* Version Independent ID: 99a52156-b21a-0d5b-0f38-aa14e2ede2fa
* Content: [Twilio - Connectors](https://docs.microsoft.com/en-us/connectors/twilio/#send-text-message-(sms))
* Content Source: [docs/Twilio/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Twilio/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@b1c1jones - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
