### ISSUE TITLE
Need Python/Rest Api sample guide how to create connector

### ISSUE THREAD

**Issue by MaiHoangViet1809** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#556]
[Enter feedback here]
I did not see any sample code how to create these connector via python or Rest API, please update, thank.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfa775a4-1c3d-39da-b33c-f3fa525bf916
* Version Independent ID: 6b3f07eb-e541-425c-30eb-6dacd8e4d561
* Content: [SMTP - Connectors](https://docs.microsoft.com/en-us/connectors/smtp/#feedback)
* Content Source: [docs/smtp/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/smtp/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@MaiHoangViet1809 - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
