### ISSUE TITLE
Null or error on "Get User (V2)"

### ISSUE THREAD

**Issue by ssimo3lsuhsc** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#558]
I'm asking for help because I need to program my flow in the event a user cannot be found. My e-mail address is "ssimo3@lsuhsc.edu." There is nobody at my institution with the e-mail address of "ssimo4@lsuhsc.edu." If I were to enter "ssimo4@lsuhsc.edu" in the input of a "Get User (V2)" action, what would happen?

a. It would return the value `null`
b. It would throw an error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8635712-d5a2-e58a-301f-cf849f2cf2e4
* Version Independent ID: 4cfdd73e-f074-0446-2aee-2dd013a8b30f
* Content: [Office 365 Users - Connectors](https://docs.microsoft.com/en-us/connectors/office365users/#get-user-profile-(v2))
* Content Source: [docs/office365users/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/office365users/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@ssimo3lsuhsc - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
