### ISSUE TITLE
Still unclear what steps are expected to work for M365 Government customers.

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#559]
This was the line added to the [Known Issues and Limitations ](https://docs.microsoft.com/en-us/connectors/teams/#known-issues-and-limitations) list:

15. Actions that use the Power Automate bot are not supported in sovereign clouds (GCC, GCCH, DoD)

This does not actually help folks know which actions are supposed to work or not work. "Power Automate bot" isn't mentioned anywhere else in the article. Assuming it is the same as the "Flow bot", only some of the broken actions explicitly have "Flow bot" in the title/description. There is no way for a GCC user to know that actions like "[Post an adaptive card and wait for a response](https://docs.microsoft.com/en-us/connectors/teams/#post-adaptive-card-and-wait-for-a-response)" are not expected to work.

Could the document be updated? Something like change "Power Automate bot" to "Flow Bot" and either:

1. Include a list of unsupported actions in the Known Issues entry, or

2. Update the description of all the actions that leverage the Flow bot.

Thanks for your help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb4ba692-98a2-2ec7-319b-d75b59d3fa50
* Version Independent ID: c24a9495-e4cb-28db-3657-ecf81005757b
* Content: [Microsoft Teams - Connectors](https://docs.microsoft.com/en-us/connectors/teams/)
* Content Source: [docs/Teams/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Teams/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@npherson - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.

**Comment by npherson** [comment]
@v-aangie  - this feedback item is for a docs issue and there are separate conversations about getting the underlying product issues resolved.

![image](https://user-images.githubusercontent.com/22797301/174132510-9139d5a8-5332-48e6-abb3-566c4a305c57.png)

Is "Power Automate bot" synonymous with "Flow bot"? If so, can we pick one term?

And the doc needs to explicitly state which actions are not supported...   you can't infer it since not all the steps have 'flow bot' in the name.
