### ISSUE TITLE
Move File

### ISSUE THREAD

**Issue by DrewBino** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#56]
Can any of the actions be used to "move" a file?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e32f470-9966-6207-ed34-db39f7e79395
* Version Independent ID: a0654443-876d-3d36-afb7-189a559d4e9f
* Content: [File System - Connectors](https://docs.microsoft.com/en-us/connectors/filesystem/#feedback)
* Content Source: [docs/filesystem/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/filesystem/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment]
Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) or to the connector-specific support contact (if applicable).
