### ISSUE TITLE
Update action through API

### ISSUE THREAD

**Issue by honzakostejn** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#561]
[Enter feedback here]
Not sure if updating of connector is supported:
![image](https://user-images.githubusercontent.com/32060653/167617911-b6d17cdd-92be-4332-94b4-6b103dd1640e.png)
![image](https://user-images.githubusercontent.com/32060653/167618087-4ea7a27d-29eb-4541-86bf-ff2019401aaa.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9176238e-97ed-366b-cc6f-3bdcc5071205
* Version Independent ID: 9176238e-97ed-366b-cc6f-3bdcc5071205
* Content: [Manage solution custom connectors with Dataverse APIs](https://docs.microsoft.com/en-us/connectors/custom-connectors/solution-custom-api)
* Content Source: [docs/custom-connectors/solution-custom-api.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/solution-custom-api.md)
* Service: **connectors**
* GitHub Login: @samrat-gavale
* Microsoft Alias: **sagavale**

**Comment by v-aangie** [comment]
@honzakostejn - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
