### ISSUE TITLE
Returning JSON vs text

### ISSUE THREAD

**Issue by Blackbaud-BenLambert** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#563]
On this page, there are examples of using `CreateJsonContent` to return a message in the response body, like this:
```
response.Content = CreateJsonContent($"Unknown operation ID '{this.Context.OperationId}'");
```

I believe CreateJsonContent also sets `Content-Type: application/json`.  But in the above example, the response won't actually be json it will just be the text string (for example) "Unknown operation ID 'foo'".  

Maybe consider rewriting to something like this:
```
    response.Content = CreateJsonContent(new JObject
    {
        ["message"] = $"Unknown operation ID '{this.Context.OperationId}'"
    }.ToString());
```

Also, there are a few unnecessary trailing commas:

`["greeting"] = "Hello World!",`

`["isMatch"] = rx.IsMatch(textToCheck),`

`["wrapped"] = result,`

Lastly, the `IScriptContext` interface documentation on this page is missing the `CreateNotificationUrl` method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0293dbc2-1f0f-ff7b-d155-536fdcbfbc9d
* Version Independent ID: 710f2fe8-ca11-2a2f-2faa-86749a42b55a
* Content: [Write code in a custom connector](https://docs.microsoft.com/en-us/connectors/custom-connectors/write-code)
* Content Source: [docs/custom-connectors/write-code.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/write-code.md)
* Service: **connectors**
* GitHub Login: @shgogna
* Microsoft Alias: **shgogna**

**Comment by v-aangie** [comment]
@Blackbaud-BenLambert - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.

**Comment by Blackbaud-BenLambert** [comment]
@v-aangie Hi - just following up on this, looking at the updated page I don't see any mention of `CreateNotificationUrl` in the IScriptContext interface.
