### ISSUE TITLE
Any solution to the 5MB limit

### ISSUE THREAD

**Issue by saadzag** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#564]
Hello,
Is there any alternative solution to bypass the 5MB limit?

HTMl to Text Connector

**Comment by v-aangie** [comment]
@saadzag - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
