### ISSUE TITLE
OpenAPI files in yaml format

### ISSUE THREAD

**Issue by sayanghosh123** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#565]
Could this method be extended with OpenAPI files in yaml format as well, so we don't have to do that externally? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9659a345-1116-5020-4300-386f3a591c2e
* Version Independent ID: e2a3861f-d3d5-f542-28db-1897d4c7feb0
* Content: [Create a custom connector from an OpenAPI definition](https://docs.microsoft.com/en-us/connectors/custom-connectors/define-openapi-definition)
* Content Source: [docs/custom-connectors/define-openapi-definition.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/define-openapi-definition.md)
* Service: **connectors**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by v-aangie** [comment]
@sayanghosh123 - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
