### ISSUE TITLE
Allow for restarting a specific deployment slot

### ISSUE THREAD

**Issue by paulthegreen** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#566]
Currently there is no option to restart a specific deployment slot, only the main application.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c83bf38-c837-b4be-9bcb-f7ac9b5cb728
* Version Independent ID: 068a610c-a523-df77-b592-34dd35a9e404
* Content: [Azure App Service - Connectors](https://docs.microsoft.com/en-gb/connectors/azureappservice/#restart-web-app)
* Content Source: [docs/azureappservice/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/azureappservice/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by v-aangie** [comment]
@paulthegreen - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
