### ISSUE TITLE
Notion (Independent Publisher) : Always get this message when trying to use updateblock 

### ISSUE THREAD

**Issue by fbeauvais** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#569]
Could not find block with ID: bae71c5b-a766-4603-XXXXXX. Make sure the relevant pages and databases are shared with your integration. The block exist, and it's a todo list in Notion.

Error
Action 'Update_a_block_(to-do)' failed
Could not find block with ID: d9616241-7524-48f4-8fad-59b68be7ce37. Make sure the relevant pages and databases are shared with your integration.

Here my source PowerApp code. I just added XXXX to my API key and block id. 

{
    "method": "patch",
    "headers": {
        "Content-Type": "application/json",
        "Notion-Version": "2021-08-16"
    },
    "path": "/blocks/bae71c5ba766460XXXXXXXX",
    "host": {
        "api": {
            "runtimeUrl": "https://flow-apim-msmanaged-na-northcentralus-01.azure-apim.net/apim/notionip"
        },
        "connection": {
            "name": "/providers/Microsoft.PowerApps/apis/shared_notionip/connections/shared-notionip-980641f5-d2c8-421d-XXXXXX"
        }
    },
    "authentication": {
        "scheme": "Key",
        "parameter": "*sanitized*",
        "type": "Raw"
    },
    "body": {
        "to_do": {
            "text": [
                {
                    "text": {
                        "content": "Moon"
                    }
                },
                {
                    "text": {
                        "content": "2022-06-09T10:00:00Z"
                    }
                }
            ]
        }
    }
}

**Comment by v-aangie** [comment]
@fbeauvais - Thanks for contacting us. If you’re still experiencing any issues, please submit a message on one of our community forums. To help you choose the forum that best describes your issue, go to [Provide feedback or get help for connectors | Microsoft Docs](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) We’re closing this issue.
