### ISSUE TITLE
Dead Link in Planner Connector Documentation

### ISSUE THREAD

**Issue by iUnknwn** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#570]
The [planner connector documentation](https://docs.microsoft.com/en-us/connectors/planner/#create-a-task) includes a link at the beginning of the page:

```markdown
For more information, please refer to [Planner API Docs](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/planner_overview)
```

However, the link is broken - clicking on the link leads to a 404.

**Comment by v-aangie** [comment]
@iUnknwn - Per our recent discussion, we'll work on this issue along with your other issue, [Additional Details on Locating Planner's Group ID · Issue #423 · MicrosoftDocs/BusinessApplicationPlatform-Connectors-public (github.com)](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors-public/issues/423). Both issues should remain closed. Thanks!
