### ISSUE TITLE
Power canvas unable to make full use of MyProfileV2 and UserProfileV2  Graph data

### ISSUE THREAD

**Issue by eversonl** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#571]
Hi, this is accessible via flow
`{ "host": { "connectionReferenceName": "shared_office365users", "operationId": "UserProfile_V2" }, "parameters": { "id": "joe@xxx.xx.xx", "$select": "onPremisesExtensionAttributes,jobTitle,mail" } }`

but there seems to be no way of getting to this via power canvas
what would the equivalent syntax be? `Office365Users.MyProfileV2({'$select':onPremisesExtensionAttributes}).extensionAttribute1`
which does not work in canvas
while the below does
`Office365Users.MyProfileV2({'$select':"jobTitle"}).jobTitle
`
this would also need fixing in **UserProfileV2** too

**Comment by v-aangie** [comment]
@eversonl - If this is regarding a specific documentation article, please let us know. If not, please choose the appropriate forum as described in this link to post your issue: https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback Thanks!

**Comment by v-aangie** [comment]
@eversonl - Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
