### ISSUE TITLE
Power Automate Teams connector failing with "Exception has been thrown by the target of an invocation"

### ISSUE THREAD

**Issue by cfernandes-muhimbi** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#572]
Create a chat action fails with the Exception - ""Exception has been thrown by the target of an invocation"

![image](https://user-images.githubusercontent.com/25176106/185971021-62564f00-7f78-48fc-b704-4799e1353798.png)

{
  "error": {
    "code": "BadRequest",
    "message": "Exception has been thrown by the target of an invocation.",
    "innerError": {
      "date": "2022-08-22T16:18:54",
      "request-id": "470dbe0b-3134-4acb-bad0-5ae0681b3b76",
      "client-request-id": "470dbe0b-3134-4acb-bad0-5ae0681b3b76"
    }
  }
}

The same was highlighted in the Power Automate Form on the thread - https://powerusers.microsoft.com/t5/Building-Flows/Forms-dynamic-content-not-supported-for-Microsoft-Teams/m-p/1720000#M190673

**Comment by cfernandes-muhimbi** [comment]
Another complaint from the Forum - I've created a flow: I successfully collect emails of users for further chat creation but Teams chat is not created in the end. The flow fails with the error Action 'Create_a_chat' failed, error details: Exception has been thrown by the target of an invocation.

https://powerusers.microsoft.com/t5/Using-Flows/Start-a-flow-from-a-SharePoint-list/m-p/1734762#M32757

**Comment by v-aangie** [comment]
@cfernandes-muhimbi - We're sorry you're experiencing issues. I've reached out to the team to help resolve this.

**Comment by afrahman-MS** [comment]
This usually mean bad input was supplied. It is probably the chat members. Can you ensure they were correctly supplied and separated by semicolons?

**Comment by v-aangie** [comment]
@cfernandes-muhimbi - Please see Afreen's comment above. Thanks!

**Comment by v-aangie** [comment]
@cfernandes-muhimbi - Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
