### ISSUE TITLE
Blank PDF for Convert Word Document to PDF

### ISSUE THREAD

**Issue by baylosb** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#58]
I had the problem of a blank pdf coming through from the PowerAutomate action "Convert Word Document to PDF".  To resolve I just needed to remove the / at the start of the file name

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d39ce977-b1fc-d4be-3776-ad31a5b780ec
* Version Independent ID: 21c81572-7742-f033-cdc1-07c1090e9878
* Content: [Word Online (Business) - Connectors](https://docs.microsoft.com/en-us/connectors/wordonlinebusiness/#feedback)
* Content Source: [docs/wordonlinebusiness/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/wordonlinebusiness/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment]
Thank you for your feedback - am I understanding correctly that the original issue you had was that your path to the file was incorrect (had an extra / at the beginning?) 

Or is there an issue with incorrect documentation on the page? The examples do not contain a / at the beginning of the file path

**Comment by v-aangie** [comment]
@baylosb - Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue in one of the forums listed in https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback.
