### ISSUE TITLE
GCC Region Support

### ISSUE THREAD

**Issue by rywilli** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#6]
Power Apps and Automate indicate this connector is available in all regions except US Government (GCC High). I think this is inaccurate because I do not see it available in US Gov - GCC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1214f622-5b88-afa0-54cb-eae8ea4b3bfd
* Version Independent ID: d5efdba5-d278-73e4-1571-13abe8474c40
* Content: [Power BI - Connectors](https://docs.microsoft.com/en-us/connectors/powerbi/)
* Content Source: [docs/PowerBI/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/PowerBI/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment]
Thank you for your feedback. This is now under review and no further action is required at this time.

**Comment by dougelliott** [comment]
This feedback has been passed to the relevant product team for review.
