### ISSUE TITLE
Repeating Control functionality doesn't work (generated document won't open)

### ISSUE THREAD

**Issue by AngK72** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#60]
I tried using the repeating control in MS Word as recommended (add a table, apply the repeating control, and nest controls within) but found that the Word document doesn't open once it is generated by Flow.  I've tried using OneDrive and SharePoint Online to store the original template with the same results.  I determined (by method of elimination of controls one "type" at a time) that the repeating controls were causing the issue.  Any help with this would be much appreciated.  Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d39ce977-b1fc-d4be-3776-ad31a5b780ec
* Version Independent ID: 21c81572-7742-f033-cdc1-07c1090e9878
* Content: [Word Online (Business) - Connectors](https://docs.microsoft.com/en-us/connectors/wordonlinebusiness/)
* Content Source: [docs/wordonlinebusiness/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/wordonlinebusiness/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment]
Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) or to the connector-specific support contact (if applicable).
