### ISSUE TITLE
Unable to create secondary connection for mailbox in same tenant

### ISSUE THREAD

**Issue by pavansarma93** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#63]
Unable to create a secondary connection for this connector with below scenario.

eg: Flow created by pavan@abc.com ; I want to send email from a standard mailbox say ITTeam@abc.com. 

The sign in always detects me only and does not allow me to sign in with the ITTeam account.

How to over come this ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc40a098-af8c-d8a9-4538-71d184efbe91
* Version Independent ID: 0ee8cf79-18e9-d923-607f-ef40cdd23e4d
* Content: [Office 365 Outlook - Connectors](https://docs.microsoft.com/en-us/connectors/office365/)
* Content Source: [docs/office365/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/office365/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment]
Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) or to the connector-specific support contact (if applicable).
