### ISSUE TITLE
unauthorized error while executing custom connector from LogicApp

### ISSUE THREAD

**Issue by sunkada** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#64]
Hello Team, I have followed the documentation and crated Logic App custom connector and using OpenAPI linked with Text Analytics cognitive services. However while running the Logic App having custom connector step failing and throwing error "Unauthorized".  I tried multiple times resetting the API Key and SharePoint login but doesnt help. 
![image](https://user-images.githubusercontent.com/48080950/80178495-fc19a700-861b-11ea-879c-c390de871e70.png)

**Comment by bezhan-msft** [comment]
Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) or to the connector-specific support contact (if applicable).

We already have an open issue to confirm the validity of the steps in our custom connector creation tutorial, so I will close this issue under the notion that the other issue will verify any errors in our documentation.
