### ISSUE TITLE
Logic App Support for Bayeux Protocol/CometD

### ISSUE THREAD

**Issue by mark-at-exelon** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#67]
Wondering if there's a way to write a Connector in Logic Apps that will support long polling over the Bayeux protocol (CometD) to be a receiver/subscriber for Salesforce Platform Events. The current LA Salesforce connector does not mention PE's, and assuming that is using REST apis.  Here is Salesforce's doc on being a streaming client: https://developer.salesforce.com/docs/atlas.en-us.api_streaming.meta/api_streaming/using_streaming_api_client_connection.htm

**Comment by bezhan-msft** [comment]
Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) or to the connector-specific support contact (if applicable).
