### ISSUE TITLE
Feels incorrect ...

### ISSUE THREAD

**Issue by coolsambit** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#7]
If you want to created a trigger but you don't have an OpenAPI definition, you can ... :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0df6a505-f725-a402-da3d-4e400e0f6fc1
* Version Independent ID: fad34bde-59a4-4330-c389-15ce64ac08b8
* Content: [Use a webhook as a trigger for Azure Logic Apps and Power Automate](https://docs.microsoft.com/en-us/connectors/custom-connectors/create-webhook-trigger#feedback)
* Content Source: [docs/custom-connectors/create-webhook-trigger.md](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/custom-connectors/create-webhook-trigger.md)
* Service: **flow**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by dougelliott** [comment]
Thanks for the callout on that, @coolsambit! I've gone ahead and put in a change for the error. That should go out sometime next week.

We'll consider this as resolved and close the issue.
