### ISSUE TITLE
outlook events

### ISSUE THREAD

**Issue by mkaashif88** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#71]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca6193ac-2539-73fb-27a8-134722eac6ac
* Version Independent ID: c9a83b37-0105-cf97-d5b9-ad20a4420986
* Content: [Office 365 Outlook - Connectors](https://docs.microsoft.com/en-us/connectors/office365connector/)
* Content Source: [docs/Office365Connector/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Office365Connector/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment]
Hello - this issue has been closed due to lack of information. If you have more information to provide, please reopen this issue.
