### ISSUE TITLE
How does it get the user's present status and know that he/she is online before send out the IM message through SfB connector?

### ISSUE THREAD

**Issue by Lesley0122** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#72]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 237add0b-60ed-a848-7b26-087e0a5252a1
* Version Independent ID: 0fb50e48-7be1-d023-83a6-4f62eb332976
* Content: [Skype for Business Online - Connectors](https://docs.microsoft.com/en-us/connectors/skypeforbiz/)
* Content Source: [docs/skypeforbiz/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/skypeforbiz/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment]
Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) or to the connector-specific support contact (if applicable).
