### ISSUE TITLE
Business Central Connector - Create Record

### ISSUE THREAD

**Issue by Godfather3300** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#73]
[Enter feedback here]
Hi

I can't see all my tables under Table name dropdown menu. I have the table I am looking for exposed in BC. I am not sure how to get the table to pull in this connector so I can create the flow I am looking for (opportunities table)

Thank you

---
![image](https://user-images.githubusercontent.com/64495780/80525268-90ef0e00-8956-11ea-95b5-035c83db8d33.png)

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fedc2db-772f-c6d2-7769-c132ad5bc457
* Version Independent ID: def5bf08-c74c-5041-cf68-61491df338d4
* Content: [Business Central - Connectors](https://docs.microsoft.com/en-us/connectors/dynamicssmbsaas/#create-record)
* Content Source: [docs/dynamicssmbsaas/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/dynamicssmbsaas/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment]
Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) or to the connector support contact (if applicable).
