### ISSUE TITLE
Logo is stretched

### ISSUE THREAD

**Issue by andreujuanc** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#76]
Logo is stretched, looks unprofessional.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9a5a57d-aa82-9c07-5502-bd3be89773dc
* Version Independent ID: 5bdbf2ae-5c31-7a59-56f0-09d568602012
* Content: [Microsoft Forms - Connectors](https://docs.microsoft.com/en-us/connectors/microsoftforms/)
* Content Source: [docs/MicrosoftForms/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/MicrosoftForms/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment]
Logos are submitted by the product team - can you please attach a screenshot of where/how you are seeing the logo being stretched?

**Comment by andreujuanc** [comment]
Can't submit a fix myself, so here is a summary of the problem:
It only occurs in Firefox as far as I could tell.

Removing the  `flex-basis` from the following class fixes the problem and it does not break any other browser. The property is invalid in chrome anyway. 
```css
.summaryHolder > img {
    height: 64px;
    flex-shrink: 1;
    flex-basis: max-content; /* REMOVE THIS */
    margin-right: .5rem;
}
```
Firefox screenshot:
![imagen](https://user-images.githubusercontent.com/360052/80704759-74351080-8ae5-11ea-9138-9d0a4b8c5582.png)

**Comment by bezhan-msft** [comment]
@ShyamSunder90 could you please take a quick look at this as well?

**Comment by v-aangie** [comment]
@andreujuanc - Thanks for your feedback. We have updated the docs to fix the logo in https://docs.microsoft.com/en-us/connectors/microsoftforms/?branch=master, and the updated content is live. Closing this issue.

**Comment by andreujuanc** [comment]
Hi @v-aangie  it still looks bad to me. Is it a cache issue now?
![image](https://user-images.githubusercontent.com/360052/130300684-a2c1cc26-9058-4f7e-a8b3-de605a0571eb.png)

**Comment by v-aangie** [comment]
Hi Juan,

I'm looking into this. It looks fine to me, as in this example:

***@***.***

**Comment by v-aangie** [comment]
![image](https://user-images.githubusercontent.com/68758324/130491108-bb0fa339-e823-4b06-93aa-561f1952a802.png)

**Comment by andreujuanc** [comment]
@v-aangie  what browser do you use? issue appears to be firefox only.

**Comment by v-aangie** [comment]
I'm using Edge. I've asked someone to check it in Firefox.
