### ISSUE TITLE
Flag Email and Mark as Read/Unread no longer works on items from Shared Boxes

### ISSUE THREAD

**Issue by dezrrehm** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#80]
{
  "error": {
    "code": "ErrorInvalidMailboxItemId",
    "message": "Item Id doesn't belong to the current mailbox.",
    "innerError": {
      "request-id": "...",
      "date": "..."
    }
  }
}

**Comment by bezhan-msft** [comment]
Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) or to the connector-specific support contact (if applicable).

This should also have been fixed.
