### ISSUE TITLE
Maximum file size for general operations

### ISSUE THREAD

**Issue by stuartahonour** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#87]
What are the file size operation limits when using this connector

Maximum file size for general operations (in MB)
Maximum file size for create file operation (in MB)
Maximum file size for read file operation (in MB)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aac5ca07-a702-d56d-b870-453dfc387f18
* Version Independent ID: d805f896-39ab-2689-ca43-ccdf853dd4b9
* Content: [Google Drive - Connectors](https://docs.microsoft.com/en-us/connectors/googledrive/#feedback)
* Content Source: [docs/GoogleDrive/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/GoogleDrive/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by DougKlopfenstein** [comment]
@stuartahonour Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) or to the connector-specific support contact (if applicable).
