### ISSUE TITLE
Dynamics 365 and Common Data Service - List Records - outputs not visible after flow runs

### ISSUE THREAD

**Issue by dmaxwe22** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#88]
After a flow runs normally we see the results of the List Records action. However, recently the results or Outputs are not visible. At times I see results in the Outputs section and then it quickly collapses.   Results cannot be access and the only portion of the component in the lower part is the message:  "Status Reason" 200, and the "Show less" selector.  In order to view the results (Outputs) we need to use a Compose action or Filter etc... and then can see the outputs of the List Records on those actions but not on the Dynamics 365 outputs.  The same is true for Common Data Service whether or not is is the old or new version. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78bf3518-bce4-ecc5-8bf6-1fb627b9105e
* Version Independent ID: d46568f2-e080-cbbe-2f7e-a655bce20b64
* Content: [Common Data Service (current environment) - Connectors](https://docs.microsoft.com/en-us/connectors/commondataserviceforapps/)
* Content Source: [docs/commondataserviceforapps/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/commondataserviceforapps/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by DougKlopfenstein** [comment]
@dmaxwe22 Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) or to the connector-specific support contact (if applicable).
