### ISSUE TITLE
PowerApps for (O365) Admins?

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#9]
When I first saw the title of this page, I thought, "Great! A way to access O365 admin data via PowerApps!" Alas, turns out that is not the case.  Is there a way to access Admin Center info for O365 admins, such as seeing what service plans a users has, what items are in quarantine, etc..?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1faea297-c470-ea36-66fb-566720727487
* Version Independent ID: 5fa0970f-ea2a-a168-fb18-920f15b02725
* Content: [PowerApps for Admins - Connectors](https://docs.microsoft.com/en-us/connectors/powerappsforadmins/)
* Content Source: [docs/powerappsforadmins/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/powerappsforadmins/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by bezhan-msft** [comment]
Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback)
