### ISSUE TITLE
Allow Limit for pagination/reduction of returned items

### ISSUE THREAD

**Issue by lsschultze** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#90]
I have a team calendar project that people keep their schedule on.  I'd like to know updates to it.  Currently it has more than 1000 items, so it is returning a pagination issue.  Was thinking of limiting to the last 1000 items and being able to post changes into Microsoft teams.  This would require updating When a task is created (V2) to allow for a 'limit' parameter.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 721b75a0-c7d7-b9da-9c36-a402e5d1f6a5
* Version Independent ID: 579c5b41-d01b-5616-c812-d6058e274f30
* Content: [Asana - Connectors](https://docs.microsoft.com/en-us/connectors/asana/#feedback)
* Content Source: [docs/Asana/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Asana/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by DougKlopfenstein** [comment]
@lsschultze Hello - thank you for your feedback.

The documentation should describe the functionality of the connector, not the end API. If the connector itself does not contain certain actions and triggers that you are requesting, please instead make a [feature request](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback).
