### ISSUE TITLE
Convert HTML to Text Does not load for me if I have to edit the html code in Flow.

### ISSUE THREAD

**Issue by tlanza89** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#91]
It works perfectly when I'm first setting up the connection and pasting in my HTML code. However, if/when I need to adjust the code in my flow, it will not open and stalls out my browser window.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 413f88f9-2b3c-172b-a74a-a533fcd167de
* Version Independent ID: b9ee8f92-b5b8-f2a3-51e6-f93a7c913567
* Content: [Content Conversion - Connectors](https://docs.microsoft.com/en-us/connectors/conversionservice/)
* Content Source: [docs/conversionservice/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/conversionservice/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by DougKlopfenstein** [comment]
@tlanza89 Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) or to the connector-specific support contact (if applicable).
