### ISSUE TITLE
Need to show that this connector is deprecated.

### ISSUE THREAD

**Issue by readyxrm** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#92]
https://docs.microsoft.com/en-us/power-platform/important-changes-coming#dynamics-365-connector-is-deprecated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2294a2b5-f7af-95bf-5a38-4391dd90cdd6
* Version Independent ID: 4221f8bb-e548-5e5f-ce3a-b477d221a468
* Content: [Dynamics 365 - Connectors](https://docs.microsoft.com/en-us/connectors/dynamicscrmonline/?source=docs#feedback)
* Content Source: [docs/dynamicscrmonline/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/dynamicscrmonline/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by DougKlopfenstein** [comment]
@readyxrm Thanks for your feedback. The Dynamics 365 connector reference article now shows the connector as deprecated.
