### ISSUE TITLE
How to write Filter expression for triggers? OData style does not work!

### ISSUE THREAD

**Issue by luoyong0201** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#94]
I use statuscode eq 1 or statuscode eq 552590009 or statuscode eq 552590006 or statuscode eq 552590007 for Filter expression for triggers. it report error when the flow triggered. Exception parsing (statuscode eq 1 or statuscode eq 552590009 or statuscode eq 552590006 or statuscode eq 552590007) submitted for attribute filterexpression of callback registration.  but it works in web api of power apps. how to write correct filter expression?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78bf3518-bce4-ecc5-8bf6-1fb627b9105e
* Version Independent ID: d46568f2-e080-cbbe-2f7e-a655bce20b64
* Content: [Common Data Service (current environment) - Connectors](https://docs.microsoft.com/en-us/connectors/commondataserviceforapps/#feedback)
* Content Source: [docs/commondataserviceforapps/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/commondataserviceforapps/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by DougKlopfenstein** [comment]
@luoyong0201 Thank you for your feedback.

This seems to be product feedback or a request for product support. Please direct those queries to the [product forums](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback) or to the connector-specific support contact (if applicable).
