### ISSUE TITLE
Support rich text on post message

### ISSUE THREAD

**Issue by blakegearin** [MicrosoftDocs/BusinessApplicationPlatform-Connectors-public#95]
Looks like the Yammer API has the parameter "is_rich_text" which could be exposed in the Yammer connector for Flow usage: https://developer.yammer.com/docs/messages-json-post

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1138ec49-b24f-cd93-83d1-6711e5d3d823
* Version Independent ID: fdf01299-53e3-023e-01c7-f6817a07b6b9
* Content: [Yammer - Connectors](https://docs.microsoft.com/en-us/connectors/yammer/#feedback)
* Content Source: [docs/Yammer/index.yml](https://github.com/MicrosoftDocs/BusinessApplicationPlatform-Connectors/blob/live/docs/Yammer/index.yml)
* Service: **connectors**
* GitHub Login: @miriver
* Microsoft Alias: **miriver**

**Comment by blakegearin** [comment]
Here are some folks that agree this should be implemented :slightly_smiling_face:
* [Microsoft Power Automate Community](https://powerusers.microsoft.com/t5/Power-Automate-Ideas/enabling-rich-text-html-format-in-yammer-post-using-MS-Flow/idi-p/27276)
* [Power Automate Exchange](https://www.flowug.com/communities/community-home/digestviewer/viewthread?GroupId=2273&MessageKey=cd9aa19b-d504-4bd7-aef5-14b8ef689bde&CommunityKey=1fed0d45-1f4a-4b0c-b1f8-4dd5397a847f&tab=digestviewer)

**Comment by DougKlopfenstein** [comment]
@blakegearin Hello - thank you for your feedback.

The documentation should describe the functionality of the connector, not the end API. If the connector itself does not contain certain actions and triggers that you are requesting, please instead make a [feature request](https://docs.microsoft.com/en-us/connectors/custom-connectors/provide-feedback).
